ceph/ceph-container

mds/README.md, mds/ceph-mds@a.service, mds/entrypoint.sh, mon/README.md, mon/ceph-mon.service, mon/entrypoint.sh, osd/ceph-osd.service, rados/README.md, rbd-lock/README.md, rbd-unlock/README.md, rbd/README.md
Update README and example files to reflect the new Docker image names (ulexus -> ceph)
=> Update docs to change ulexus -> ceph

config/entrypoint.sh
This should fix #36 by checking the return code of etcdctl rather than stderr.
=> Fix existence check

config/entrypoint.sh
=> Fix config etcdctl

README.md, docker-registry/Dockerfile, docker-registry/README.md
=> docker-registry

osd/README.md
Add the command to create an OSD.
Closes: #40 
=> Improve OSD README

kubernetes/README.md, kubernetes/ceph-mon.json
I recently gave a first and quick try to Kubernetes.
This is a first step toward running Ceph in Docker managed by
Kubernetes.
=> Add a k8s pod file

daemon/entrypoint.sh
The user must explicitly set it to 1.
=> Force zap should be disable by default

daemon/entrypoint.sh
=> Retry common OSD handler

examples/kubernetes/ceph-mon.json
=> Update the pod file

daemon/entrypoint.sh
=> Fix condition

examples/kubernetes/ceph-mon.json
=> Use ceph/daemon for k8s

daemon/README.md, daemon/entrypoint.sh
=> Change MDS name to avoid numeric values

README.md
=> Video demo

demo/Dockerfile, demo/entrypoint.sh
Refer to https://github.com/ceph/ceph-docker/issues/107
=> Add ceph-rest-api to ceph/demo

daemon/README.md, daemon/entrypoint.sh
Attempt to fix #55.
Signed-off-by: leseb <seb@redhat.com>
=> Add a ceph-rest-api daemon

daemon/entrypoint.sh
=> bugfix part 2: restapi

daemon/config.kv.sh, daemon/config.static.sh, daemon/entrypoint.sh
=> Crush location expert and multi cluster support

demo/entrypoint.sh
Fixes: #130
Signed-off-by: leseb <seb@redhat.com>
=> Ability to re-use an existing ceph/demo cluster

examples/coreos/rbdmap/README.md, examples/coreos/rbdmap/rbdmap, examples/coreos/rbdmap/rbdmap.service
The service file wasn't quite working, and the docs were lacking some vital details.
=> Updated docs and fixed service file so that it actually works

README.md
Deploy ceph in docker with ansible video.
=> Add video with ansible

daemon/entrypoint.sh
=> Fix key addition for osd_directory scenario

demo/README.md
https://github.com/ceph/ceph-docker/issues/145
=> Updated ceph-demo README for issue #145 user_xattr

demo/entrypoint.sh
enable multiple clusters in same box with host networking.
add missing --cluster in ceph osd/fs/etc commands. add cluster aware
monmap creation and reference (allows different port in the mon).
=> add missing cluster option in demo cmds and config.

base/Dockerfile, daemon/entrypoint.sh
=> some fixes

base/Dockerfile, daemon/config.static.sh, daemon/entrypoint.sh
Use Ceph's last stable version.
=> Use Infernalis

daemon/README.md
Get stable OSDs and proper recommendation when using SELinux.
=> Add more doc

daemon/config.kv.sh
etcdtcl exits if key already exists
=> etcdtcl exits if key already exists

base/Dockerfile
Signed-off-by: Ulexus <ulexus@gmail.com>
=> etcd version bump: 2.2.4

daemon/entrypoint.sh
=> since ceph-disk activate already starts ceph-osd, don't rerun it; just wait till it exits

daemon/entrypoint.sh
=> Revert "since ceph-disk activate already starts ceph-osd, don't rerun it; just wait till it exits"

daemon/entrypoint.sh
=> since ceph-disk activate already starts ceph-osd, don't rerun it; just wait till it exists

daemon/entrypoint.sh
This is to fix issue #212 introduced by pull request #207
=> ceph-daemon: update broken OSD startup

daemon/entrypoint.sh
The previous commit did not entirely fix the problem, sorry about that :/
=> ceph-daemon: update broken OSD startup (fix check)

daemon/README.md, daemon/entrypoint.sh
=> split osd disk to disk prepare and disk activate

examples/atomic/unit/ceph-mon@.service, examples/atomic/unit/ceph-osd@.service
=> add systemd unit files for OSes like REHL Atomic

daemon/README.md
Use consistent formatting for directory name.
=> Minor formatting fix

daemon/README.md
The default port number of rgw has been changed after PR #201.
=> Correct the document wrong about default rgw port number

daemon/entrypoint.sh
Properly handle specifying an OSD_JOURNAL when OSD_TYPE=disk.  If we specify an OSD_DEVICE and an OSD_JOURNAL with the disk type, don't attempt to partition the OSD_DEVICE - just go with what the user has specified for block devices.
=> Properly handle OSD_JOURNAL for OSD_TYPE=disk

base/Dockerfile, daemon/Dockerfile
Reduce the number of layers in ceph/base and ceph/daemon.  Mostly accomplished by chaining RUN statements together, and occasionally coalescing ADDs.
=> Shrink the layer count

daemon/entrypoint.sh
osd is activated in `osd_activate`
=> don't activate osd in osd_disk_prepare

daemon/entrypoint.sh
want to float the idea first. The new command will be used when udev triggers `ceph-disk activate-journal`
@leseb
=> WIP: add osd_activate_journal to match ceph-disk activate-journal command

config/ceph-config.service
It seems the image name changed from ceph/ceph-config to ceph/config.
=> Update ceph-config image

config/README.md
=> config: deprecation warning

daemon/config.static.sh
'/etc/ceph/ceph.mon.keyring' has been chown twice.:)
=> '/etc/ceph/ceph.mon.keyring' is repeated.

daemon/config.static.sh
this implements #249 
@Ulexus @leseb
=> implement #249

daemon/entrypoint.sh
fixes #256 . I've only tested this with `--bluestore`
=> Adds variable to pass flags to ceph-disk's prepare

base/Dockerfile, daemon/Dockerfile
=> Jewel daemon

ceph-docker-workflow.sh
Most of the actual files are in fact symlinks.
The current code was detecting changes on the original file but not on
the linked ones leading to a situation where some distro were forgoten.
Like ubuntu 16 linking ubuntu 14, a change in u14 didn't triggered a
rebuild for u16.
This patch does two things :
- creating a map between the links and the original files
- making a lookup between those impacted file and the missing distro
As a result, this patch flags the distros that have linked file as
impacted once the original is touched.
=> ceph-docker-workflow: Don't forget symlinked builds

ceph-releases/hammer/centos/7/base/README.md, ceph-releases/hammer/ubuntu/14.04/base/README.md, ceph-releases/hammer/ubuntu/14.04/daemon/README.md, ceph-releases/hammer/ubuntu/14.04/demo/README.md, ceph-releases/hammer/ubuntu/16.04/base/README.md, ceph-releases/infernalis/centos/7/base/README.md, ceph-releases/infernalis/ubuntu/14.04/base/README.md, ceph-releases/infernalis/ubuntu/14.04/daemon/README.md, ceph-releases/infernalis/ubuntu/14.04/demo/README.md, ceph-releases/infernalis/ubuntu/16.04/base/README.md, ceph-releases/jewel/centos/7/base/README.md, ceph-releases/jewel/fedora/23/base/README.md, ceph-releases/jewel/ubuntu/14.04/base/README.md, ceph-releases/jewel/ubuntu/14.04/daemon/README.md, ceph-releases/jewel/ubuntu/14.04/demo/README.md, ceph-releases/jewel/ubuntu/16.04/base/README.md
=> dummy commit to trigger a docker build

README.md, generate-dev-env.sh
=> Fix readme

ceph-releases/hammer/centos/7/base/Dockerfile, ceph-releases/hammer/centos/7/daemon/Dockerfile, ceph-releases/hammer/ubuntu/14.04/base/Dockerfile, ceph-releases/hammer/ubuntu/14.04/daemon/Dockerfile, ceph-releases/hammer/ubuntu/16.04/base/Dockerfile, ceph-releases/hammer/ubuntu/16.04/daemon/Dockerfile, ceph-releases/infernalis/centos/7/base/Dockerfile, ceph-releases/infernalis/centos/7/daemon/Dockerfile, ceph-releases/infernalis/ubuntu/14.04/base/Dockerfile, ceph-releases/infernalis/ubuntu/14.04/daemon/Dockerfile, ceph-releases/infernalis/ubuntu/16.04/base/Dockerfile, ceph-releases/infernalis/ubuntu/16.04/daemon/Dockerfile, ceph-releases/jewel/centos/7/base/Dockerfile, ceph-releases/jewel/centos/7/daemon/Dockerfile, ceph-releases/jewel/ubuntu/14.04/base/Dockerfile, ceph-releases/jewel/ubuntu/14.04/daemon/Dockerfile, ceph-releases/jewel/ubuntu/16.04/base/Dockerfile, ceph-releases/jewel/ubuntu/16.04/daemon/Dockerfile
Packages installation should only happen in the base image.
=> daemon: remove all the package installations

.travis.yml, ceph-releases/hammer/ubuntu/14.04/demo/entrypoint.sh, ceph-releases/infernalis/ubuntu/14.04/demo/entrypoint.sh, ceph-releases/jewel/ubuntu/14.04/demo/entrypoint.sh, travis-builds/build_imgs.sh, travis-builds/prepare_osd_fs.sh, travis-builds/validate_cluster.sh, travis-builds/validate_demo_cluster.sh
The mds needs a couple of seconds to create its pools and appear as up
on the monitor side. We allow us to wait until 10sec and we fail if
nothing comes up.
=> ci: improve mds check

ceph-releases/hammer/ubuntu/16.04/base/Dockerfile, ceph-releases/infernalis/centos/7/daemon/Dockerfile, ceph-releases/infernalis/ubuntu/14.04/daemon/Dockerfile, ceph-releases/infernalis/ubuntu/16.04/base/Dockerfile, ceph-releases/infernalis/ubuntu/16.04/daemon/Dockerfile, ceph-releases/jewel/centos/7/daemon/Dockerfile, ceph-releases/jewel/ubuntu/16.04/base/Dockerfile
=> bunch of fixes for the builds to succeed

ceph-docker-workflow.sh
We don't always want to run the workflow script but perhaps just want to
look at the changes that will be applied. So now you can run the script
with `--dry-run`.
[ci skip]
=> workflow: add a dry run option

ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh
All the ceph tools support symlinks for the devices (such as /dev/disk/by-path) but `ceph-disk` list will give the canonical names, so we need to resolve the symlink when we grep the output from ceph-disk
=> entrypoint: accept /dev/disk/by-x names for OSD_DEVICE

ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh
In the first statement, we check the disk partition existed.
Actually, there exist the same conditional statement below.
We can combine them.
=> Combine the same if-statements

ceph-releases/hammer/ubuntu/14.04/daemon/config.kv.sh, ceph-releases/hammer/ubuntu/14.04/daemon/entrypoint.sh, ceph-releases/infernalis/ubuntu/14.04/daemon/config.kv.sh, ceph-releases/infernalis/ubuntu/14.04/daemon/entrypoint.sh, ceph-releases/jewel/ubuntu/14.04/daemon/config.kv.sh, ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh
i found two small issues that prevent the daemon image to startup
=> fixing KV using etcd /w ssl 

ceph-releases/jewel/centos/7/daemon/my_init/my_init, ceph-releases/jewel/ubuntu/14.04/daemon/my_init/my_init
=> Runit exited with status 127

ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh
Prior to this path, so socket was created only during the boostrap
sequence of the ceph daemon. So when the container restarts/die and
start the path is not present anymore, preventing daemons to properly
start. We always create this directory no matter what.
=> jewel: create socket dir at the beginning of the function

ceph-releases/jewel/ubuntu/14.04/daemon/config.static.sh, ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh
Signed-off-by: daniel lin <danielin@umich.edu>
=> Changes to allow for clusters not named ceph

ceph-releases/hammer/ubuntu/14.04/daemon/config.kv.sh, ceph-releases/hammer/ubuntu/14.04/daemon/config.static.sh, ceph-releases/hammer/ubuntu/14.04/daemon/entrypoint.sh, ceph-releases/infernalis/ubuntu/14.04/daemon/config.k8s.sh, ceph-releases/infernalis/ubuntu/14.04/daemon/config.kv.sh, ceph-releases/infernalis/ubuntu/14.04/daemon/config.static.sh, ceph-releases/infernalis/ubuntu/14.04/daemon/entrypoint.sh, ceph-releases/jewel/ubuntu/14.04/daemon/config.k8s.sh, ceph-releases/jewel/ubuntu/14.04/daemon/config.kv.sh, config/entrypoint.sh
monmap naming scheme extended across all calls to get_mon_config
Signed-off-by: Daniel Lin <danielin@umich.edu>
=> Fix for #357 KV clusters do not work

README.md, ceph-releases/jewel/centos/7/base/Dockerfile, ceph-releases/jewel/centos/7/daemon/Dockerfile, ceph-releases/jewel/fedora/24/base/Dockerfile, ceph-releases/jewel/fedora/24/daemon/Dockerfile, ceph-releases/jewel/ubuntu/14.04/base/Dockerfile, ceph-releases/jewel/ubuntu/14.04/daemon/Dockerfile, ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh, ceph-releases/jewel/ubuntu/14.04/demo/entrypoint.sh, ceph-releases/jewel/ubuntu/16.04/base/Dockerfile, ceph-releases/jewel/ubuntu/16.04/daemon/Dockerfile
Add the Ganesha NFS gateway to the daemon.  This allows accessing the
RadosGW via NFS.
Signed-off-by: Daniel Gryniewicz <dang@redhat.com>
=> Add support for NFS Gateway

ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh
This commit does 2 main things:
* implement multi device support
* add some safety checks
* do more detection on the device
=> daemon: improve purge scenario

ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh
pgrep can exit 1 if no results are found
This should fix #370
=> entrypoint: ignore pgrep exit code

ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh
=> daemon: fix ipv6 subnet

ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh
=> daemon: do not execute mon functions is mon exit

ceph-releases/hammer/ubuntu/14.04/daemon/config.kv.sh
=> fixed #373: config.kv.sh: conf file path error

ceph-releases/jewel/redhat/7.2/Dockerfile, ceph-releases/jewel/redhat/7.2/README.md, ceph-releases/jewel/redhat/7.2/all.sh, ceph-releases/jewel/redhat/7.2/build.sh, ceph-releases/jewel/redhat/7.2/config.kv.sh, ceph-releases/jewel/redhat/7.2/config.no-gen.sh, ceph-releases/jewel/redhat/7.2/config.static.sh, ceph-releases/jewel/redhat/7.2/entrypoint.sh, ceph-releases/jewel/redhat/7.2/install.sh
@dang @rootfs @font @jimcurtis 
[ci skip]
=> add rhel image

ceph-releases/jewel/centos/7/base/Dockerfile, ceph-releases/jewel/fedora/24/base/Dockerfile
A small change to include the `nfs-ganesha-ceph` packages in the base images
=> Centos/Fedora NFS ceph

README.md, travis-builds/validate_cluster.sh
Signed-off-by: Alfredo Deza <adeza@redhat.com>
=> add a note on the new CI testing in Jenkins

ceph-releases/jewel/ubuntu/14.04/daemon/config.static.sh
- Fix for #398
- Fix indentation
Signed-off-by: Ivan Font <ifont@redhat.com>
=> Check if ip command is available before using it

tests/.gitignore, tests/README.md, tests/base/test_monitors.py, tests/conftest.py, tests/requirements.txt
Driven with Python, and just doing Monitor images for now. Not all tests are passing (issues are opened for most of the failing tests)
=> initial take on running tests for all container images

tests/README.md, tests/base/test_monitors.py, tests/conftest.py
And corrects some mismatched tags for Jewel/Hammer tests
=> Prune unsupported Fedora 23

ceph-releases/jewel/ubuntu/14.04/daemon/config.k8s.sh, ceph-releases/jewel/ubuntu/14.04/daemon/config.kv.sh, ceph-releases/jewel/ubuntu/14.04/daemon/config.static.sh, ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh, ceph-releases/jewel/ubuntu/14.04/demo/entrypoint.sh
I'm only applying this to Jewel for now.
=> Add common logging function

ceph-releases/hammer/centos/7/daemon/remove-mon.sh, ceph-releases/hammer/fedora/23/daemon/ceph.defaults
=> add remove-mon.sh to hammer centos

ceph-releases/hammer/centos/7/base/Dockerfile, ceph-releases/hammer/centos/7/daemon/check_zombie_mons.py
add missing file check_zombie_mons.py
=> hammer centos fix build

tests/base/test_monitors.py
=> test: fix monmap name check

ceph-releases/hammer/ubuntu/14.04/demo/entrypoint.sh, ceph-releases/infernalis/ubuntu/14.04/demo/entrypoint.sh, ceph-releases/jewel/ubuntu/14.04/demo/entrypoint.sh
re-using the same convention as traditionnal entrypoints
=> normalize monmap names

travis-builds/purge_cluster.sh
- Only run container status command once
Signed-off-by: Ivan Font <ifont@redhat.com>
=> Update purge cluster script for travis builds

ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh
=> osd: try to activate when the osd if exist

tests/base/test_monitors.py, tests/conftest.py
We are no longer supporting hammer
=> Rm hammer tests

examples/kubernetes-coreos/startup.sh
Minor spelling correction made to file path.
=> Spelling correction

examples/kubernetes/ceph-cephfs-test.yaml, examples/kubernetes/ceph-mon-v1-dp.yaml, examples/kubernetes/ceph-mon-v1-ds.yaml, examples/kubernetes/ceph-rbd-test.yaml, examples/kubernetes/create_ceph_cluster.sh, examples/kubernetes/create_secrets.sh, examples/kubernetes/delete_ceph_cluster.sh
- Add label and namespace to ceph tests
- Cleanup storage node-type label from all nodes
- Script to just create kube ceph secrets
- Default to use IPv4 even if IPv6 address exists
=> Updates to Kubernetes example

examples/kubernetes/README.md, examples/kubernetes/ceph-cephfs-test.yaml, examples/kubernetes/ceph-mds-v1-dp.yaml, examples/kubernetes/ceph-rbd-test.yaml, examples/kubernetes/ceph-rgw-v1-dp.yaml, examples/kubernetes/create_secrets.sh, examples/kubernetes/gke/README.md, examples/kubernetes/rbd-pv-claim.yaml, examples/kubernetes/rbd-pv.yaml, examples/kubernetes/rbd-pvc-pod.yaml, examples/kubernetes/rbd-storage-class.yaml, examples/kubernetes/rgw_s3_client.py
- Documentation for Ceph cluster on GKE K8s cluster
- Update CephFS and RBD tests to use nodeSelector
- Fix RGW pod errors connecting to the cluster
See commit log for more details.
=> Documentation for Ceph cluster on GKE K8s cluster

examples/kubernetes/README.md
Mention that the Kubernetes example will not survive kubernetes cluster restarts.
=> Doc: Kube example does not survive cluster restart

examples/kubernetes/create_ceph_cluster.sh
=> Revert "Don't validate yml files for creating the cluster"

ceph-releases/jewel/ubuntu/14.04/daemon/README.md, ceph-releases/kraken/ubuntu/16.04/daemon/README.md, examples/kubernetes-coreos/README.md
These are pretty important fixes for someone like me following along in the documentation and examples.
=> Documentation: Fix osd_directory and ceph-install errors

tox.ini, travis-builds/build_imgs.sh
Signed-off-by: Andrew Schoen <aschoen@redhat.com>
=> tests: enable CI testing of kraken images

ceph-releases/kraken/ubuntu/16.04/daemon/entrypoint.sh
ceph-disk got a new activation option to not run the OSD process. So we
force this and let our entrypoint run the OSD.
Fixes: #479
=> osd: do not start daemon during activation

ceph-releases/kraken/ubuntu/16.04/daemon/start_osd.sh
Commit 0cf40ef6bb59 reorganized script scructure, but break osd_ceph_disk
=> daemon: fix osd_ceph_disk scenario

ceph-releases/hammer/ubuntu/14.04/demo/entrypoint.sh, ceph-releases/infernalis/ubuntu/14.04/demo/entrypoint.sh, ceph-releases/jewel/ubuntu/14.04/demo/entrypoint.sh, ceph-releases/kraken/ubuntu/16.04/demo/entrypoint.sh
Hi, 
this is proposed resolution of #487 . Lighly tested on my test environment.
=> Set "rgw dns name" based on RGW_NAME variable

.travis.yml, ceph-releases/kraken/centos/7/demo/Dockerfile, ceph-releases/kraken/ubuntu/16.04/demo/Dockerfile
=> demo: add kraken container

.travis.yml
=> ci: test demo container image with travis

ceph-releases/kraken/ubuntu/16.04/daemon/zap_device.sh
After zapping the partitions, if we do not remove the header,
the next time the device will be partitionned a type 'crypto_LUKS'
will appear on the partition. This is really misleading when
re-deploying a brand new cluster.
=> zap: remove luks header and key from the partition

ceph-releases/kraken/ubuntu/16.04/daemon/zap_device.sh
=> daemon: zap fix typo on cryptsetup

ceph-releases/kraken/ubuntu/16.04/daemon/common_functions.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_directory.sh
Let's use a function to test if a string is an integer representation.
=> Having a common function for testing integers

examples/helm/README.md, examples/helm/build-all.sh, examples/helm/ceph/Chart.yaml, examples/helm/ceph/templates/config/configmap.yaml, examples/helm/ceph/templates/jobs/configmap.yaml, examples/helm/ceph/templates/jobs/job.yaml, examples/helm/ceph/templates/mds/deployment.yaml, examples/helm/ceph/templates/mon/deployment.yaml, examples/helm/ceph/templates/mon/service.yaml, examples/helm/ceph/templates/mon/statefulset.yaml, examples/helm/ceph/templates/osd/daemonset.yaml, examples/helm/ceph/templates/storageclass.yaml, examples/helm/ceph/values.yaml, examples/helm/tests/ceph/job.yaml, examples/helm/tests/ceph/pvc.yaml
=> helm: add initial support for k8s helm

ceph-releases/kraken/ubuntu/16.04/daemon/entrypoint.sh
As we now have to_lowercase() function, let's use it.
=> entrypoint: Using to_lowercase

ceph-releases/kraken/ubuntu/16.04/daemon/common_functions.sh, ceph-releases/kraken/ubuntu/16.04/daemon/config.static.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_mds.sh, ceph-releases/kraken/ubuntu/16.04/daemon/variables_entrypoint.sh
This PR is about cleaning up the mds code.
It does move the mkdir to the proper function.
It does also create variables for very common & repetitive paths/files. If you like this kind of change, I can propagate it to the other files.
=> Cleaning up mds code

ceph-releases/kraken/ubuntu/16.04/daemon/common_functions.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_mon.sh
=> Creating a loop & move mkdir

ceph-releases/kraken/ubuntu/16.04/daemon/common_functions.sh, ceph-releases/kraken/ubuntu/16.04/daemon/config.k8s.sh, ceph-releases/kraken/ubuntu/16.04/daemon/config.kv.etcd.sh, ceph-releases/kraken/ubuntu/16.04/daemon/config.static.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_common.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_directory.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_directory_single.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_disk_activate.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_disk_prepare.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_disks.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_mds.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_mon.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_rgw.sh, ceph-releases/kraken/ubuntu/16.04/daemon/variables_entrypoint.sh
This PR is about avoiding having all the keyrings paths to be duplicated.
It does create some new internal variables and reuse them among the code base.
=> Avoid duplicating keyring paths

ceph-releases/kraken/ubuntu/16.04/daemon/README.md, ceph-releases/kraken/ubuntu/16.04/daemon/populate_kv.sh, ceph-releases/kraken/ubuntu/16.04/daemon/variables_entrypoint.sh, examples/confd/populate.sh
=> daemon: remove consul as a KV store

ceph-releases/kraken/centos/7/daemon/osd_scenarios/osd_common.sh, ceph-releases/misslinks.sh
Adding a tool to avoid any miss-linked files.
Making the first patch to fix a link issue too.
=> Adding Misslinks

ceph-releases/kraken/ubuntu/16.04/daemon/config.kv.etcd.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_common.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_directory.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_directory_single.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_disk_activate.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_disk_prepare.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_disks.sh, ceph-releases/kraken/ubuntu/16.04/daemon/populate_kv.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_mds.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_mgr.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_mon.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_rbd_mirror.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_restapi.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_rgw.sh, ceph-releases/kraken/ubuntu/16.04/daemon/variables_entrypoint.sh
We know use a variable that contains the command line argument.
=> daemon: simply daemon startup command line

examples/helm/ceph/templates/mds/deployment.yaml, examples/helm/ceph/values.yaml
An option for releases that don't need MDS
=> Helm: Simple toggle to enable/disable mds

examples/helm/ceph/templates/rgw/deployment.yaml, examples/helm/ceph/templates/rgw/service.yaml, examples/helm/ceph/values.yaml
Adds a deployment and service for RGW
=> Helm: Basic RGW support

examples/helm/ceph/templates/exporter/deployment.yaml, examples/helm/ceph/templates/exporter/service.yaml, examples/helm/ceph/values.yaml
Adds basic support for the digitalocean ceph-exporter to allow metrics
collection
=> Helm: Prometheus exporter

ceph-releases/kraken/ubuntu/16.04/daemon/debug.sh
The fstree option wasn't functional. This PR is fixing all the found bugs in the actual code.
=> Improving fstree option

ceph-releases/kraken/ubuntu/16.04/demo/entrypoint.sh
Use the refactor of daemon in demo.
=> demo: refactor code

ceph-releases/jewel/ubuntu/14.04/daemon/common_functions.sh, ceph-releases/jewel/ubuntu/14.04/daemon/osd_scenarios/osd_activate_journal.sh, ceph-releases/jewel/ubuntu/14.04/daemon/osd_scenarios/osd_disk_activate.sh, ceph-releases/jewel/ubuntu/14.04/daemon/osd_scenarios/osd_disk_prepare.sh, ceph-releases/jewel/ubuntu/14.04/demo/entrypoint.sh, travis-builds/validate_demo_cluster.sh
Due to some timing issue, devices might take some time to appear so
instead of failing we wait for it.
=> jewel: backport of 0bfc1c8, implement a wait_for_file function

ceph-releases/infernalis/ubuntu/14.04/daemon/config.k8s.sh, ceph-releases/jewel/ubuntu/14.04/daemon/config.k8s.sh, ceph-releases/kraken/ubuntu/16.04/daemon/config.k8s.sh
=> use /etc/ceph/.conf in config.k8s.sh get_mon_config()

ceph-releases/hammer/ubuntu/14.04/daemon/entrypoint.sh, ceph-releases/infernalis/ubuntu/14.04/daemon/entrypoint.sh, ceph-releases/jewel/ubuntu/14.04/daemon/start_mds.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_mds.sh
=> use cluster config file

ceph-releases/jewel/ubuntu/14.04/daemon/start_mon.sh, ceph-releases/kraken/ubuntu/16.04/daemon/config.k8s.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_mon.sh, examples/kubernetes/ceph-mon-v1-svc.yaml
=> kubernetes mon start dns and public addr issues

ceph-releases/jewel/ubuntu/16.04/demo/Dockerfile
=> add s3cmd installation step in Dockerfile (Jewel, Ubuntu 16.04)

ceph-docker-workflow.sh, travis-builds/build_imgs.sh
Trying to make things a bit clearer
=> fix grammar in comments

tox.ini
Signed-off-by: Gregory Meno <gmeno@redhat.com>
=> changing tox factor to include tests on latest stable ceph-ansible

ceph-releases/jewel/ubuntu/14.04/daemon/start_mon.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_mon.sh, ceph-releases/luminous/ubuntu/16.04/daemon/start_mon.sh
=> Revert "daemon: try to fetch the last version of monmap"

examples/kubernetes/README.md
fixed kube-dns address, added notes on jinja2, added secret type:     `--type="kubernetes.io/rbd"`
=> fix kube-dns addr, added secret type

tests/tox.sh
=> Support CentOS/RHEL as base OS for running tests

travis-builds/build_imgs.sh
build_imgs.sh's copy_dirs() method is a no-op if the top-level "base", "daemon", and "demo" directories already exist. We use this conditional to determine what we're testing in Travis CI: are we testing a GitHub PR, or a pushed branch?
Simplify the code here to simply exit the function early. This eliminates a level of indentation so the function is easier to read and understand.
=> build_imgs.sh: simplify non-PR case in copy_dirs()

README.md
Signed-off-by: Dan Mick <dan.mick@redhat.com>
=> README.md: mention subdirectory README files for noobs

ceph-releases/jewel/ubuntu/14.04/daemon/start_mon.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_mon.sh, ceph-releases/luminous/ubuntu/16.04/daemon/start_mon.sh
First we remove the initial monmap, this monmap is really dangerous
after the initial deployment. Thus it should be deleted so we are sure
it's used later.
Also prior to this patch we were running the monitor which would fail
instantly, then create a socket and the other process would not run.
Removing this useless start and let's just the monitor start by reading
the Ceph configuration file, which will contain the list of all
monitors.
=> daemon: do not run the monitor twice

README.md
Signed-off-by: Gregory Meno <gmeno@redhat.com>
=> remove refs to utilities and wrappers that no longer exist

ceph-releases/luminous/ubuntu/16.04/daemon/demo.sh
=> demo: use an array for cmd line options

ceph-releases/kraken/ubuntu/16.04/daemon/start_mgr.sh, ceph-releases/luminous/ubuntu/16.04/daemon/start_mgr.sh
=> Daemon: fix ceph-mgr opts

ceph-releases/luminous/ubuntu/16.04/daemon/demo.sh
Use array for command line option.
=> daemon: fix demo scenario

ceph-releases/luminous/ubuntu/16.04/daemon/start_mgr.sh, ceph-releases/luminous/ubuntu/16.04/daemon/variables_entrypoint.sh
It will listen on 0.0.0.0:7000 by default, you can change this setting
MGR_IP to the desired IP.
=> daemon: enable mgr dashboard

ceph-releases/kraken/ubuntu/16.04/daemon/start_mgr.sh, ceph-releases/luminous/ubuntu/16.04/daemon/start_mgr.sh
=> Daemon: generate mgr key

ceph-releases/luminous/ubuntu/16.04/daemon/start_mgr.sh, ceph-releases/luminous/ubuntu/16.04/daemon/variables_entrypoint.sh
Use an array to call the CLI options
Also add 'mgr' to the list of scenarios.
Fixes: https://github.com/ceph/ceph-docker/issues/695
=> daemon: several mgr fixes

examples/kubernetes/README.md, examples/kubernetes/create_secrets.sh
=> Add rbd dynamic provisioning section

ceph-releases/luminous/ubuntu/16.04/daemon/config.kv.etcd.sh, ceph-releases/luminous/ubuntu/16.04/daemon/config.static.sh
Add ceph-mgr permissions when the admin keyring is create.
=> Add ceph-mgr permissions in admin keyring

ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_common.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_directory.sh, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_common.sh, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_directory.sh
=> daemon: use an array for CRUSH_LOCATION

examples/kubernetes/README.md, examples/kubernetes/ceph-osd-activate-v1-ds.yaml, examples/kubernetes/ceph-osd-prepare-v1-ds.yaml
=> add osd prepare and osd activate daemon set for osd disk persistence

ceph-releases/jewel/ubuntu/14.04/daemon/start_mon.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_common.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_mgr.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_mon.sh, ceph-releases/luminous/ubuntu/16.04/daemon/start_mon.sh
=> kraken: daemon update cli to use an array

ceph-releases/jewel/ubuntu/14.04/daemon/common_functions.sh, ceph-releases/jewel/ubuntu/14.04/daemon/osd_scenarios/osd_common.sh, ceph-releases/jewel/ubuntu/14.04/daemon/osd_scenarios/osd_directory.sh, ceph-releases/jewel/ubuntu/14.04/daemon/osd_scenarios/osd_disk_activate.sh, ceph-releases/kraken/ubuntu/16.04/daemon/common_functions.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_common.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_directory.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_disk_activate.sh, ceph-releases/luminous/ubuntu/16.04/daemon/common_functions.sh, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_common.sh, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_directory.sh, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_disk_activate.sh
Add two new functions to simplify the code.
=> daemon: functions to calculate osd weight and add osd to crush

ceph-releases/jewel/ubuntu/14.04/daemon/osd_scenarios/osd_disk_activate.sh, ceph-releases/jewel/ubuntu/14.04/daemon/osd_scenarios/osd_disk_prepare.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_disk_activate.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_disk_prepare.sh, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_disk_activate.sh, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_disk_prepare.sh
=> fixes partion name for devices like /dev/loop0

ceph-releases/jewel/fedora/24/demo/Dockerfile
Closes: https://github.com/ceph/ceph-docker/issues/744
=> jewel: add s3cfg file to demo

ceph-releases/jewel/ubuntu/14.04/daemon/osd_scenarios/osd_directory.sh, ceph-releases/jewel/ubuntu/14.04/daemon/osd_scenarios/osd_disks.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_directory.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_disks.sh, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_directory.sh, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_disks.sh
=> source osd_common.sh before running start_forego()

ceph-releases/luminous/ubuntu/16.04/daemon/demo.sh, ceph-releases/luminous/ubuntu/16.04/daemon/start_mgr.sh, ceph-releases/luminous/ubuntu/16.04/daemon/variables_entrypoint.sh
Closes: https://github.com/ceph/ceph-docker/issues/746
=> mgr: re-enable dashboard

ceph-releases/jewel/ubuntu/14.04/daemon/osd_scenarios/osd_activate_journal.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_activate_journal.sh, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_activate_journal.sh
Signed-off-by: Huamin Chen <hchen@redhat.com>
=> wait_for is not defined, use wait_for_file

ceph-releases/luminous/ubuntu/16.04/daemon/start_mgr.sh
Closes: https://github.com/ceph/ceph-docker/issues/759
=> daemon: mgr force dashboard

ceph-releases/luminous/rhel/7.3/daemon/Dockerfile, ceph-releases/luminous/rhel/7.3/daemon/README.md
=> daemon: update rhel dockerfile

ceph-releases/luminous/rhel/7.3/daemon/Dockerfile
=> Add ceph-mgr

README.md
=> contrib add: build status for docker hub

ceph-releases/jewel/ubuntu/14.04/daemon/variables_entrypoint.sh, ceph-releases/kraken/ubuntu/16.04/daemon/variables_entrypoint.sh, ceph-releases/luminous/ubuntu/16.04/daemon/variables_entrypoint.sh
added etcd schema detection
This should solve #758 
Please verify, I don't have a easy way to test this. It looks harmless but you never know.
=> added etcd schema detection, solves #758

ceph-releases/luminous/ubuntu/16.04/daemon/common_functions.sh
Closes: https://github.com/ceph/ceph-docker/issues/772
=> daemon: create bootstrap rbd directory

ceph-releases/luminous/ubuntu/16.04/daemon/start_mon.sh
=> rbd-mirorr: fix mispell keyring var

ceph-releases/luminous/ubuntu/16.04/daemon/start_nfs.sh, ceph-releases/luminous/ubuntu/16.04/daemon/variables_entrypoint.sh
- add rgw key creation
- also change rgw keyring path to the right one
=> nfs: properly configure nfs rgw

ceph-releases/luminous/ubuntu/16.04/daemon/common_functions.sh, ceph-releases/luminous/ubuntu/16.04/daemon/start_rgw.sh
=> rgw: fix key directory creation

ceph-releases/luminous/rhel/7.3/daemon/disabled_scenario
=> [skip ci] daemon: allow nfs scenario

ceph-releases/devel/wip-prometheus-testing/centos-7/daemon/ganesha.repo
=> wip-prometheus-testing: add ganesha repo file

ceph-releases/luminous/ubuntu/16.04/daemon/common_functions.sh, ceph-releases/luminous/ubuntu/16.04/daemon/disk_list.sh, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_disk_activate.sh, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_disk_prepare.sh
=> daemon: fix dmcrypt list

ceph-releases/jewel/ubuntu/14.04/daemon/common_functions.sh, ceph-releases/jewel/ubuntu/14.04/daemon/osd_scenarios/osd_disk_activate.sh
=> jewel: re-add osd weight and crush

ceph-releases/jewel/ubuntu/14.04/daemon/disk_list.sh, ceph-releases/luminous/ubuntu/16.04/daemon/disk_list.sh
=> add support for loop devices in disk_list

ceph-releases/jewel/rhel/7.3/daemon/Dockerfile
=> resync with downstream

tests/tox.sh, tox.ini, travis-builds/build_imgs.sh, travis-builds/purge_cluster.sh
=> ci: add sudo commands

ceph-releases/luminous/ubuntu/16.04/daemon/common_functions.sh, ceph-releases/luminous/ubuntu/16.04/daemon/config.static.sh, ceph-releases/luminous/ubuntu/16.04/daemon/demo.sh, ceph-releases/luminous/ubuntu/16.04/daemon/entrypoint.sh.in, ceph-releases/luminous/ubuntu/16.04/demo/ceph_demo, ceph_demo
=> [skip ci] demo: oversimply the setup

ceph-releases/jewel/ubuntu/14.04/daemon/start_mon.sh, ceph-releases/luminous/ubuntu/16.04/daemon/start_mon.sh
This fix change the mon id in monmap in case the monitor name in the monmap doesn't match the hostname of the monitor. 
This can be the case when using k8s to create the monmap from the pods labels and the hostname of the monitors are full qualified while the hostname of the servers is not full qualified.
=> Fix mon id where name in monmap doesn't match monitor name

tests/tox.sh, tox.ini
=> tests: update tox tests according to recent changes

ceph-releases/luminous/ubuntu/16.04/demo/ceph_demo
Please find in this short PR,
- two basic fixes to make it work on Fedora 27
- two commits to improve the user experience
Enjoy,
=> [skip ci] Code cleanup

ceph-releases/luminous/ubuntu/16.04/daemon/confd/conf.d/ceph.conf.toml.in, ceph-releases/luminous/ubuntu/16.04/daemon/confd/templates/ceph.conf.tmpl
:man_facepalming: Same as #851, but for luminous containers too. Sorry for the noise!
=> daemon: Adds support for client config subsections with confd to luminous containers

ceph-releases/luminous/ubuntu/16.04/daemon/check_zombie_mons.py
Forgot to apply the selector in check_zombie_mons.py
=> Use K8S_MON_SELECTOR variable for monitor health checks

ceph-releases/luminous/ubuntu/16.04/daemon/common_functions.sh
Dmcrypt Jewel has a lockbox partition numbered 3, where in Luminous
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1518788
=> common_functions: fix upgrade from dmcrypt jewel to luminous

ceph-releases/luminous/ubuntu/16.04/daemon/Dockerfile
It seems the backslashes before every comments are disrupting the builds.
By the way, It's kind of duplicate with the one on previous line.
=> dockerfile: fix comments

ceph-releases/luminous/ubuntu/16.04/daemon/debug.sh, ceph-releases/luminous/ubuntu/16.04/daemon/docker_exec.sh, ceph-releases/luminous/ubuntu/16.04/daemon/entrypoint.sh.in, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_disk_activate.sh
=> osd: unmount osd store after the osd stops

ceph-releases/luminous/ubuntu/16.04/daemon/disk_list.sh
We can assume the device is dmcrypt as soon as we find `TYPE=crypto_LUKS`
on `${OSD_DEVICE}`.
There is no need to try to predict what will be the name of the 'ceph data'
partition, therefore, `is_loop_dev` is no longer needed.
Let's find the `ceph data` uuid partition with `blkid` and mount it.
Fixes: #884
=> disk_list.sh: improve 'ceph data' mount partition

ceph-releases/luminous/ubuntu/16.04/daemon/README.md
Hi, please see #889 for the justification.
=> PR for #889

ceph-releases/jewel/ubuntu/14.04/daemon/variables_entrypoint.sh, ceph-releases/luminous/ubuntu/16.04/daemon/variables_entrypoint.sh
`HOSTNAME` won't be set as expected since it's already defined when the
containter starts.
We must reset that variable to the value we actually want.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1546127
=> short hostname shouldn't be only a default value

contrib/build-push-ceph-container-imgs.sh
This script will be triggered by the CI after each PR is merged.
=> [skip ci] ci: add script to build and push images

contrib/build-push-ceph-container-imgs.sh
Instead of discovering branche and commit we can simply re-use jenkins
env variables during the job execution.
=> [skip ci] ci: use jenkins variables

contrib/build-push-ceph-container-imgs.sh
Sometimes we end up running on the same slave, let's make sure it gets
purged prior to build anything.
=> [skip ci] ci: cleanup for leftover

contrib/build-push-ceph-container-imgs.sh
=> Backport of 959

contrib/build-push-ceph-container-imgs.sh
When building on a tag, we don't want to tag and push latest. We simply
want to build the release tags.
=> ci: do not push latest when building on a tag

README.md
=> README: add doc for finding image tags

contrib/build-push-ceph-container-imgs.sh
DO_NOT_PUSH_LATEST is semanticly wrong here.
To be more generic, it would be better saying that we run on tagged head.
Then we let functions deciding what they have to do when we run on a tagged head.
Reading the code with this change shows a better semantic.
This commit replace DO_NOT_PUSH_LATEST by TAGGED_HEAD which is a boolean, false by default.
This commit also move the testing of TAGGED_HEAD inside push_ceph_imgs_latest() to get a cleaner main.
That also give the opportunity to print a specific & explicit message about this skip.
=> ci: Changing semantic of DO_NOT_PUSH_LATEST

Makefile
=> [skip ci] make:fix wrong quote position.

README.md
A presentation around the work done on rethinking the whole project architecture
=> [skip ci] Presentations: Adding reworking ceph-container

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/ALL/centos/daemon-base/__ISCSI_PACKAGES__, src/daemon-base/__CEPH_BASE_PACKAGES__, src/daemon/entrypoint.sh.in, src/daemon/start_rbd_target_api.sh, src/daemon/start_rbd_target_gw.sh, src/daemon/start_tcmu_runner.sh, src/daemon/variables_entrypoint.sh
=> [skip ci] DNM: daemon: add support for iscsi scenario

maint-lib/flavors-modified-vs-master.py, maint-lib/stagelib/replace.py
Refactor some flake8 errors that slipped by.
=> maint-lib: flake8 refactors

src/daemon/entrypoint.sh.in, src/daemon/variables_entrypoint.sh
Let's call the scenario with the name of daemon, it's clearer.
=> [skip ci] iscsi: clarify scenario names

.travis.yml, CONTRIBUTING.md, Makefile, README.md, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, maint-lib/makelib.mk, maint-lib/stage.py, maint-lib/stagelib/envglobals.py, src/STAGING_ENV_VARS.md, tests/stage-test/src/daemon/src-daemon-test-file, tests/stage-test/stage-key/files-sources, tests/stage-test/stage-key/staging_output.txt, tests/stage-test/test_staging.sh, tests/tox.sh
Shorten the flavor spec to `CEPH_VERSION,BASEOS_REPO,BASEOS_TAG`
=> make: shorten flavors

contrib/build-push-ceph-container-imgs.sh
=> [skip ci] contrib: fix push latest tag

contrib/build-push-ceph-container-imgs.sh
latest-bis is needed by ceph-ansible so it can test the restart
handlers on an image ID change.
So we rebuild latest again to get a different image ID.
We extracted the test for a tagged head so that we can separate each
function's call (push_ceph_imgs_latests and build_and_push_latest_bis).
latest-bis needs to exist if latest tags were built, so basically when
we are not building a release.
=> [skip ci] contrib: build latest-bis image

ceph-releases/jewel/daemon/check_zombie_mons.py, ceph-releases/kraken/daemon/check_zombie_mons.py, examples/kubernetes/rgw_s3_client.py, maint-lib/stagelib/envglobals.py, maint-lib/stagelib/filetools.py, src/daemon/check_zombie_mons.py, tests/base/test_ceph_conf.py, tests/conftest.py
This patch is about removing the >70 flake8 errors we had which were triggered errors on the CI.
That was a bad idea as it could hide a real python error.
=> Cleaning Flake8 errors

Makefile
Since it's now possible to change the image tags to arbitrary strings,
our clean operations might just do nothing. Revise the way the
`clean.all` target works. Inspect each docker image's metadata and look
for the string "CEPH_POINT_RELEASE" anywhere in the metadata.
"CEPH_POINT_RELEASE" is a string all of our build containers should
have, and it is unlikely that another container build will use the same
string. "CEPH_VERSION", is also probably unlikely, but it is certain to
be more likely than "CEPH_POINT_RELEASE".
Drop `clean.nuke` target, as its functionality is now encompassed by
`clean.all`.
=> make: Revise clean targets

src/daemon/start_mgr.sh
The code as is wasn't working. Also, if you are looking at enabling
modules we recommend to use a different interface to enable them.
The start function only starts the daemon. To enable the modules you
could use another container.
Closes: https://github.com/ceph/ceph-container/issues/928
=> mgr: remove the modules code

.travis.yml, src/daemon/demo.sh
Sree is an S3 interface to play with S3 interface of rgw.
=> [skip ci] demo: add sree interface

src/daemon/demo.sh
This now handles the case where the container restarts. We don't need to
go through the config again since it's already there. We just start the
API service.
=> [skip ci] demo: make sree bootstrap idempotent

contrib/build-push-ceph-container-imgs.sh
So we can create the daemon.json file.
=> [skip ci] contrib: create docker user directory

.travis.yml, Makefile, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/ALL/ubuntu/daemon-base/__DOCKERFILE_INSTALL__, contrib/build-push-ceph-container-imgs.sh, src/daemon/demo.sh, tests/tox.sh
Ceph Mimic just got released.
We know build mimic ceph images.
=> mimic: add mimic release

README.md
Add a list of stable ceph-container daemon images.
Should resolve #1085
Signed-off-by: Elias Abacioglu <elias.rabi@gmail.com>
=> Add stable image list to README.md

.travis.yml, src/daemon/demo.sh
If DATA_TO_SYNC is passed with a directory (also exposed) and DATA_TO_SYNC_BUCKET is
named then the content of DATA_TO_SYNC will be uploaded into the bucket
DATA_TO_SYNC_BUCKET.
=> [skip ci] demo: import dir at running time

src/daemon/start_mon.sh
Backport of #1102 in stable-3.0
=> Backport of 1102 in stable-3.0

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/ALL/centos/daemon-base/__ISCSI_PACKAGES__
Backport of #1057 
(cherry picked from commit d7f19d15fc08673f1fc6f4a972d8519fc13701df)
=> [skip ci] iscsi: add python-rtslib repo

tests/tox.sh
Update the ceph-ansible requirements.txt picked up in ceph-container
tests accordingly with the ceph-ansible branch being tested.
=> tests: update ceph-ansible requirements.txt picked up

src/daemon/zap_device.sh
Backport of #1119 in stable-3.0
=> Backport of 1119 in stable-3.0

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/ALL/ubuntu/daemon-base/__DOCKERFILE_INSTALL__
Backport of #1079 in stable-3.0
=> Backport of 1079 in stable-3.0

tests/tox.sh
Backport of #1130 in stable-3.1
=> Backport of 1130 in stable-3.1

src/daemon/disk_list.sh
Backport of #1128 in stable-3.0
=> Backport of 1128 in stable-3.0

ceph-releases/ALL/rhel7/__DOCKERFILE_MAINTAINER__, ceph-releases/ALL/rhel7/daemon-base/__DOCKERFILE_PREINSTALL__
Backport of #1136 in stable-3.1
=> [skip ci] Backport of 1136 in stable-3.1

.travis.yml, src/daemon/demo.sh, src/daemon/start_rgw.sh, src/daemon/variables_entrypoint.sh
Backport of #1126 in stable-3.0
=> Backport of #1126 in stable-3.0

.travis.yml, src/daemon/demo.sh, src/daemon/start_rgw.sh, src/daemon/variables_entrypoint.sh
Backport of #1126 in stable-3.1
=> Backport of 1126 in stable-3.1

src/daemon/variables_entrypoint.sh
Backport of #1141 in stable-3.1
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1603202
=> Backport of 1141 in stable-3.1

src/daemon/variables_entrypoint.sh
Backport of #1141 in stable-3.0
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1603202
=> Backport of 1141 in stable-3.0

.travis.yml, src/daemon/demo.sh, src/daemon/start_rgw.sh, src/daemon/variables_entrypoint.sh
Backport of #1148 in stable-3.1
=> [skip ci] Backport of 1148 in stable-3.1

.travis.yml, src/daemon/demo.sh, src/daemon/start_rgw.sh, src/daemon/variables_entrypoint.sh
Backport of #1148 in stable-3.1
=> [skip ci] Backport of 1148 in stable-3.0

src/daemon/variables_entrypoint.sh
Backport of #1150 in stable-3.0
=> [skip ci] Backport of 1150 in stable-3.0

src/daemon/variables_entrypoint.sh
Backport of #1150 in stable-3.1
=> [skip ci] Backport of 1150 in stable-3.1

src/daemon/common_functions.sh
Backport of #1155 in stable-3.1
=> Backport of 1155 in stable-3.1

src/daemon/common_functions.sh
Backport of #1155 in stable-3.0
=> Backport of 1155 in stable-3.0

examples/kubernetes-coreos/rbd
ceph/base -> ceph/daemon-base
Resolves #
Checklist:
=> [skip ci] examples: update docker image name

ceph-releases/jewel/daemon/config.kv.etcd.sh, ceph-releases/kraken/daemon/config.kv.etcd.sh, src/daemon/config.kv.etcd.sh
I'm getting these errors on mon containers, which should be fixed with this patch:
Error:  100: Key not found (/ceph-config/ceph/lock) [108]
Checklist:
=> Do not die if lock does not exist

contrib/build-ceph-base.sh, contrib/ceph-build-config.sh
Various fixes to a better integration
=> Fix Stuff :D

Makefile, maint-lib/makelib.mk
Resolves #1191 without causing an infinite loop.
Checklist:
=> Make: fix 1191 parallel build fails (try #2)

src/daemon/__DAEMON_PACKAGES__, src/daemon/docker_exec.sh, src/daemon/entrypoint.sh.in, src/daemon/osd_scenarios/osd_disk_activate.sh, src/daemon/osd_scenarios/osd_volume_activate.sh
Backporting #1179 to stable-3.1
=> Backporting #1179 to stable-3.1

contrib/ceph-build-config.sh, contrib/make-ceph-base-manifests.sh
`docker tag ...` does not work to apply tags to manifest images. Instead
add tags with the manifest images. This requires changing the manifest
loop from a look-behind to a look-ahead.
Because some manifest images have already been pushed, also add an
option to force recreation of manifest images.
Set `FORCE_MANIFEST_CREATION` to rebuild the latest manifest images.
@leseb In order to fix the manifests which are already created, when you pull this, can you do a manual run with the environment variable `FORCE_MANIFEST_CREATION=true` so that those get overwritten with the appropriate manifests?
Checklist:
=>  contrib: add tags with manifests [skip ci]

ceph-releases/ALL/rhel7/daemon/content_sets.yml
Signed-off-by: Yaakov Selkowitz <yselkowi@redhat.com>
Allow building rhel7 container on ppc64le.
Checklist:
- [ n/a ] Documentation has been updated, if necessary.
- [ n/a ] Pending release notes updated with breaking and/or notable changes, if necessary.
=> rhel7: add ppc64le content sets

ceph-releases/ALL/rhel7/daemon/content_sets.yml
Signed-off-by: Yaakov Selkowitz <yselkowi@redhat.com>
Cherry pick #1235 to stable-3.2 branch.
Checklist:
- [ n/a ] Documentation has been updated, if necessary.
- [ n/a ] Pending release notes updated with breaking and/or notable changes, if necessary.
=> [stable-3.2] rhel7: add ppc64le content sets

src/daemon/common_functions.sh
=> Backport of 1256

.travis.yml
This will help cn to come back to life at each restart even if the
container IP changes.
=> travis: run demo on localhost

contrib/build-push-ceph-container-imgs.sh
ARM builds are pretty much slower & weaker than x86 ones.
There is situations where we need to disable the ARM builds not to block the x86 ones.
When this situation occurs, the BUILD_ARM variable can be emptied.
Once the ARM build are stable again, this variable can be set to anything so it is reactivated.
Note this patch is disabling the ARM builds are we are currently facing an issue with them.
Resolves #
Checklist:
=> contrib/build-push-ceph-container-imgs.sh: Disabling ARM builds

contrib/build-push-ceph-container-imgs.sh, src/daemon/osd_scenarios/osd_disk_activate.sh
=> Unmount OSD path properly

src/daemon/osd_scenarios/osd_disk_activate.sh, src/daemon/osd_scenarios/osd_volume_activate.sh
=> 1264 bkp stable 3.2

src/daemon/docker_exec.sh
=> Minor improvements of docker_exec

examples/helm/ceph/templates/mon/service.yaml, examples/kubernetes-coreos/startup.sh, examples/kubernetes/gce/README.md, examples/kubernetes/gke/README.md, tests/README.md
Signed-off-by: Christian Berendt <berendt@betacloud-solutions.de>
=> Replace ceph-docker with ceph-container where possible

src/daemon/common_functions.sh, src/daemon/start_mon.sh
This commit is about introducing a dynamic tuning of ceph's.
The concept is to collect first the amount of available memory reported by the system.
If the cgroup report a reasonable value, this value is used, unless (if cgroups reports 8Exabytes), the value is taken from the system.
This value is then reduced from a couple of MB to let some room for the other process to run.
If this value exceed 4GB, the amount of memory is caped to avoid giving all possible memory to ceph.
Then, the 3 ceph metrics are computed :
+----------------------+ -> max system memory
|                      |
|                      |
|----------------------| -> available memory
|                      |
|----------------------| -> available memory - 50MB
| osd_memory_target    | -> memory used by ceph at most …
=> daemon: Tuning ceph's memory when container starts

README.md
update the README badge link to docker hub for convenience
Signed-off-by: Li Hongen <gradle@qq.com>
=> README: update the badge link to docker hub

contrib/ceph-build-config.sh
Signed-off-by: Saravanakumar Arumugam <sarumuga@redhat.com>
=> Remove ubuntu reference as it is no longer built

README.md
Signed-off-by: Saravanakumar Arumugam <sarumuga@redhat.com>
=> To build the container, pass build as an argument to make.

contrib/build-ceph-base.sh
=> contrib: add FORCE_BUILD option to ceph/ceph build

contrib/compose-rhcs.sh
For the master branch, we just care about Nautilus and RHEL 8.
=> contrib: compose-rhcs for nautilus + RHEL 8

src/daemon/check_zombie_mons.py
Signed-off-by: nesc58 <14092074+nesc58@users.noreply.github.com>
(cherry picked from commit be248cc803720e3f1ac98580d1216265de85fa3e)
=> Fix monmap_command for MON_HEALTH daemon

src/daemon/start_mon.sh
When bootstrapping an initial cluster, we don't need to add the mon
to the monmap via 'ceph mon add' command.
But when we want to scale up the monitors then we need it.
Currently the new mon added will be out of quorum because the addr
in the ceph config and in the monmap won't match.
start_mon(): ceph --cluster ceph mon add xxx 192.168.100.5:3300
mon.xxx at v2:192.168.100.5:3300/0 already exists
Even if the ceph conf uses v2+v1 then the new mon will have only v2
address configured in the monmap creating a conflict.
0 mon.xxx@0(probing) e3  monmap addrs for rank 4 changed, i am
[v2:192.168.100.5:3300/0,v1:192.168.100.5:6789/0], monmap is
v2:192.168.100.5:3300/0, respawning
0 mon.xxx@0(probing) e3 respawn
Removing the port value on the 'ceph mon add' command allows to add
a monitor with …
=> daemon/start_mon.sh: add mon without port value (bp #1410)

contrib/build-push-ceph-container-imgs.sh
There's multiple issues with the build-push-ceph-container-imgs.sh
script:
- we execute the script from master but checkout the code from stable
branch when building a new tag.
- the ceph_releases list is static and should not be the same if we're
building on tag (TAGGED_HEAD=true) or not.
* stable-3.2: luminous and mimic
* stable-4.0: nautilus
Currently on stable-3.2 and stable-4.0 branches we always build
luminous, mimic and nautilus for arm64 architecture (because hardcoded
in the build-push-ceph-container-imgs-arm64.sh script) while we build
releases based on the FLAVORS value from the Makefile for x86_64.
This commit allows to override the ceph releases list when we're
building a new tag.
Because the new list won't have master then we need to change the
condition in the …
=> contrib: override releases list on stable branch

.travis.yml, src/daemon/demo.sh, travis-builds/validate_demo_cluster.sh
Enables build and demo validation on stable branch.
=> travis: Add basic CI on stable-3.2

src/daemon/zap_device.sh
if the device passed is a partition, we never call
`zap_dmcrypt_device()`, it means dmcrypt partitions aren't wipped properly.
This commit moves the call to `zap_dmcrypt_device()` so it applies for
root devices and partitions.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1572933
Backport: #1425
(cherry picked from commit f285b23b75f749edd2bab9a8796fe9b90d5e80b6)
=> zap_device: zap dmcrypt partitions as well (bp #1425)

src/daemon/zap_device.sh
if the device passed is a partition, we never call
`zap_dmcrypt_device()`, it means dmcrypt partitions aren't wipped properly.
This commit moves the call to `zap_dmcrypt_device()` so it applies for
root devices and partitions.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1572933
=> zap_device: zap dmcrypt partitions as well

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Let's also pin master to ganesha 2.8 since ganesha master is still
broken.
=> ceph: unblock master images

src/daemon/osd_scenarios/osd_volume_activate.sh
After upgrading to nautilus, the OSD deployed by ceph-disk needs to be
manage by ceph-volume with the simple subcommand.
This was part of the osd_ceph_disk_activate entrypoint but there's no
need to have a separate entrypoint because at the end we are using the
same command : ceph-volume.
=> osd_volume_activate: manage ceph-disk based OSD

src/daemon/osd_scenarios/osd_volume_activate.sh
After upgrading to nautilus, the OSD deployed by ceph-disk needs to be
manage by ceph-volume with the simple subcommand.
This was part of the osd_ceph_disk_activate entrypoint but there's no
need to have a separate entrypoint because at the end we are using the
same command : ceph-volume.
Backport: #1446
(cherry picked from commit d467a30a505e8a841344644d5ed59010e2c10b10)
=> osd_volume_activate: manage ceph-disk based OSD (bp #1446)

src/daemon/osd_scenarios/osd_disks.sh
[file] osd_disks: edit the src/daemon/osd_scenarios/osd_disks.sh file
Signed-off-by: Jean Wasilewski <henyxia@revs0.com>
=> fix: assign properly OSD_DISKS variable

src/daemon-base/__CEPH_MGR_PACKAGES__
=> daemon-base: add ceph-mgr-ssh package

src/daemon/disk_list.sh
[file] disk_list.sh: delete the temporary folder created as a mount point for
Ceph devices.
Resolves #1473
Checklist:
=> fix: delete temporary mount point

contrib/build-push-ceph-container-imgs.sh
also rename short_repo_tag to branch_repo_tag
Signed-off-by: Dan Mick <dan.mick@redhat.com>
=> contrib/build-push-ceph-container-imgs.sh: add sha1 tag

src/daemon/demo.sh, travis-builds/validate_demo_cluster.sh
The nfs ganesha service requires dbus to be running. Also the rpc.idmapd
service isn't required in this scenario.
=> demo: fix nfs ganesha startup

contrib/build-push-ceph-container-imgs.sh
=> contrib/build-push-ceph-container-imgs.sh: workaround podman-docker

contrib/build-push-ceph-container-imgs.sh
This is for CentOS 8 distribution.
=> contrib: add podman support

contrib/build-push-ceph-container-imgs.sh
The previous commit introduced a typo in the if statement.
=> contrib: fix if/else statement

src/daemon/osd_scenarios/osd_volume_activate.sh
When managing legacy ceph-disk based OSD with ceph-volume then we need
to open the encrypted partitions before running the ceph-volume simple
scan command otherwise the scan will fail.
This situation happens after a reboot because all encrypted partitions
are closed.
```console
$ ceph-volume simple scan /dev/sdb1 --force
(...)
--> broken symlink found /tmp/tmpept0ox2j/block -> /dev/mapper/457d7196-4015-40fe-aa83-a160477450f7
```
```console
$ ceph-volume.log
(...)
[ceph_volume.util.system][INFO  ] /dev/sdb1 was not found as mounted
[ceph_volume.util.encryption][WARNING] failed to detect device mapper information
[ceph_volume.util.encryption][WARNING] failed to detect device mapper information
[ceph_volume.devices.simple.scan][WARNING] broken symlink found /tmp/tmpept0ox2j/block -> …
```
=> osd_volume_activate: open encrypted legacy parts

src/daemon/osd_scenarios/osd_disk_activate.sh
=> Fix activating legacy osd-disk partitioned nvme device

ceph-releases/ALL/centos/8/daemon-base/__GANESHA_PACKAGES__
needed in `ceph/daemon-base:latest-master-devel` for nfs-ganesha
deployment by `bin/cephadm` (https://github.com/ceph/ceph/pull/33064)
Signed-off-by: Michael Fritch <mfritch@suse.com>
Checklist:
=> daemon-base: add nfs-ganesha-rados-urls

src/daemon-base/Makefile
https://tracker.ceph.com/issues/44250
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
Resolves #
Checklist:
=> daemon-base/Makefile: chown $(USER) $(DAEMON_BASE_IMAGE)

contrib/build-push-ceph-container-imgs.sh
Fixes: https://tracker.ceph.com/issues/44242
=> contrib: Install patched fuse-overlayfs package

tests/setup.yml
- update docker insecure registry
- remove atomic and debian tasks
- use ini_file for podman configuration
=> tests/setup.yml: update the playbook

ceph-releases/ALL/ubi8/daemon-base/__DOCKERFILE_PREINSTALL__, ceph-releases/ALL/ubi8/daemon/content_sets.yml
RHCS 5 will be based on Ceph Octopus release.
=> ubi8: update for RHCS 5

tests/tox.sh
This is to reflect the ceph-ansible configuration.
=> tests/tox.sh: increase pytest thread

src/daemon/README.md
Add missing udev bind mount.
Closes: #1304
=> daemon/README: add udev bind mount

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Update nfs-ganesha from 3.2 to 3.3 for octopus.
=> centos: update nfs-ganesha to 3.3

tox.ini
To reflect the ceph-ansible change.
=> tox: update to ansible 2.9

contrib/build-push-ceph-container-imgs.sh
=> CI builds: push -aarch64 versions of short tags; improve "kubic" repo handling

src/daemon/README.md
I fixed a small typo error in docs.
Resolves #
Checklist:
=> fix: small error

tests/tox.sh
In order to avoid false positive in the CI that I've been unable to
reproduce elsewhere than in the CI.
(cherry picked from commit 8d0b3b44e0a2d5f7f54b08c09c61b25667b7367c)
=> tests: increase reruns and reruns delay in pytest

tests/setup.yml, tox.ini
The ceph-ansible master branch updated the ansible version to 2.10
=> tox: update ansible to 2.10

src/daemon/start_mon.sh, tests/setup.yml
This converts the ansible facts calls to ansible_facts['x']
(cherry picked from commit 588f29f54912d476fc3e4bef5ca46eb6c423cb51)
=> tests/ansible: use ansible_facts

contrib/build-push-ceph-container-imgs.sh
We don't really need to use ceph nano for listing the container tags
from docker hub registry.
We can do it in bash and we already do that in other scripts.
Also ceph nano is not optimized and something the command returns
nothing without failing.
=> contrib: remove ceph-nano dependency

src/daemon/README.md
This updates the ceph docs URLs.
Signed-off-by: Robbert <RobbertH@users.noreply.github.com>
=> [skip ci] README.md: update ceph doc URLs

.github/workflows/rhcs.yml, travis-builds/validate_demo_cluster.sh
This adds a github workflow for testing RHCS compose.
=> [skip ci] workflow: add rhcs compose task

contrib/ceph-build-config.sh
- registry namespace and repositories remain the same than docker.io [1][2][3]
- define the registry name explicitly for login, pull and push operations
- update registry API endpoint calls for quay registry [4]
- base container images (CentOS) are pulled from quay.io [5]
- existing ceph container images (amd64 and arm64) are pulled from quay.io
- new ceph container images are pushed to quay.io/ceph/ceph-{amd64,arm64}
and manifests to quay.io/ceph/ceph
- update registry credentials variables to be more generic
[1] https://quay.io/repository/ceph/ceph
[2] https://quay.io/repository/ceph/ceph-amd64
[3] https://quay.io/repository/ceph/ceph-arm64
[4] https://docs.quay.io/api/
[5] https://quay.io/repository/centos/centos
Closes: #1834
=> contrib: publish ceph/ceph to quay.io registry

.github/workflows/container.yml, src/daemon/demo.sh, travis-builds/validate_demo_cluster.sh
- remove legacy code
- remove custom cluster name
- add crash support
- update mgr caps
- update mds caps
- remove rbd pool
=> [skip ci] demo: cleanup and add crash support

.github/workflows/container.yml, src/daemon/demo.sh, travis-builds/validate_demo_cluster.sh
- remove legacy code
- remove custom cluster name
- add crash support
- update mgr caps
- update mds caps
- remove rbd pool
Backport: #1921
=> [skip ci] demo: cleanup and add crash support (bp #1921)

contrib/build-push-ceph-container-imgs.sh
=> contrib: Missing slash

ceph-releases/ALL/centos/__DOCKERFILE_MAINTAINER__, ceph-releases/ALL/rhel7/__DOCKERFILE_MAINTAINER__, ceph-releases/ALL/ubi8/__DOCKERFILE_MAINTAINER__, src/__DOCKERFILE_MAINTAINER__
This updates the maintainer label.
=> maintainer: update __DOCKERFILE_MAINTAINER__

Makefile, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, contrib/build-push-ceph-container-imgs.sh, contrib/ceph-build-config.sh, maint-lib/ceph_version.sh
quincy v17.1.0 release is available.
Let's build quincy images.
=> add quincy release

contrib/ceph-build-config.sh
The quay.io API endpoint `repository/<repo>/<ns>/tag/<tag>/images` doesn't
exist anymore.
Instead we can use the `repository/<repo>/<ns>/tag/` endpoint with the
`specificTag` parameter.
As a consequence we now need to test the tags array length from the response
because we can't only rely on the curl return code.
This also change the workflow when the curl command fails for any reason. The
current workflow was to continue the execution while the script stops now.
=> [skip ci] contrib: update API endpoint for existing tags

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
This reverts commit f5891de55813759d23c9bc70ca8bda0802eab1c4.
=> Revert "build: fix centos latest"

contrib/rhcs.md
Document how to build the RH Ceph Storage container image locally.
=> document rhcs scripts

ceph-releases/ALL/ubi9/daemon-base/__DOCKERFILE_PREINSTALL__, contrib/compose-rhcs.sh, contrib/rhcs.md
Signed-off-by: Justin Caratzas <jcaratza@redhat.com>
Resolves #
Checklist:
=> ubi9: change text to reflect rhcs 5 -> 6

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, travis-builds/validate_demo_cluster.sh
This reverts commit 469dd66af9727f5dcfaf72606b03fd12622ce7a3.
https://github.com/ceph/ceph-container/pull/2058#issuecomment-1232941712
Resolves #
Checklist:
=> Revert "build: Prevent `error: db5 error` errors"

ceph-releases/ALL/debian/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/ALL/debian/daemon-base/__DOCKERFILE_PREINSTALL__
Update all package on base images before building image to install latest available package. Updating and installing latest package will help to reduce Vulnerability.
Resolves #2073
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>
Checklist:
=> feat : update all packages of base debian image

ceph-releases/ALL/ubi8-ibm/__DOCKERFILE_MAINTAINER__, ceph-releases/ALL/ubi9-ibm/__DOCKERFILE_MAINTAINER__
This changes the maintainer's email address (@redhat.com->@ibm.com)
=> ubi-ibm: change maintainer email address

ceph-releases/ALL/ubi9-ibm/__DOCKERFILE_BRANDING__, ceph-releases/ALL/ubi9-ibm/daemon-base/__DOCKERFILE_LABELS__, ceph-releases/ALL/ubi9-ibm/daemon-base/__ETC_REDHAT_STORAGE_RELEASE__, ceph-releases/ALL/ubi9-redhat/__DOCKERFILE_BRANDING__, ceph-releases/ALL/ubi9-redhat/__DOCKERFILE_CLEAN_COMMON__, ceph-releases/ALL/ubi9-redhat/__DOCKERFILE_MAINTAINER__, ceph-releases/ALL/ubi9-redhat/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/ALL/ubi9-redhat/daemon-base/__DOCKERFILE_LABELS__, ceph-releases/ALL/ubi9-redhat/daemon-base/__DOCKERFILE_POSTINSTALL_CLEANUP__, ceph-releases/ALL/ubi9-redhat/daemon-base/__DOCKERFILE_PREINSTALL__, ceph-releases/ALL/ubi9-redhat/daemon-base/__DOCKERFILE_VERIFY_PACKAGES__, ceph-releases/ALL/ubi9-redhat/daemon-base/__ETC_REDHAT_STORAGE_RELEASE__, ceph-releases/ALL/ubi9-redhat/daemon-base/__RADOSGW_PACKAGES__, ceph-releases/ALL/ubi9-redhat/daemon-base/container.yaml, ceph-releases/ALL/ubi9-redhat/daemon-base/content_sets.yml, ceph-releases/ALL/ubi9-redhat/daemon/__DOCKERFILE_VERIFY_PACKAGES__, src/daemon-base/__UTIL_PACKAGES__
This is required to support the multiple frontend directories (redhat/ibm)
=> add ubi9-redhat release

contrib/build-push-ceph-container-imgs.sh
The local image tag was modified in
https://github.com/ceph/ceph-container/commit/15054d97b0fcf406542d9c1ea6cc6897f45ad732, so we need to modify the path in this script
as well.
Resolves https://tracker.ceph.com/issues/62432
=> contrib: add repo to the local image tag

ceph-releases/reef/centos/__GANESHA_REPO__
Followup to https://github.com/ceph/ceph-container/commit/546d97faab66e6a0eee95447e7eb43c762dc1412
Resolves https://tracker.ceph.com/issues/62434
Checklist:
=> ceph-releases/reef/centos: fix reef ganesha repo bash syntax

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Fixes the regression introduced in
https://github.com/ceph/ceph-container/commit/546d97faab66e6a0eee95447e7eb43c762dc1412.
Checklist:
=> ceph-releases/ALL/centos/daemon-base: fix filepath for nfs-ganesha repo

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/main/centos-arm64/__GANESHA_PACKAGES__, ceph-releases/quincy/centos-arm64/__GANESHA_PACKAGES__, ceph-releases/reef/centos-arm64/__GANESHA_PACKAGES__
=> add ganesha packages to main, quincy, reef builds

ceph-releases/reef/ubi9-ibm/__DOCKERFILE_BRANDING__
We need to re-build and publish the Beta
This reverts commit 3635e55bead1ab7eae48589b65e751b96b23e3fc.
Resolves #
Checklist:
=> ubi9-ibm: use beta container URLs for Beta respin

ceph-releases/reef/ubi9-ibm/__DOCKERFILE_BRANDING__
This reverts commit 33cfcdb0f078d9924ae9e72220dee39997a653ae.
We've re-published the Beta, so we can remove these edits again
Resolves #
Checklist:
=> Revert "Revert "Revert "ubi9-ibm: use beta container URLs"""

src/daemon-base/__CEPH_BASE_PACKAGES__, src/daemon-base/__CEPH_NODE_PROXY_PACKAGE__
This adds the new RPM ceph-node-proxy
=> Add new package ceph-node-proxy in daemon-base image

ceph-releases/reef/ubi9-ibm/__DOCKERFILE_BRANDING__
for IBM 7.1 beta
Resolves #
Checklist:
=> ubi9-ibm: use beta container registry

contrib/build-push-ceph-container-imgs.sh
I sincerely hope this is nearly the last thing I need to do to this repo
=> Build centos9 for CI containers, add -centos9 to tag to avoid collision

.github/workflows/container.yml, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
=> nfs: use nfs-ganesha 5

Makefile
This changes the default images built (el8 -> el9)
=> Makefile: update FLAVORS, ALL_BUILDABLE_FLAVORS

contrib/build-push-ceph-container-imgs.sh
Due to the EOL of Stream8, let's switch to Stream9 by default.
=> update _centos_release() function

contrib/build-push-ceph-container-imgs.sh
This image is no longer built, any try to push it will fail.
=> do not push daemon image

README.md
=> chore(doc): fix list style in readme
