ceph/ceph-container

contrib/commit-rhcs.sh
For the master branch, we just care about Nautilus and RHEL 8.
In addition of d2f524e.
=> contrib/commit-rhcs.sh: Nautilus on RHEL 8

ceph-releases/ALL/rhel8/daemon/content_sets.yml
RHEL 8 is released, and it uses these final content-set names.
=> rhel8: use production content-sets

src/daemon/common_functions.sh
Since fed5b23 the block.db and block.wal partitions aren't created
by default with bluestore when using a single device.
Because there's not db and wal partitions then we don't have to do
dmcrypt operation (open_encrypted_part and close_encrypted_part).
=> ceph-disk: fix dmcrypt with bluestore db/wal

src/daemon/check_zombie_mons.py
Hi, for me the MON_HEALTH daemon  is not working.
The error:
```2019-05-14 16:05:44  /opt/ceph-container/bin/entrypoint.sh: Checking for zombie mons
got monmap epoch 9
/bin/sh:     monmaptool: command not found
Traceback (most recent call last):
File "/opt/ceph-container/bin/check_zombie_mons.py", line 39, in <module>
current_mons = extract_mons_from_monmap()
File "/opt/ceph-container/bin/check_zombie_mons.py", line 25, in extract_mons_from_monmap
monmap = subprocess.check_output(monmap_command, shell=True)
File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'ceph --cluster=${CLUSTER} mon getmap > /tmp/monmap && '    'monmaptool -f /tmp/monmap --print' returned non-zero exit …
```
=> Fix monmap_command for MON_HEALTH daemon

maint-lib/makelib.mk
Description of your changes: Allows to build images from Mac OS
Checklist:
- Documentation has been updated, if necessary: not needed
- Pending release notes updated with breaking and/or notable changes, if necessary: not needed
=> maint-lib/makelib.mk: long-form not supported on mac os

ceph-releases/ALL/centos-arm64/daemon-base/__RADOSGW_PACKAGES__
58d2eea161691f1a1b444c464f2ad2ca790a4c5e missed to fix this symlink.
This commit fixes it.
=> fix broken symlink for centos-arm64 __RADOSGW_PACKAGES__ override

Makefile, contrib/build-push-ceph-container-imgs-arm64.sh, contrib/build-push-ceph-container-imgs.sh
12ab4d2 adds arm64 to ceph-build-config script but there's some
missing pieces in order to build arm64 nautilus image.
This also adds nautilus to the registry manifest creation because
we now have multiple arch for that release too (the same way than
luminous and mimic)
=> contrib/build-push-ceph: Add arm64 for nautilus

Makefile
The openSUSE 42.3 luminous build isn't working anymore preventing to
build the other container images.
This is temporary until the issue is resolved.
See: https://github.com/ceph/ceph-container/issues/1387
=> Makefile: disable openSUSE 42.3 luminous build

src/daemon/populate_kv.sh
The client_host directory command creation is called for every keys
present in the ceph configuration.
We only need to call the mkdir command once outsite the kv function.
Resolves: #1197
=> populate_kv.sh: create client_host directory once

ceph-releases/ALL/centos/daemon-base/__ISCSI_PACKAGES__, ceph-releases/luminous/centos/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/luminous/centos/daemon-base/__ISCSI_PACKAGES__, ceph-releases/mimic/centos/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/mimic/centos/daemon-base/__ISCSI_PACKAGES__
With nautilus we have to use ceph-iscsi 3.x which uses a combined
ceph-iscsi repository and package (ceph-iscsi).
=> centos: Update ceph-iscsi repo/pkgs for nautilus

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/luminous/centos/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/mimic/centos/daemon-base/__DOCKERFILE_INSTALL__
We need to use nfs-ganesha 2.8 release for ceph nautilus release (and
higher).
Because there's no rpm-V2.8-stable repository then we configure the
repository with shaman. This was already enabled for master.
Luminous and Mimic are still using stable 2.7.
=> daemon-base: Use nfs-ganesha 2.8 for nautilus

src/daemon/start_rbd_target_api.sh, src/daemon/start_rbd_target_gw.sh
With ceph-iscsi 3.x release, the log directory for rbd target api/gw
are required when the process starts.
Ideally this needs to be done via a bind mount on the container
engine side to avoid logging in the container.
=> daemon: create log directories for rbd target

src/daemon/config.static.sh, src/daemon/variables_entrypoint.sh
sosreport does not export logs from journald, so the idea here is to
have an alternative to retrieve logs in a containerized context.
Related ceph-ansible PR: ceph/ceph-ansible#4166
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1710548
=> variables_entrypoint.sh: improve logging

src/daemon/start_mon.sh
When bootstrapping an initial cluster, we don't need to add the mon
to the monmap via 'ceph mon add' command.
But when we want to scale up the monitors then we need it.
Currently the new mon added will be out of quorum because the addr
in the ceph config and in the monmap won't match.
start_mon(): ceph --cluster ceph mon add xxx 192.168.100.5:3300
mon.xxx at v2:192.168.100.5:3300/0 already exists
Even if the ceph conf uses v2+v1 then the new mon will have only v2
address configured in the monmap creating a conflict.
0 mon.xxx@0(probing) e3  monmap addrs for rank 4 changed, i am
[v2:192.168.100.5:3300/0,v1:192.168.100.5:6789/0], monmap is
v2:192.168.100.5:3300/0, respawning
0 mon.xxx@0(probing) e3 respawn
Removing the port value on the 'ceph mon add' command allows to add
a monitor with …
=> daemon/start_mon.sh: add mon without port value

Makefile
The openSUSE 42.3 luminous build isn't working anymore preventing to
build the other container images.
This is temporary until the issue is resolved.
See: https://github.com/ceph/ceph-container/issues/1387
(cherry picked from commit a4d4a0d523a54d0525049806b572ea57153723ea)
=> Makefile: disable openSUSE 42.3 luminous build (bp #1390)

Makefile, README.md, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, contrib/build-push-ceph-container-imgs.sh, maint-lib/makelib.mk, maint-lib/stage.py, maint-lib/stagelib/envglobals.py, src/STAGING_ENV_VARS.md, src/daemon-base/Dockerfile
We currently use the ceph packages for stable releases from [1] except
for master.
But in same case, we might want to test features/bugs merged into ceph
upstream but unreleased.
The CEPH_DEVEL flag allows to switch the ceph packages content to
shaman/chacra repositories when enabled.
make CEPH_DEVEL=true FLAVORS="nautilus,centos,7" build
The default value remains false for backward compatibility.
The build-push-ceph-container-imgs.sh script is also updated to be able
to build all ceph container images with that flag.
[1] http://download.ceph.com/
=> Add CEPH_DEVEL flag for using ceph devel packages

contrib/build-push-ceph-container-imgs.sh
The ceph nano (cn) release was pretty old (1.8.0) so updating it to the
latest one.
Also adding the cn release as a variable.
=> contrib: Update ceph nano to v2.3.1

Makefile
The stable-3.2 branch should only build luminous and mimic releases.
=> Makefile: Update flavors for stable-3.2

Makefile
The stable-4.0 branch should only build nautilus release.
=> Makefile: Update flavors for stable-4.0

ceph-releases/ALL/centos/__DOCKERFILE_MAINTAINER__, ceph-releases/ALL/rhel7/__DOCKERFILE_MAINTAINER__, ceph-releases/ALL/ubi8/__DOCKERFILE_MAINTAINER__, src/__DOCKERFILE_MAINTAINER__
Since the maintainer for the base image and all rhel based ceph-container
images has changed, let's update this label.
=> Dockerfile: update maintainer name

ceph-releases/ALL/centos/__DOCKERFILE_MAINTAINER__, ceph-releases/ALL/rhel7/__DOCKERFILE_MAINTAINER__, ceph-releases/ALL/ubi8/__DOCKERFILE_MAINTAINER__, src/__DOCKERFILE_MAINTAINER__
Since the maintainer for the base image and all rhel based ceph-container
images has changed, let's update this label.
Backport: #1426
(cherry picked from commit 64b1c5f554895053deeb368eba827ae4cb135512)
=> Dockerfile: update maintainer name (bp #1426)

.travis.yml, src/daemon/common_functions.sh
A NBSP has been introduced in ce6b4f0 causing the function
get_dmcrypt_bluestore_uuid to fail.
bin/common_functions.sh: line 376: $'[\302\240-n': command not found
=> daemon/common_functions.sh: remove NBSP

.travis.yml
A NBSP has been introduced in ce6b4f0 causing the function
get_dmcrypt_bluestore_uuid to fail.
bin/common_functions.sh: line 376: $'[\302\240-n': command not found
Backport: #1431
(cherry picked from commit ba4e71d7e1a1b68d0db8c8d35ecab78d30e9fe5c)
=> daemon/common_functions.sh: remove NBSP (bp #1431)

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
On Nautilus release, let's use the stable 2.8 packages for Ganesha.
Resolves #
Checklist:
=> nautilus: pin ganesha version to 2.8

ceph-releases/luminous/daemon/entrypoint.sh.in, ceph-releases/luminous/daemon/osd_scenarios/osd_disk_activate.sh, ceph-releases/luminous/daemon/start_osd.sh, ceph-releases/luminous/daemon/variables_entrypoint.sh, ceph-releases/mimic/daemon/entrypoint.sh.in, ceph-releases/mimic/daemon/osd_scenarios/osd_disk_activate.sh, ceph-releases/mimic/daemon/start_osd.sh, ceph-releases/mimic/daemon/variables_entrypoint.sh, src/daemon/common_functions.sh
In some case, we don't want to activate and start the OSD process in
the same entrypoint.
In order to allocate an OSD id on prepared OSD, we need to activate it
without start it.
That way, we're able to get the OSD id for systemd unit script.
In order to get the OSD ids with ceph-disk list command, we need first
to map the dmcrypt data partitions (mount the lockbox partition and
then open the encrypted partition).
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1670734
=> Add two entrypoints for ceph-disk OSD ids

src/daemon/common_functions.sh, src/daemon/entrypoint.sh.in, src/daemon/osd_scenarios/osd_disk_activate.sh, src/daemon/start_osd.sh, src/daemon/variables_entrypoint.sh
In some case, we don't want to activate and start the OSD process in
the same entrypoint.
In order to allocate an OSD id on prepared OSD, we need to activate it
without start it.
That way, we're able to get the OSD id for systemd unit script.
In order to get the OSD ids with ceph-disk list command, we need first
to map the dmcrypt data partitions (mount the lockbox partition and
then open the encrypted partition).
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1670734
Backport: #1434 
=> Add two entrypoints for ceph-disk OSD ids (bp #1434)

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
On Nautilus release, let's use the stable 2.8 packages for Ganesha.
Backport: #1435 
(cherry picked from commit 5938be9f2df87b3acdca2c94712a58d5b7527a6e)
=> nautilus: pin ganesha version to 2.8 (bp #1435)

src/daemon/config.kv.etcd.sh
8dfe9da removed the set-uid option in config.static file but not in the
one for etcd configuration.
=> config.kv.etcd: Remove set-uid flag for nautilus+

src/daemon/config.kv.etcd.sh
8dfe9da removed the set-uid option in config.static file but not in the
one for etcd configuration.
Backport: #1440
(cherry picked from commit 8c292f087031e268b8d13815c4836a60a7362c9c)
=> config.kv.etcd: Remove set-uid flag for nautilus+ (bp #1440)

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
This reverts commit a61f2e2d7345f3f3d7b29d478adeebfb07cd8a3e.
Because nfs-ganesha@master (2.9-dev) build has been fixed by [1] then
we can reuse that version on container image build for master/octopus.
[1] https://github.com/ceph/ceph-build/pull/1346
=> Revert "ceph: unblock master images"

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_POSTINSTALL_CLEANUP__
Repos on chacra are quite ephemeral, they last for 2 weeks only. If
someone is using an image that is 3 weeks old, the repos will be gone
and they won't be able to install any packages.
So disabling these repos is easy and less confusing for users.
They can always be re-enabled with:
yum-config-manager --enable ceph-iscsi ceph-iscsi-source ceph-iscsi-noarch tcmu-runner tcmu-runner-noarch tcmu-runner-source python-rtslib-source python-rtslib-noarch python-rtslib
Resolves https://github.com/rook/rook/issues/3662
Checklist:
=> cleanup: disable repos pointing to chacra

contrib/build-push-ceph-container-imgs-arm64.sh, contrib/build-push-ceph-container-imgs.sh
This branch modifies contrib/build-push-ceph-container-imgs.sh to allow use from a Ceph build to push a centos7 daemon-base container to a repo of choice.  There are also some cleanups and refactors for clarity, which I've tried to isolate in separate commits.
I expect this not to change the behavior of this script in other contexts.
=> Add ability to execute from Ceph build and build containers for CI/testing

src/__DOCKERFILE_POSTINSTALL_TWEAKS__
Because we're using lvm commands from the container but udev isn't
running then we also need to disable obtain_device_list_from_udev.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1676612
=> tweaks: disable obtain_device_list_from_udev lvm

src/__DOCKERFILE_POSTINSTALL_TWEAKS__
Because we're using lvm commands from the container but udev isn't
running then we also need to disable obtain_device_list_from_udev.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1676612
Backport: #1466
(cherry picked from commit 75b23017cb673e419fa2ee3f9dcb0bb2a71b456d)
=> tweaks: disable obtain_device_list_from_udev lvm (bp #1466)

contrib/build-push-ceph-container-imgs.sh
d4eedeb introduced a regression by omitting a variable renaming.
This breaks the current stable (tagged) container image build.
=> contrib: fix BRANCH variable name

src/daemon/docker_exec.sh, src/daemon/osd_scenarios/osd_volume_activate.sh
A couple of patches in order to fix the teardown that is never executed when OSDs are stopped.
2 majors issues noticed:
- mount points are never cleaned
- dmcrypt devices aren't closed
=> docker_exec/osd_volume_activate: fix teardown

src/daemon/osd_scenarios/osd_volume_activate.sh
90511a4e0231d42d98171ac456e714406605de15 introduced a bug in
osd_volume_lvm function.
OSDs couldn't start because `$CEPH_VOLUME_LIST_JSON` is seen as an empty
variable when consumed in this function.
Since there's no need to have a separate function for detecting the
volume type, let's refact this part of the code so we can fix this
issue.
=> osd_volume_activate: fix osd_volume_lvm function

src/daemon/osd_scenarios/osd_volume_activate.sh
Loop devices are like nvme or cciss devices because the partitions are
referenced with an extra 'p' before the partition number.
=> osd_volume_activate: handle loop device

src/daemon/osd_scenarios/osd_disk_activate.sh
When using OSD_DEVICE variable with /dev/disk/by-[id|path] then the
partition name is different for the ceph data partition. There's an
additional '-part' prefix before the partition number.
Instead of managing this prefix and considering that files located in
the /dev/disk/by-[id|path] directories are symlinks then we can resolve
the symlink to get the actual device /dev/xxxx.
Closes: #1480
=> osd_disk_activate: resolve device symlink

src/daemon/disk_list.sh, src/daemon/docker_exec.sh, src/daemon/osd_scenarios/osd_disk_activate.sh, src/daemon/osd_scenarios/osd_disks.sh, src/daemon/osd_scenarios/osd_volume_activate.sh
This is a the list of the commits backported to stable-4.0. It's mainly about osd_volume_activate and disk_list.sh changes.
f96aaa8 fix: delete temporary mount point
9fa8986 osd_disk_activate: resolve device symlink
0625c25 osd_volume_activate: handle loop device
cfce9fe osd_volume_activate: fix bug in teardown
4b0360a osd_volume_activate: fix osd_volume_lvm function
f5d8ba2 osd_volume_activate: cleanup dmcrypt when osd is stopped
4da6ca2 docker_exec: execute sigterm_cleanup_post() when signal is SIGCHLD
206ee85 osd_volume_activate: fix a bug in findmnt cmd call
3df9a91 fix: assign properly OSD_DISKS variable
c56e627 disk_list.sh: Don't use wildcard on OSD device
=> backports stable-4.0

src/daemon/disk_list.sh, src/daemon/docker_exec.sh, src/daemon/osd_scenarios/osd_disks.sh, src/daemon/osd_scenarios/osd_volume_activate.sh
This is a the list of the commits backported to stable-3.2. It's mainly about osd_volume_activate and disk_list.sh changes.
de54772 fix: delete temporary mount point
3454e80 docker_exec: execute sigterm_cleanup_post() when signal is SIGCHLD
ae8387c osd_volume_activate: fix a bug in findmnt cmd call
e3d1299 fix: assign properly OSD_DISKS variable
=> backports stable-3.2

src/daemon-base/__CEPH_BASE_PACKAGES__
The mon and osd need smartctl and nvme to scrape metrics from HDDs/SSDs.
=> src/daemon-base: add smartmontools and nvme-cli packages

src/daemon-base/__CEPH_BASE_PACKAGES__
The mon and osd need smartctl and nvme to scrape metrics from HDDs/SSDs.
Closes: #1396
Backport: #1489
(cherry picked from commit 854cf34296706337a59e95124ee80b6afe1cea36)
=> src/daemon-base: add smartmontools and nvme-cli packages (bp #1489)

ceph-releases/ALL/ubi8/daemon-base/__DOCKERFILE_PREINSTALL__
This was done downstream and to avoid conflict during sync between
upstream and downstream we should use the same syntax.
=> ubi8: use quotes for LABEL version

src/daemon-base/__CEPH_BASE_PACKAGES__
This is needed to turn device LEDs on and off.
=> src/daemon-base: add libstoragemgmt

ceph-releases/luminous/daemon/osd_scenarios/osd_disk_activate.sh, ceph-releases/mimic/daemon/osd_scenarios/osd_disk_activate.sh, src/daemon/osd_scenarios/osd_disk_activate.sh, src/daemon/osd_scenarios/osd_volume_activate.sh
The ceph-osd systemd unit script set LimitNOFILE=1048576 and 
LimitNPROC=1048576.
We should enforce this value before executing the ceph-osd process.
This is especially true when the container is started with custom ulimit
nofile values but smaller than the expected (like ceph-ansible does)
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1766079
=> src/daemon: enforce ceph-osd ulimit values

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
To avoid the progress meter in the build output we should set the silent
option on curl commands.
=> centos: Add silent option to curl commands

src/daemon/osd_scenarios/osd_disk_activate.sh, src/daemon/osd_scenarios/osd_volume_activate.sh
The ceph-osd systemd unit script set LimitNOFILE=1048576 and
LimitNPROC=1048576.
We should enforce this value before executing the ceph-osd process.
This is especially true when the container is started with custom ulimit
nofile values but smaller than the expected (like ceph-ansible does)
Backport: #1497 
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1766079
(cherry picked from commit 881b66da06871e4b8f7fb1064d14d7ab1b9fd4ac)
=> src/daemon: enforce ceph-osd ulimit values (bp #1497)

src/daemon-base/Makefile
If there's already base image present on the system then the new build
won't try to pull the latest version of that image.
When the base image isn't present on the system then the image will be
downloaded to the latest version.
That's why we could have:
```console
$ docker images
centos  7  5f65840122d0  18 months ago  234MB
```
instead of:
```console
$ docker images
centos  7  67fa590cfc1c   2 months ago  202MB
```
By using the --pull parameter with the docker build command we ensure
that the latest base image is pulled.
=> Makefile: add docker pull parameter on build

src/daemon-base/Makefile
If there's already base image present on the system then the new build
won't try to pull the latest version of that image.
When the base image isn't present on the system then the image will be
downloaded to the latest version.
That's why we could have:
$ docker images
centos  7  5f65840122d0  18 months ago  234MB
instead of:
$ docker images
centos  7  67fa590cfc1c   2 months ago  202MB
By using the --pull parameter with the docker build command we ensure
that the latest base image is pulled.
Backport: #1501 
(cherry picked from commit e247e24a182352b3bab94ba444c779678031fa07)
=> Makefile: add docker pull parameter on build (bp #1501)

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Ceph is in the process of moving to python 3 only but in the meantime we need a higher version of remoto which has a better support of python 2.
This can get reverted in a few weeks when that transition is finished.
=> ceph: temporarily use remoto from pip

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
To update remoto via pip we need to run the upgrade process after the
package installation otherwise we will still have the old remoto version
from the rpm package.
=> centos: run pip after rpm package installation

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
I seem to need openssh-clients installed for remoto to work.
This should probably be a dependency of the package?
=> ceph: need openssh-clients for remoto to work

contrib/build-push-ceph-container-imgs.sh
Change from cephci/daemon-base to ceph-ci/ceph.
Also, push a second tag that is just "branchname"
Signed-off-by: Dan Mick <dan.mick@redhat.com>
Resolves #
Checklist:
=> contrib/build-push-ceph-container-imgs.sh: CI: switch to ceph-ci/ceph

src/daemon/demo.sh, src/daemon/start_mon.sh
Since [1] the ceph status will show a health warning when the pool size
is set the 1.
On the demo scenario we can disable this warning.
This is only for ceph release >= octopus.
[1] https://github.com/ceph/ceph/commit/33c647e
=> demo: Fix ceph health with no redundancy

src/daemon/demo.sh
We don't need to set the osd data path in the global section. If someone
wants to add more OSDs then it won't be possible because the OSD 0 data
path is set globally.
Instead we should set this in the osd.0 section.
=> demo: move OSD data path in dedicated section

ceph-releases/ALL/ubi8/daemon/container.yaml
This allows us to build the RHEL 8-based container image using packages
from ODCS.
Resolves #
Checklist:
=> ubi8: add container.yaml

src/daemon/start_nfs.sh
This runs a dedicated dbus daemon for nfs-ganesha in order to avoid
using the host dbus socket so we don't have to launch nfs-ganesha with
--privileged option.
Related ceph-ansible PR: ceph/ceph-ansible#4760
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1725254
=> nfs: run a dedicated dbus daemon for nfs-ganesha

src/daemon/start_nfs.sh
This runs a dedicated dbus daemon for nfs-ganesha in order to avoid
using the host dbus socket so we don't have to launch nfs-ganesha with
--privileged option.
Related ceph-ansible PR: ceph/ceph-ansible#4760
Backport: #1517 
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1725254
(cherry picked from commit 9d78f73178d2e69b3972ea5aa62cf89188f7cad9)
=> nfs: run a dedicated dbus daemon for nfs-ganesha (bp #1517)

src/daemon/README.md
The ceph container image are based on CentOS which use the ceph user
mapped on the uid/gid 167.
Closes: #1520
=> README: update ceph uid/gid value for ceph osd

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Reverts ceph/ceph-container#1507
Replaced by https://github.com/ceph/ceph/pull/31806
=> Revert "ceph: need openssh-clients for remoto to work"

ceph-releases/ALL/ubi8/daemon-base/__CEPH_MGR_PACKAGES__
This adds the ceph-mgr-k8sevents rpm package to the RHEL 8 container
image for OCS/rook-ceph usage.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1763918
=> ubi8: add ceph-mgr-k8sevents package

ceph-releases/ALL/ubi8/daemon-base/__CEPH_MGR_PACKAGES__
This adds the ceph-mgr-k8sevents rpm package to the RHEL 8 container
image for OCS/rook-ceph usage.
Backport: #1524
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1763918
(cherry picked from commit 3b4056dc12bd8a4d02e563cfc6e428e3c8af8166)
=> ubi8: add ceph-mgr-k8sevents package (bp #1524)

ceph-releases/ALL/ubi8/daemon-base/__CEPH_MGR_PACKAGES__
The ceph-mgr-ssh isn't present in RHCS 4.0
=> ubi8: remove ceph-mgr-ssh package

ceph-releases/ALL/ubi8/daemon-base/__CEPH_MGR_PACKAGES__
The ceph-mgr-ssh isn't present in RHCS 4.0
Backport: #1526
(cherry picked from commit 5cbbda3a2ab438b72cc796a9333fd5b0247be38a)
=> ubi8: remove ceph-mgr-ssh package (bp #1526)

contrib/make-ceph-base-manifests.sh
Only vX and vX.Y were created on ceph/ceph.
The full vX.Y.Z tag was present but with a date suffix.
Let's add it by default.
Closes: #1528
=> contrib: add vX.Y.Z container tag on ceph/ceph

contrib/ceph-build-config.sh
Now the curl command against the docker hub registry to list the
tags per page doesn't fail on non existing page.
Because there's only a condition on the curl command then there's an
infinite loop with the page number incrementing.
We can break the loop when the next attribute is null.
=> ceph-build-config: fix infinite loop on registry

ceph-releases/ALL/ubi8/daemon-base/__CEPH_MGR_PACKAGES__, src/daemon-base/__CEPH_MGR_PACKAGES__
Ceph nautilus 14.2.5 is now out and includes the k8sevents mgr package.
=> daemon-base: add ceph-mgr-k8sevents package

ceph-releases/ALL/ubi8/daemon-base/__CEPH_MGR_PACKAGES__, src/daemon-base/__CEPH_MGR_PACKAGES__
Ceph nautilus 14.2.5 is now out and includes the k8sevents mgr package.
Backport: #1531
(cherry picked from commit 21c2ff9ec2d4470bf31dfebb7929874f340799d2)
=> daemon-base: add ceph-mgr-k8sevents package (bp #1531)

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, src/daemon-base/__CEPH_MGR_PACKAGES__
This is an ugly kludge but it will work for the time being until something
more elegant is sorted out.
=> daemon-base: drop ceph-mgr-ssh, except for the master/wip-* special case

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/nautilus/daemon-base/__CEPH_MGR_PACKAGES__
This is a follow up on #1534.
Because ceph-mgr-cephadm is only available on octopus then we need a
dedicated copy of the ceph mgr packages for nautilus.
=> daemon-base: add cephadm mgr package for octopus

src/daemon/common_functions.sh
Some devices use an extra 'p' character before the partition number.
=> daemon: handle special devices in dmcrypt data

src/daemon/common_functions.sh
Some devices use an extra 'p' character before the partition number.
Backport: #1538
=> daemon: handle special devices in dmcrypt data (bp #1538)

src/daemon/start_nfs.sh
This reverts commit 9d78f73178d2e69b3972ea5aa62cf89188f7cad9.
Otherwise ganesha consumers can't dynamically update exports using dbus
because the dbus socket is accessible only from inside the container.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1784562
=> Revert "nfs: run a dedicated dbus daemon for nfs-ganesha"

src/daemon/common_functions.sh
Makes find skip files already owned by 'ceph' user when launching
chown command; chown will unconditionally re-apply the ownership
causing a lot of writes.
It looks like we use this function not only when it is necessary
to create the directories but also when there is existing data into
those, as a safety measure.
Resolves: #1536
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1784047
Signed-off-by: Giulio Fidente <gfidente@redhat.com>
=> daemon: speed up create_mandatory_directories

src/daemon/start_nfs.sh
This reverts commit 9d78f73178d2e69b3972ea5aa62cf89188f7cad9.
Otherwise ganesha consumers can't dynamically update exports using dbus
because the dbus socket is accessible only from inside the container.
Backport: #1541
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1784562
(cherry picked from commit e654565d0ba670ef671ff384727f19fbd0d70915)
=> Revert "nfs: run a dedicated dbus daemon for nfs-ganesha" (bp #1541)

src/daemon/common_functions.sh
Makes find skip files already owned by 'ceph' user when launching
chown command; chown will unconditionally re-apply the ownership
causing a lot of writes.
It looks like we use this function not only when it is necessary
to create the directories but also when there is existing data into
those, as a safety measure.
Backport: #1537
Resolves: #1536
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1784047
Signed-off-by: Giulio Fidente <gfidente@redhat.com>
(cherry picked from commit 625630cc4a9722ad1130612c63871e75d6e9c26c)
=> daemon: speed up create_mandatory_directories (bp #1537)

contrib/build-push-ceph-container-imgs.sh
When using a release with two digits in the z release then this isn't
catch by the regex.
=> contrib: support two digits z release

.travis.yml, Makefile, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/ALL/centos/daemon-base/__ISCSI_PACKAGES__, ceph-releases/master/daemon-base/__DOCKERFILE_POSTINSTALL_CLEANUP__, ceph-releases/master/daemon/__DOCKERFILE_INSTALL__, ceph-releases/nautilus/daemon-base/__ISCSI_PACKAGES__, contrib/build-push-ceph-container-imgs.sh, src/daemon/demo.sh, travis-builds/validate_demo_cluster.sh
This switches the base container image from CentOS 7 to CentOS 8 for
octopus+ ceph releases.
Starting with octopus release python2 is dropped so we don't need the
pip remoto hack anymore.
=> Add CentOS 8 support for octopus

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
On some GNU/Linux distribution, when updating the CentOS 8 packages in
the container base image then the platform-python package is updated.
After the update the python interpreter is broken so we can run yum/dnf
commands anymore
yum: /usr/libexec/platform-python: bad interpreter: Permission denied
As a temporary solution we can disable the platform-python and
python3-libs package update.
=> centos: disable python3 update for CentOS 8

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_POSTINSTALL_CLEANUP__, ceph-releases/ALL/centos/daemon-base/__ISCSI_PACKAGES__
There's now build available for ceph-iscsi and tcmu-runner on CentOS 8.
The rtslib python library is available in both CentOS 7 and 8 by default
so we don't need this shaman repository anymore.
=> daemon-base: Add ceph-iscsi for octopus on CentOS8

contrib/build-push-ceph-container-imgs-arm64.sh, contrib/build-push-ceph-container-imgs.sh
This also add a new function to get the centos release from a ceph
release/branch
=> contrib: fix centos release for ceph-ci build

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, src/daemon/demo.sh, travis-builds/validate_demo_cluster.sh
There nfs-ganesha builds available on https://download.nfs-ganesha.org/
instead of shaman.
Until we have someting available on shaman we can use the other source.
This also re-enable the nfs test in demo/travis.
=> centos: add nfs-ganesha on CentOS 8

src/daemon/demo.sh
The s3cmd isn't yet present on epel 8 repository but in epel 8 testing
so enabling the EPEL testing repository only during the s3cmd package
installation until it is promoted.
=> centos 8: add s3cmd package

contrib/ceph-build-config.sh
Currently the regex builds every package, which leads to issue when not
building the stable minor '2' because some packages do not exist.
For example, we hit:
No package ceph-mgr-k8sevents-14.1.0 available.
It doesn't make sense to build non-stable packages because we have dev
builds.
So this will avoid packages issues as well as speeding up the build
time.
Checklist:
=> build: only build stable releases

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/nautilus/daemon-base/__CEPH_MGR_PACKAGES__
The ceph-mgr-k8sevents package isn't present in all Nautilus release
but only since 14.2.5.
If we try to build an older release then this package will be installed
and veriried which ultimately fails.
=> nautilus: parametrize k8sevents package name

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
This reverts commit c7500c027aca679e0f8696f5e6dd5a9038783e06.
We don't need this anymore since CentOS 8.1 container image.
=> Revert "centos: disable python3 update for CentOS 8"

ceph-releases/ALL/centos/8/__DOCKERFILE_CLEAN_COMMON__
The libsystemd-shared file is located in the /usr/lib/systemd directory
on CentOS 8.
Because we are removing the content of that directory during the
container clean then commands like udevadm that are linked to the
systemd library generete errors like:
error while loading shared libraries: libsystemd-shared-239.so: cannot
open shared object file: No such file or directory
```console
$ ldd /usr/bin/udevadm | grep systemd
libsystemd-shared-239.so => not found
```
=> centos8: don't remove /usr/lib/systemd

src/daemon/common_functions.sh, src/daemon/osd_scenarios/osd_volume_activate.sh
When managing legacy ceph-disk based OSD with ceph-volume then we need
to open the encrypted partitions before running the ceph-volume simple
scan command otherwise the scan will fail.
This situation happens after a reboot because all encrypted partitions
are closed.
$ ceph-volume simple scan /dev/sdb1 --force
(...)
--> broken symlink found /tmp/tmpept0ox2j/block -> /dev/mapper/457d7196-4015-40fe-aa83-a160477450f7
$ ceph-volume.log
(...)
[ceph_volume.util.system][INFO  ] /dev/sdb1 was not found as mounted
[ceph_volume.util.encryption][WARNING] failed to detect device mapper information
[ceph_volume.util.encryption][WARNING] failed to detect device mapper information
[ceph_volume.devices.simple.scan][WARNING] broken symlink found /tmp/tmpept0ox2j/block -> …
=> osd_volume_activate: open encrypted legacy parts (bp #1572)

src/daemon/start_mon.sh, src/daemon/variables_entrypoint.sh
as of nautilus, we can use these options so we can log to file 'on the fly'.
eg:
```
$ sudo podman exec ceph-mon-mon0 ceph config set mon.mon0 log_to_file true
$ sudo podman exec ceph-mon-mon0 ceph config set mon.mon0 mon_cluster_log_to_file true
```
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1710548
Closes: ceph/ceph-container#1479
=> add logging on the fly support

src/daemon/start_mon.sh, src/daemon/variables_entrypoint.sh
as of nautilus, we can use these options so we can log to file 'on the fly'.
eg:
```
$ sudo podman exec ceph-mon-mon0 ceph config set mon.mon0 log_to_file true
$ sudo podman exec ceph-mon-mon0 ceph config set mon.mon0 mon_cluster_log_to_file true
```
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1710548
Closes: ceph/ceph-container#1479
Backport: #1574
(cherry picked from commit a63bcf48c7e69c3abe7288e77c85c14554188247)
=> add logging on the fly support (bp #1574)

src/daemon/start_mon.sh
Typical error:
```
Jan 21 16:15:20 mon0 docker[19458]: parse error setting 'mon_cluster_log_to_file' to 'false ' (Expected option value to be integer, got 'false ')
```
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1793608
=> start_mon: fix DAEMON_OPTS

src/daemon/start_mon.sh
Typical error:
```
Jan 21 16:15:20 mon0 docker[19458]: parse error setting 'mon_cluster_log_to_file' to 'false ' (Expected option value to be integer, got 'false ')
```
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1793608
Backport: #1576
(cherry picked from commit dfaf2733304900172d51a3e32019f58f8d9c9acc)
=> start_mon: fix DAEMON_OPTS (bp #1576)

ceph-releases/ALL/ubi8/daemon-base/__GANESHA_PACKAGES__
Since nfs-ganesha 2.8.3, there's a new subpackage for using RADOS URLS
which is called nfs-ganesha-rados-urls
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1797075
=> ubi8: add nfs-ganesha-rados-urls package

ceph-releases/ALL/ubi8/daemon-base/__GANESHA_PACKAGES__
Since nfs-ganesha 2.8.3, there's a new subpackage for using RADOS URLS
which is called nfs-ganesha-rados-urls
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1797075
Backport: #1580
(cherry picked from commit 97985eb16d967fed7e2325d19e2850cf9c8de6f3)
=> ubi8: add nfs-ganesha-rados-urls package (bp #1580)

src/daemon/osd_scenarios/osd_disk_activate.sh
When the daemon tries to mount an nvme device which was prepared by ceph-disk, the partition path should be /dev/nvme0n1p1, the current osd_disk_activate.sh will use the hdd rule and try to find the partition as /dev/nvme0n11, which missed a 'p'.
As "dev_part" already been widly used, we can use it here to avoid un-reliable text concatenation.
Backport: #1582
Signed-off-by: Tang Jianyu <jianyu@jianyu.net>
(cherry picked from commit 1dfeba5a7fb018311c4a67862efa74a773931894)
=> Fix activating legacy osd-disk partitioned nvme device (bp #1582)

src/daemon/demo.sh
The container memory tuning should only be set on nautilus+ ceph
releases.
=> demo: fix memory tuning condition

src/daemon/common_functions.sh
In Jewel the lockbox partition is using the partition number 3 compared
to 5 for Luminous.
The dmcrypt_data_map function doesn't handle this situation causing issue
when upgrading from Jewel to Luminous with ceph-disk dmcrypt OSDs.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1803755
=> common_functions: fix lockbox partition number

src/daemon/common_functions.sh
In Jewel the lockbox partition is using the partition number 3 compared
to 5 for Luminous.
The dmcrypt_data_map function doesn't handle this situation causing issue
when upgrading from Jewel to Luminous with ceph-disk dmcrypt OSDs.
Backport: #1587
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1803755
(cherry picked from commit 3fda10ce4608dec5469353bbe06eccf31295ae7f)
=> common_functions: fix lockbox partition number (bp #1587)

src/daemon-base/Makefile
it's a workaround of https://bugzilla.redhat.com/show_bug.cgi?id=1802907
Fixes: https://tracker.ceph.com/issues/44242
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
Resolves #
Checklist:
=> daemon-base/Makefile: use root for groupadd in podman

src/daemon-base/Makefile
This reverts commit 4564c28b25b3a20c9fa1ad19340e083086b7ba1b and f307829
This is breaking the upstream ci build system.
=> Revert "daemon-base/Makefile: chown $(USER) $(DAEMON_BASE_IMAGE)"

src/daemon/osd_scenarios/osd_volume_activate.sh
To find the correct OSD id in all the OSD devices we need to scan them.
This requires to mount the lockbox partitions and open the encrypted
partitions when using dmcrypt.
After the ceph-volume simple scan command we should umount the lockbox
partitions otherwise each OSD containers will mount all lockbox
partitions.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1806033
=> osd_volume_activate: umount lockbox after scanning

src/daemon/osd_scenarios/osd_volume_activate.sh
To find the correct OSD id in all the OSD devices we need to scan them.
This requires to mount the lockbox partitions and open the encrypted
partitions when using dmcrypt.
After the ceph-volume simple scan command we should umount the lockbox
partitions otherwise each OSD containers will mount all lockbox
partitions.
Backport: #1592
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1806033
(cherry picked from commit 82a1ee7d9fcbda64b21365a70c10af5a02634469)
=> osd_volume_activate: umount lockbox after scanning (bp #1592)

ceph-releases/ALL/ubi8/daemon/gating.yaml
Our internal Greenwave instance will use these settings to determine overall pass/fail test results.
=> ubi8: add gating.yaml

ceph-releases/ALL/ubi8/daemon/gating.yaml
Our internal Greenwave instance will use these settings to determine
overall pass/fail test results.
Backport: #1600
Co-authored-by: subhash <vpoliset@redhat.com>
(cherry picked from commit 3916d7b77c7c2877c1b5ea533c76471d5c0cb852)
=> ubi8: add gating.yaml (bp #1600)

ceph-releases/ALL/rhel7/daemon/gating.yaml
Our internal Greenwave instance will use these settings to determine
overall pass/fail test results.
Backport: #1600
Co-authored-by: subhash <vpoliset@redhat.com>
(cherry picked from commit 3916d7b77c7c2877c1b5ea533c76471d5c0cb852)
=> rhel7: add gating.yaml (bp #1600)

src/__DOCKERFILE_TRACEABILITY_LABELS__
While implementing https://tracker.ceph.com/issues/44440 we had the need of being able to identify images that are "ceph images".
The idea behind this PR is to have an easy way to filter ceph images, e.g.:
```
docker images --filter label=ceph=True
```
Signed-off-by: Ricardo Marques <rimarques@suse.com>
Checklist:
=> labels: add label to inform this is a ceph container

contrib/build-push-ceph-container-imgs.sh
The _ceph_release function which returns the CentOS release used as
the base container image was missing the octopus release.
=> contrib: add missing octopus condition

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Because octopus is still in development then we should still use shaman
as the source and only switch to download.ceph.com when the release
become stable (15.2.x).
=> octopus: use ceph bits from shaman

tox.ini
This is to match the ceph-ansible ansible requirement.
We don't need the ceph_ansible2.3 env because it doesn't exist anymore.
=> tox: update ansible release

.travis.yml
This is not used anymore so we can remove it.
=> travis: remove secure variable

.travis.yml
This is not used anymore so we can remove it.
Backport: #1612
(cherry picked from commit e5702444dc9e99571214a03c02311a50cc8d0378)
=> travis: remove secure variable (bp #1612)

contrib/ceph-build-config.sh
This commit adds the Ceph Octopus release to the ceph/ceph repository
but only for x86_64 architecture.
When the arm64 build will be available we will add it to the mix.
This also allows using RC build (X.1.Z) in addition of stable build
(X.2.Z).
=> contrib: add octopus to ceph/ceph repository

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, contrib/build-push-ceph-container-imgs-arm64.sh, contrib/ceph-build-config.sh
We now have arm64 build available on download.ceph.com so we can add the
octopus release to the list.
=> contrib: add octopus to arm64 list

contrib/build-push-ceph-container-imgs.sh
In our CI, we're occasionally seeing https://github.com/containers/libpod/issues/5306
This PR is an attempt to fix those issues based on the suggestions in the comments.
- Cleanup leftover artifacts from previous builds
=> contrib: Aggressively clean up leftover podman artifacts

ceph-releases/ALL/centos-arm64/8/__DOCKERFILE_CLEAN_COMMON__, ceph-releases/ALL/centos-arm64/8/daemon-base/__DOCKERFILE_POSTINSTALL_CLEANUP__, ceph-releases/ALL/centos-arm64/8/daemon-base/__GANESHA_PACKAGES__, ceph-releases/ALL/centos-arm64/8/daemon/__DOCKERFILE_INSTALL__, ceph-releases/ALL/centos-arm64/8/daemon/__ETCD_PACKAGE__, ceph-releases/ALL/centos-arm64/8/daemon/__KUBECTL_PACKAGE__
There was no CentOS 8 configuration for the arm64 architecture so the
Octopus on that arch currently fails.
=> ceph-releases: add centos-arm64/8 directory

contrib/build-push-ceph-container-imgs.sh
Override the ceph releases list for stable-5.0 branch (octopus).
=> contrib: add stable-5.0 branch for octopus

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
We now have nfs-ganesha 3.2 builds available on download.ceph.com so we
should use this source for the Ceph Octopus release.
=> octopus: nfs-ganesha bits from download.ceph.com

.travis.yml
We don't need the branch limitation on stable branch.
=> travis: remove branch limitation

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
We now have nfs-ganesha 3.2 builds available on download.ceph.com so we
should use this source for the Ceph Octopus release.
Backport: #1620
(cherry picked from commit 116b7191954657223328711361a61cab98e7859e)
=> octopus: nfs-ganesha bits from download.ceph.com (bp #1620)

contrib/compose-rhcs.sh
This updates the ceph release for ubi8 to octopus and also disable the
ceph csi packages.
=> ubi8: update to octopus

contrib/compose-rhcs.sh
This updates the ceph release for ubi8 to octopus and also disable the
ceph csi packages.
Backport: #1628
(cherry picked from commit e91b78b6883115c4a3465dacd7fe6c9c063202d3)
=> ubi8: update to octopus (bp #1628)

contrib/build-push-ceph-container-imgs.sh
Fixes:
```
+ rm -rf /home/jenkins-build/.config/containers
+ rm -rf /home/jenkins-build/.local/share/containers
rm: cannot remove '/home/jenkins-build/.local/share/containers/storage/overlay/aff9833d464191900b4a3b6e68aad912f930de639b411124e433aeb3757001cd/diff/root/.wh..wh..opq': Permission denied
rm: cannot remove '/home/jenkins-build/.local/share/containers/storage/overlay/aff9833d464191900b4a3b6e68aad912f930de639b411124e433aeb3757001cd/diff/root/.bash_logout': Permission denied
```
=> contrib: Use sudo to cleanup podman cache

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
We now have ceph-iscsi 3.x builds available on download.ceph.com so we
should use this source for the Ceph Octopus release.
=> octopus: ceph-iscsi bits from download.ceph.com

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
We now have ceph-iscsi 3.x builds available on download.ceph.com so we
should use this source for the Ceph Octopus release.
Backport: #1634
(cherry picked from commit 41f4d43dfc8a061f07317d80add8f390d26e3571)
=> octopus: ceph-iscsi bits from download.ceph.com (bp #1634)

tests/tox.sh
The site-docker.yml.sample playbook is a symlink to the
site-container.yml.sample playbook and will be remove soon.
See https://github.com/ceph/ceph-ansible/pull/5216
=> tests: update ceph-ansible playbook name

tests/tox.sh
The site-docker.yml.sample playbook is a symlink to the
site-container.yml.sample playbook and will be remove soon.
Backport: #1637
See https://github.com/ceph/ceph-ansible/pull/5216
(cherry picked from commit c5cfca3a9f9fff2fdabe469f549b2b6e8ba0a48d)
=> tests: update ceph-ansible playbook name (bp #1637)

contrib/build-push-ceph-container-imgs.sh
- Revert attempts (dcdf268 and 8f7c363) to workaround a bug by cleaning up cached podman artifacts
- Use newer version of podman when building CI containers
- Use newer version of fuse-overlayfs when building CI containers
=> contrib: Use newer version of podman when building CI containers

tests/tox.sh
This aligns the playbooks order with ceph-ansible testing.
=> tests/tox: run setup before the main playbook

.github/stale.yml
enable stale bot in order to close PR with no recent activity.
=> repo: Add configuration for stalebot

tests/tox.sh
This aligns the playbooks order with ceph-ansible testing.
Backport: #1641
(cherry picked from commit 781d3c47f8012cfa8f9036d18e9018b37e66f23c)
=> tests/tox: run setup before the main playbook (bp #1641)

ceph-releases/ALL/ubi8/daemon-base/__DOCKERFILE_INSTALL__
The sso mgr module requires the saml python library to be installed.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1820217
=> ubi8: add python3-saml package for mgr SSO module

ceph-releases/ALL/ubi8/daemon-base/__DOCKERFILE_PREINSTALL__, ceph-releases/ALL/ubi8/daemon/content_sets.yml
RHCS 5 will be based on Ceph Octopus release.
Backport: #1649
(cherry picked from commit 2b6244e372fa2fbcf9e6f354686346eb1e41cd6e)
=> ubi8: update for RHCS 5 (bp #1649)

maint-lib/stagelib/replace.py
The replace.py script doesn't work on python 3.6 because the content
of the file read is using the default ascii encoding.
We should for the utf-8 encoding instead.
Resolves: #1182
=> maint-lib/replace.py: use utf-8 decoding on file

tox.ini
This is to match the ceph-ansible ansible requirement. ceph-ansible now
uses ansible 2.9.
=> tox: update ansible release to 2.9

tox.ini
This is to match the ceph-ansible ansible requirement. ceph-ansible now
uses ansible 2.9.
Backport: #1652
(cherry picked from commit c050085bc30e7a88f276ac165898c3327f9875e4)
=> tox: update ansible release to 2.9 (bp #1652)

tests/tox.sh
This is to reflect the ceph-ansible configuration.
Backport: #1653
(cherry picked from commit 0a73e117f338773ea1f902f026093aa00dbaeb13)
=> tests/tox.sh: increase pytest thread (bp #1653)

contrib/ceph-build-config.sh
This was added to get the first Octopus RC images but now this release
is stable we don't need to rebuild RC images anymore.
=> ceph-build-config: remove RC build

contrib/ceph-build-config.sh
7966351 introduced a regression in the ceph version regex. It's not
possible anymore to build ceph release with a two digits z release like
x.y.10
=> contrib: fix z release package regex

contrib/commit-rhcs.sh
The `contrib/commit-rhcs.sh` script needs to look in the "octopus" directory for RHCS 5.
=> contrib: update commit-rhcs.sh for octopus

contrib/commit-rhcs.sh
The contrib/commit-rhcs.sh script needs to look in the "octopus"
directory for RHCS 5.
Backport: #1664
(cherry picked from commit c14464c0e94b8146d89a341596d2cfc6a8daa97f)
=> contrib: update commit-rhcs for octopus (bp #1664)

ceph-releases/luminous/daemon/osd_scenarios/osd_disk_activate.sh, ceph-releases/mimic/daemon/osd_scenarios/osd_disk_activate.sh, src/daemon/common_functions.sh
When applying ceph owner/group for Bluestore OSD with dedicated DB
and/or WAL partitions then the blank spaces in the dev_real_path
variable will be preserve. The result will be a single string which
won't be evaluated correctly with the for loop.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1831273
Closes: #1579
=> common_function: use dev_real_path as array

src/daemon/common_functions.sh, src/daemon/osd_scenarios/osd_disk_activate.sh
When applying ceph owner/group for Bluestore OSD with dedicated DB
and/or WAL partitions then the blank spaces in the dev_real_path
variable will be preserve. The result will be a single string which
won't be evaluated correctly with the for loop.
Backport: #1667
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1831273
Closes: #1579
(cherry picked from commit dc262d14421f3964eea70e0cb0f4d6832120e081)
=> common_function: use dev_real_path as array (bp #1667)

ceph-releases/ALL/ubi8/daemon/container.yaml
OSBS introduced a new "`ignore_absent_pulp_repos`" setting. This setting tells ODCS to proceed when it cannot find some of the expected repositories in pulp.
The reason we must enable this setting is that Red Hat release engineering has not created all the pulp repositories in `content_sets.yml` yet. We can revert this commit when all of those pulp repositories are ready.
=> ubi8: ignore absent pulp repositories

ceph-releases/ALL/ubi8/daemon/container.yaml
OSBS introduced a new "ignore_absent_pulp_repos" setting. This setting
tells ODCS to proceed when it cannot find some of the expected
repositories in pulp.
The reason we must enable this setting is that Red Hat release
engineering has not created all the pulp repositories in
content_sets.yml yet. We can revert this commit when all of those pulp
repositories are ready.
Backport: #1669
(cherry picked from commit 59450b60137b2e9daaedac95ca750946fbeefc6e)
=> ubi8: ignore absent pulp repositories (bp #1669)

contrib/build-push-ceph-container-imgs.sh, contrib/ceph-build-config.sh
The arm64 container image needs to be referenced with the variant
attribute.
At the moment, the arm64 is only referring to arm64v8 which could change
in the futur.
This doesn't seem to be an issue on docker platform but only for podman.
Closes: #1673
=> manifest: add variant attribute to arm64 build

ceph-releases/ALL/ubi8/daemon/content_sets.yml
We're building the RHCS 5 container for s390x. Add the relevant repositories to the `content_sets.yml` file that the [OSBS](https://osbs.readthedocs.io/) and [Freshmaker](https://pagure.io/freshmaker) systems read.
=> ubi8: add s390x entry to content_sets.yml

ceph-releases/ALL/ubi8/daemon/content_sets.yml
We're building the RHCS 5 container for s390x. Add the relevant
repositories to the content_sets.yml file that the OSBS and Freshmaker
systems read.
Backport: #1678
(cherry picked from commit f0a1ab7ab391aabcf4089445b4123447eab85200)
=> ubi8: add s390x entry to content_sets.yml (bp #1678)

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
see https://download.nfs-ganesha.org/3/LATEST/RHEL/
also, the noarch packages are now offered by arch-specific repo, see
https://buildlogs.centos.org/centos/8/storage/x86_64/nfsganesha-3/Packages/n/
where nfs-ganesha-selinux-* packages can also be found.
Signed-off-by: Kefu Chai <kchai@redhat.com>
Resolves #
Checklist:
=> centos: use repo at buildlogs.centos.org for nfs-ganesha

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
This allows to use https instead of http for the nfs ganesha repository
hosted on download.ceph.com
Resolves #
Checklist:
=> centos: use https for ganesha repository

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
This allows to use https instead of http for the nfs ganesha repository
hosted on download.ceph.com
Backport: #1686
(cherry picked from commit abf38c046df4ce1ff5fac3957259d528999a1eb4)
=> centos: use https for ganesha repository (bp #1686)

tests/tox.sh
The IUS CentOS repository URL has been updated to https://repo.ius.io
=> tests/tox: update ius centos repository

tests/tox.sh
The IUS CentOS repository URL has been updated to https://repo.ius.io
Backport: #1690
(cherry picked from commit 292e32f343d1d5b97d78020d4f71b68cadf46511)
=> tests/tox: update ius centos repository (bp #1690)

src/daemon/osd_scenarios/osd_volume_activate.sh
This adds support for managing ceph-disk based OSDs via ceph-volume simple commands when using the `OSD_CEPH_VOLUME_ACTIVATE` entrypoint.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1844591
=> osd_volume_activate: support ceph-disk based OSDs via ceph-volume

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
All EL8 dependencies are now present on EPEL 8 so we don't need the
additional repositories that were only a temporary solution.
=> centos/8: remove copr and sepia repositories

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
All EL8 dependencies are now present on EPEL 8 so we don't need the
additional repositories that were only a temporary solution.
Backport: #1694
(cherry picked from commit 541cc031acbb5325aef06cd7eacabe6809e87657)
=> centos/8: remove copr and sepia repositories (bp #1694)

src/daemon/start_mon.sh
mon_warn_on_pool_no_redundancy has been backported to nautilus.
=> demo: fix no redundancy for nautilus

src/daemon/start_mon.sh
mon_warn_on_pool_no_redundancy has been backported to nautilus.
Backport: #1700
(cherry picked from commit 61f415697a7197e122c166faedc010e9eea6ae28)
=> demo: fix no redundancy for nautilus (bp #1700)

src/daemon/demo.sh, src/daemon/start_mon.sh
Since [1] the ceph status will show a health warning when the pool size
is set the 1.
On the demo scenario we can disable this warning.
This is only for ceph release >= nautilus.
Backport: #1700
[1] https://github.com/ceph/ceph/commit/33c647e8114b37404d8d62a08c85664cea709118
(cherry picked from commit 36d770610b6e9cdebdc392baf9af343b8f5f189d)
=> demo: Fix ceph health with no redundancy (bp #1700)

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Update nfs-ganesha from 3.2 to 3.3 for octopus.
Backport: #1699
(cherry picked from commit baaf8ba0e66d01f90bb25295b57d15b5fcce57bb)
=> centos: update nfs-ganesha to 3.3 (bp #1699)

contrib/build-push-ceph-container-imgs.sh
with teuthology supporting crimson flavor build differentiating
container on basis of only sha1 is not unique anymore.
This change will push container with tag format:
<>:sha1:os-os_version-shaman_osd_flavor
Signed-off-by: Deepika Upadhyay <dupadhya@redhat.com>
Resolves #
Checklist:
=> build-push-ceph-container-imgs.sh: change container tag

contrib/commit-rhcs.sh, contrib/compose-rhcs.sh
We now need to inherit from registry.redhat.io when using the ubi8
container image.
The ubi8 taag also changed from 8-released to latest.
=> [skip ci] contrib/rhcs: update ubi8 container image

contrib/commit-rhcs.sh, contrib/compose-rhcs.sh
We now need to inherit from registry.redhat.io when using the ubi8
container image.
The ubi8 taag also changed from 8-released to latest.
Backport: #1721
(cherry picked from commit 97db9ff4e8004d31e9db249e29917faff0c6e4aa)
=> [skip ci] contrib/rhcs: update ubi8 container image (bp #1721)

contrib/commit-rhcs.sh, contrib/compose-rhcs.sh
We now need to inherit from registry.redhat.io when using the rhel7
container image.
The rhel7 tag also changed from 7-released to latest.
Backport: #1721
(cherry picked from commit 97db9ff4e8004d31e9db249e29917faff0c6e4aa)
=> [skip ci] contrib/rhcs: update rhel7 container image (bp #1721)

src/daemon/start_tcmu_runner.sh, src/daemon/variables_entrypoint.sh, tests/tox.sh
This commit changes the log directory for tcmu-runner to
`/var/log/tcmu-runner`. This way we can bindmount this directory in
order to make logrotate access it from the host.
ceph-ansible related PR: ceph/ceph-ansible#5780
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1873915
=> tcmu-runner: set log dir to /var/log/tcmu-runner

src/daemon/start_tcmu_runner.sh, src/daemon/variables_entrypoint.sh, tests/tox.sh
This commit changes the log directory for tcmu-runner to
/var/log/tcmu-runner. This way we can bindmount this directory in
order to make logrotate access it from the host.
ceph-ansible related PR: ceph/ceph-ansible#5780
Backport: #1726
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1873915
Signed-off-by: Guillaume Abrioux gabrioux@redhat.com
(cherry picked from commit 94c4ece920d4ef03bd004e0fc4aa9019c8ae37ac)
=> tcmu-runner: set log dir to /var/log/tcmu-runner (bp #1726)

tests/tox.sh
If we use sudo with make then we will generate some files with root:root
owner/group which can't be deleted by jenkins during the workspace clean
up.
Because we already allow the current user to use the docker socket then
there's no need to use sudo with docker commands too.
=> tests/tox: don't use sudo with make

tests/tox.sh
If we use sudo with make then we will generate some files with root:root
owner/group which can't be deleted by jenkins during the workspace clean
up.
Because we already allow the current user to use the docker socket then
there's no need to use sudo with docker commands too.
Backport: #1730
(cherry picked from commit c945b6c3d040f8a2a4e032840edd362d69fc1dd9)
=> tests/tox: don't use sudo with make (bp #1730)

ceph-releases/ALL/daemon/__WEB_INSTALL_ETCDCTL__
When installing etcdctl binary via the upstream tarball the owner/group
is set to 478493:89939 which could lead to failure when using podman and
rootless containers.
There's no need to have such uid/gid on the etcdctl binary. When the
installation is done by package then the owner/group is root.
Closes: #1725
=> daemon: set root owner/group on etcdctl binary

ceph-releases/ALL/daemon/__WEB_INSTALL_ETCDCTL__
When installing etcdctl binary via the upstream tarball the owner/group
is set to 478493:89939 which could lead to failure when using podman and
rootless containers.
There's no need to have such uid/gid on the etcdctl binary. When the
installation is done by package then the owner/group is root.
Backport: #1737 
Closes: #1725
=> daemon: set root owner/group on etcdctl binary (bp #1737)

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Since smarmontools 7 won't be present in CentOS 8 until 8.3 then we will
be stuck with 6.6 which isn't compatible with the device health status.
This re-adds ktdreyer copr repository that contains a smartmontools 7
build.
This is a temporary solution until CentOS 8.3 release.
Fixes: https://tracker.ceph.com/issues/47107
=> centos/8: add ktdreyer copr repository back

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Since smarmontools 7 won't be present in CentOS 8 until 8.3 then we will
be stuck with 6.6 which isn't compatible with the device health status.
This re-adds ktdreyer copr repository that contains a smartmontools 7
build.
This is a temporary solution until CentOS 8.3 release.
Fixes: https://tracker.ceph.com/issues/47107
Backport: #1745
(cherry picked from commit aa644a5fd03aecb9eda8b95002d25ded9c57b25e)
=> centos/8: add ktdreyer copr repository back (bp #1745)

src/daemon/start_mon.sh, src/daemon/variables_entrypoint.sh
Using --default-* in DAEMON_OPTS to allow ceph.conf to override this value.
Signed-off-by: Seena Fallah <seenafallah@gmail.com>
Checklist:
=> DAEMON_OPTS: use --default-* for logging opts

contrib/build-ceph-base.sh, contrib/ceph-build-config.sh
Currently the registry login is only done just before the push operation
so any pull operations are done anonymously.
With the latest docker hub limitation, we should do any operation with
an authenticate user like we already do in the build-push-ceph scripts.
=> [skip ci] contrib: registry login earlier

src/daemon/start_mon.sh, src/daemon/variables_entrypoint.sh
Using --default-* in DAEMON_OPTS to allow ceph.conf to override this value.
Backport: #1729
Signed-off-by: Seena Fallah <seenafallah@gmail.com>
(cherry picked from commit 227775b6b86eca78001bf2aa90ffd0e0c4af1193)
=> DAEMON_OPTS: use --default-* for logging opts (bp #1729)

tests/tox.sh
To avoid docker hub rate limit on PRs and nightlies jobs.
=> tests/tox: consume docker registry credentials

contrib/build-push-ceph-container-imgs.sh
before this change, we build octopus container images for both el7 and
el8, and tag them using the same set of tag names. so the last build
wins in the racing. the consumers of these images still expect the el8
builds by asking the images by names encoded using sha1.
after this change, the el7 container images are not tagged with names
without distro_release encoded, so the el7 images does not overwrite
the el8 ones even if they are built and pushed after el8 ones with
the same sha1 and branch names.
Fixes: https://tracker.ceph.com/issues/48162
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
Resolves #
Checklist:
=> contrib: do not overwrite images created for el8

contrib/ceph-build-config.sh
To avoid unmet dependencies.
```console
The following packages have unmet dependencies:
docker.io : Depends: containerd (>= 1.2.6-0ubuntu1~)
E: Unable to correct problems, you have held broken packages.
```
=> [skip ci] contrib: force installing containerd on ubuntu

ceph-releases/ALL/centos/8/daemon-base/__CEPH_MGR_PACKAGES__
The python3-saml package is now available in EPEL 8 so we can include
it for the mgr dashboard sso module dependency.
=> centos/8: add python3-saml package

ceph-releases/ALL/centos/8/daemon-base/__CEPH_MGR_PACKAGES__
The python3-saml package is now available in EPEL 8 so we can include
it for the mgr dashboard sso module dependency.
Backport: #1756
(cherry picked from commit b682658663b616b89b39a9ca47531211813a550f)
=> centos/8: add python3-saml package (bp #1756)

ceph-releases/ALL/centos/8/daemon/__DOCKERFILE_INSTALL__, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
This reverts commit aa644a5fd03aecb9eda8b95002d25ded9c57b25e.
CentOS 8.3 has been released so we don't need the extra copr repository.
=> Revert "centos/8: add ktdreyer copr repository back"

ceph-releases/ALL/centos/8/daemon/__DOCKERFILE_INSTALL__, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
This reverts commit aa644a5.
CentOS 8.3 has been released so we don't need the extra copr repository.
Backport: #1770
=> Revert "centos/8: add ktdreyer copr repository back" (bp #1770)

contrib/commit-rhcs.sh, contrib/compose-rhcs.sh
RHCS 5 tracks master at the moment. Remove the octopus references and update the contrib scripts for master.
We'll update to pacific when that branches.
=> contrib: rhcs is based on master

src/daemon/osd_scenarios/osd_directory.sh
Set the ceph owner/group on the OSD keyring created by the ceph-authtool
command.
Closes: #1775
=> [skip ci] daemon/osd_directory: fix OSD keyring permission

src/daemon/start_mon.sh
If the demo container is restarted then the warning option in the ceph
configuration file about the pool without redundancy will be set again
even if it is already present.
=> [skip ci] daemon/demo: avoid duplicate option on restart

src/daemon/start_mon.sh
If the demo container is restarted then the warning option in the ceph
configuration file about the pool without redundancy will be set again
even if it is already present.
Backport: #1780
(cherry picked from commit 2bb051a8e19c7fa9015280fa36ff3afb64438e5c)
=> [skip ci] daemon/demo: avoid duplicate option on restart (bp #1780)

tests/tox.sh
When running pytest after the deployment then the cluster status could
be in WARNING due to global recovery event.
```console
STDOUT:
cluster:
id:     212ac54d-bc36-44de-a483-1f33b1b70b2d
health: HEALTH_WARN
1 osds down
services:
mon: 1 daemons, quorum mon0 (age 2m)
mgr: mon0(active, since 2m)
osd: 8 osds: 7 up (since 2s), 8 in (since 66s)
data:
pools:   3 pools, 289 pgs
objects: 0 objects, 0 B
usage:   26 GiB used, 199 GiB / 225 GiB avail
pgs:     26.644% pgs unknown
58.131% pgs not active
147 peering
77  unknown
38  active+clean
21  activating
6   stale+active+clean
progress:
Global Recovery Event (25s)
[=...........................] (remaining: 6m)
```
Increasing the pytest rerun delay to let more time to the cluster to
be fully recovered.
Signed-off-by: Dimitri Savineau …
=> tests/tox: increase pytest rerun delay

tests/tox.sh
When running pytest after the deployment then the cluster status could
be in WARNING due to global recovery event.
-----------------------------------------------------------
STDOUT:
cluster:
id:     212ac54d-bc36-44de-a483-1f33b1b70b2d
health: HEALTH_WARN
1 osds down
services:
mon: 1 daemons, quorum mon0 (age 2m)
mgr: mon0(active, since 2m)
osd: 8 osds: 7 up (since 2s), 8 in (since 66s)
data:
pools:   3 pools, 289 pgs
objects: 0 objects, 0 B
usage:   26 GiB used, 199 GiB / 225 GiB avail
pgs:     26.644% pgs unknown
58.131% pgs not active
147 peering
77  unknown
38  active+clean
21  activating
6   stale+active+clean
progress:
Global Recovery Event (25s)
[=...........................] (remaining: 6m)
-----------------------------------------------------------
Increasing the pytest rerun …
=> tests/tox: increase pytest rerun delay (bp #bp1787)

ceph-releases/ALL/ubi8/daemon-base/__CEPHFS_PACKAGES__, ceph-releases/nautilus/daemon-base/__CEPHFS_PACKAGES__, ceph-releases/octopus/daemon-base/__CEPHFS_PACKAGES__, src/daemon-base/__CEPHFS_PACKAGES__, src/daemon-base/__CEPH_BASE_PACKAGES__
On master/devel for Pacific we would like to have the cephfs-mirror
package to start the implementation in Rook.
This package isn't installed for RHCS 5 even if it's based on Pacific.
=> daemon-base: add support for cephfs-mirror package

tests/tox.sh
When running pytest after the deployment then the cluster status could
be in WARNING due to global recovery event.
-----------------------------------------------------------
STDOUT:
cluster:
id:     212ac54d-bc36-44de-a483-1f33b1b70b2d
health: HEALTH_WARN
1 osds down
services:
mon: 1 daemons, quorum mon0 (age 2m)
mgr: mon0(active, since 2m)
osd: 8 osds: 7 up (since 2s), 8 in (since 66s)
data:
pools:   3 pools, 289 pgs
objects: 0 objects, 0 B
usage:   26 GiB used, 199 GiB / 225 GiB avail
pgs:     26.644% pgs unknown
58.131% pgs not active
147 peering
77  unknown
38  active+clean
21  activating
6   stale+active+clean
progress:
Global Recovery Event (25s)
[=...........................] (remaining: 6m)
-----------------------------------------------------------
Increasing the pytest rerun …
=> tests/tox: increase pytest rerun delay (bp #1787)

tests/tox.sh
The fetch_directory variable doesn't exist anymore in ceph-ansible.
=> test/tox: remove fetch_directory ansible variable

tests/tox.sh
The fetch_directory variable doesn't exist anymore in ceph-ansible.
Backport: #1790
(cherry picked from commit a8fc13d0ad373072fa592d7a6af47d736a879dbf)
=> test/tox: remove fetch_directory ansible variable (bp #1790)

Makefile, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Since pacific branch has been created then we can split pacific and
master.
There's still no pacific build on download.ceph.com so this target is
still using shaman/chacra bits for now. Same thing for nfs-ganesha.
However we can use the stable ceph-iscsi 3 repository instead of
shaman/chacra.
=> release: add pacific target

contrib/build-push-ceph-container-imgs.sh
Until we get 16.1.x build for both x86_64 and aarch64 on download.ceph.com
then we can only build pacific on x86_64 (bits from shaman/chacra).
=> [skip ci] contrib: build pacific devel on x86_64

src/daemon/osd_scenarios/osd_disk_activate.sh, src/daemon/osd_scenarios/osd_volume_activate.sh
There's no need to have complexity to get the path of the current OSD.
By the way, at the moment this complexity leads to incorrect behavior:
```
-bash-4.2# docker exec ceph-osd-2 findmnt --nofsroot --noheadings --output SOURCE --submounts --target /var/lib/ceph/osd/
/dev/mapper/atomicos-root
/dev/sdb1
/dev/sda1
-bash-4.2# docker exec ceph-osd-2 df --output=target | grep '/var/lib/ceph/osd/'
/var/lib/ceph/osd/ceph-0
/var/lib/ceph/osd/ceph-2
-bash-4.2#
```
In the first method used in recent branches, it means we might try to umount
the root partition.
In the second method used in older branches we try to umount something
messed up:
```
2021-01-14 00:17:08  /opt/ceph-container/bin/entrypoint.sh: osd_disk_activate: Unmounting /var/lib/ceph/osd/ceph-0
/var/lib/ceph/osd/ceph-2
...
umount: …
```
=> osd_activate: fix osd umount on container stop

src/daemon/osd_scenarios/osd_disk_activate.sh, src/daemon/osd_scenarios/osd_volume_activate.sh
There's no need to have complexity to get the path of the current OSD.
By the way, at the moment this complexity leads to incorrect behavior:
```
-bash-4.2# docker exec ceph-osd-2 findmnt --nofsroot --noheadings --output SOURCE --submounts --target /var/lib/ceph/osd/
/dev/mapper/atomicos-root
/dev/sdb1
/dev/sda1
-bash-4.2# docker exec ceph-osd-2 df --output=target | grep '/var/lib/ceph/osd/'
/var/lib/ceph/osd/ceph-0
/var/lib/ceph/osd/ceph-2
-bash-4.2#
```
In the first method used in recent branches, it means we might try to umount
the root partition.
In the second method used in older branches we try to umount something
messed up:
```
2021-01-14 00:17:08  /opt/ceph-container/bin/entrypoint.sh: osd_disk_activate: Unmounting /var/lib/ceph/osd/ceph-0
/var/lib/ceph/osd/ceph-2
...
umount: …
```
=> osd_activate: fix osd umount on container stop (bp #1783)

contrib/commit-rhcs.sh, contrib/compose-rhcs.sh
Since pacific branch has been created then RHCS 5 doesn't track master
anymore but the pacific release.
=> [skip ci] contrib: RHCS 5 is based on pacific

ceph-releases/ALL/ubi8/daemon-base/__DOCKERFILE_INSTALL__
By default, dnf tries to install weak dependencies which leads to install
packages like podman or chrony in the container image.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1921807
=> [skip ci] ubi8: disable weak dependencies

contrib/build-push-ceph-container-imgs.sh
This was removed in ef48a80b so let's add it back.
=> [skip ci] contrib: add back luminous on centos 7

.github/workflows/container.yml, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, contrib/build-push-ceph-container-imgs-arm64.sh, src/daemon/demo.sh, tests/tox.sh, travis-builds/validate_demo_cluster.sh
Because shaman is now providing aarch64 build then there's no guarantee
that the latest centos/8 build query on shaman is x86_64.
This also enable master/pacific aarch64 builds.
=> daemon-base/centos: specify arch on shaman url

src/daemon/demo.sh
5 seconds is often not enough and makes the script fail because it's not
ready. Let's increase this timeout.
=> demo: increase timeout in bootstrap_demo_user()

contrib/build-push-ceph-container-imgs.sh
There's a reasonable chance that podman 2 fixes the issue in
https://github.com/containers/libpod/issues/5306 (the bug
seems to imply that 1.9.1 has the fix), and the kubic
repo causes problems because of podman-catatonit, sometimes
called just "catatonit", and its dependencies on and of podman-docker.
Signed-off-by: Dan Mick <dmick@redhat.com>
Resolves #
Checklist:
=> contrib/build-push-ceph-container-imgs.sh: undo kubic repo hack

travis-builds/validate_demo_cluster.sh
The mds daemon status output in the ceph cluster status has changed.
Before:
```console
mds: cephfs:1 {0=demo=up:active}
```
After:
```console
mds: 1/1 daemons up
```
=> [skip ci] demo/validation: fix mds cluster status check

ceph-releases/ALL/centos/8/daemon-base/__GPERFTOOLS_LIBS__, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/ALL/centos/daemon-base/__GPERFTOOLS_LIBS__, tests/tox.sh
This commit makes any build against el8 fetch gperftools from
epel-testing which provides 2.7 instead of epel which provides 2.8.
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1933792
Related Tracker: https://tracker.ceph.com/issues/49618#note-5
=> gperftools: install from epel-testing for ceph octopus

ceph-releases/ALL/centos/8/daemon-base/__GPERFTOOLS_LIBS__, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/ALL/centos/daemon-base/__GPERFTOOLS_LIBS__, tests/tox.sh
This commit makes any build against el8 fetch gperftools from
epel-testing which provides 2.7 instead of epel which provides 2.8.
Backport: #1817 
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1933792
Related Tracker: https://tracker.ceph.com/issues/49618#note-5
=> gperftools: install from epel-testing for ceph (bp #1817)

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
the mgr failure prediction module needs this, and there is no package
packaged for CentOS8 or EPEL8.
see also https://bugzilla.redhat.com/show_bug.cgi?id=1844636
Signed-off-by: Kefu Chai <kchai@redhat.com>
Resolves #
Checklist:
=> daemon-base: add copr repo for python3-scikit-learn packages

ceph-releases/ALL/centos-arm64/8/daemon-base/__GPERFTOOLS_LIBS__, ceph-releases/ALL/centos-arm64/daemon-base/__GPERFTOOLS_LIBS__
The CentOS 8 arm64 configuration wasn't updated with 4c4b735.
=> centos-arm64: fix gperftools libs file

ceph-releases/ALL/centos-arm64/8/daemon-base/__GPERFTOOLS_LIBS__, ceph-releases/ALL/centos-arm64/daemon-base/__GPERFTOOLS_LIBS__
The CentOS 8 arm64 configuration wasn't updated with 4c4b735.
Backport: #1823
(cherry picked from commit e2d54e961ffedf75484f4922f255352477e30cb4)
=> [skip ci] centos-arm64: fix gperftools libs file (bp #1823)

ceph-releases/ALL/centos-arm64/8/daemon-base/__GPERFTOOLS_LIBS__, ceph-releases/ALL/centos-arm64/daemon-base/__GPERFTOOLS_LIBS__
The CentOS 8 arm64 configuration wasn't updated with 4c4b735.
Backport: #1823
(cherry picked from commit e2d54e961ffedf75484f4922f255352477e30cb4)
=> [skip ci] centos-arm64: fix gperftools libs file (bp #1823)

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
* add copr repo for python3-scikit-learn packages
* install python3-scikit-learn package
the mgr failure prediction module needs this, and there is no package
packaged for CentOS8 or EPEL8.
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1844636
Backport: #1821
Signed-off-by: Kefu Chai <kchai@redhat.com>
(cherry picked from commit 9a3e9fd32682b07b7d846c4636734e368ff6b1b4)
=> daemon-base: install python3-scikit-learn on el8

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
We can now use stable nfs-ganesha release (3.5) from download.ceph.com
instead of CentOS buildlogs.
=> centos/pacific: use ganesha from download.ceph.com

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
We can now use stable nfs-ganesha release (3.5) from download.ceph.com
instead of CentOS buildlogs.
Backport: #1829
(cherry picked from commit b1a29c16a2c2582c11f1624d365064bb7860c738)
=> centos/pacific: use ganesha from download.ceph.com (bp #1829)

ceph-releases/ALL/centos-arm64/8/daemon-base/__GPERFTOOLS_LIBS__, ceph-releases/ALL/centos-arm64/daemon-base/__GPERFTOOLS_LIBS__, ceph-releases/ALL/centos/8/daemon-base/__GPERFTOOLS_LIBS__, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/ALL/centos/daemon-base/__GPERFTOOLS_LIBS__
This reverts commits 4c4b735e251847c21869414e9d5a843ef1e7215f and
e2d54e961ffedf75484f4922f255352477e30cb4 since gperftools has been
downgrade to 2.7 in epel 8 stable.
=> Revert "gperftools: install from epel-testing"

ceph-releases/ALL/centos-arm64/8/daemon-base/__GPERFTOOLS_LIBS__, ceph-releases/ALL/centos-arm64/daemon-base/__GPERFTOOLS_LIBS__, ceph-releases/ALL/centos/8/daemon-base/__GPERFTOOLS_LIBS__, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/ALL/centos/daemon-base/__GPERFTOOLS_LIBS__
This reverts commits 4c4b735e251847c21869414e9d5a843ef1e7215f and
e2d54e961ffedf75484f4922f255352477e30cb4 since gperftools has been
downgrade to 2.7 in epel 8 stable.
Backport: #1831
(cherry picked from commit 86da1a47133ecf7a6d66d318bc637c7ed1f0073a)
=> Revert "gperftools: install from epel-testing" (bp #1831)

contrib/build-push-ceph-container-imgs.sh, contrib/ceph-build-config.sh
To be honest, I don't know why this is needed.  Not sure what changed on the builders or in docker that makes the service sometimes masked.
=> [skip ci] contrib: Unmask docker service if needed

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
This is the same behaviour than the ceph build present on shaman but
for tcmu-runner this time.
=> [skip ci] daemon-base/centos: specify arch for tcmu url

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
This is the same behaviour than the ceph build present on shaman but
for tcmu-runner this time.
Backport: #1839
(cherry picked from commit f05750cd1ab4d7c5a5d4643e8110ddd8677281f6)
=> [skip ci] daemon-base/centos: specify arch for tcmu url (bp #1839)

src/daemon-base/__CEPH_IMMUTABLE_OBJECT_CACHE_PACKAGE__
The CEPH_POINT_RELEASE environment variable was missing from the
ceph-immutable-object-cache package name.
=> [skip ci] daemon-base: add missing env var to immutable pkg

ceph-releases/ALL/centos-arm64/8/daemon-base/__SCIKIT_LEARN__, ceph-releases/ALL/centos-arm64/daemon-base/__SCIKIT_LEARN__, ceph-releases/ALL/centos/8/daemon-base/__SCIKIT_LEARN__, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, src/daemon-base/__CEPH_BASE_PACKAGES__
This will avoid to have a dedicated dnf install command just for this
package instead of installing it with the other packages.
Backport: #1845
(cherry picked from commit 50c62733fe9962908c16f14743ac0d9988ccdf06)
=> [skip ci] daemon-base: move scikit learn to the main install (bp #1845)

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Instead of doing two curl calls on shaman for retrieving the tcmu-runner
repository information then we can do it in a single one via the /latest
endpoint and the arch parameter (instead of the search API).
This also makes sure we're using the -o curl option to store the repository
information on disk instead of using output redirection.
=> [skip ci] daemon-base/centos: simplify tcmu shaman repo code

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Instead of doing two curl calls on shaman for retrieving the tcmu-runner
repository information then we can do it in a single one via the /latest
endpoint and the arch parameter (instead of the search API).
This also makes sure we're using the -o curl option to store the repository
information on disk instead of using output redirection.
Backport: #1851
(cherry picked from commit 8850c371871f2cb4f006c65bc17c343d367b9a4e)
=> [skip ci] daemon-base/centos: simplify tcmu shaman repo code (bp #1851)

.github/workflows/container.yml
The github workflow infrastructure doesn't offer arm64 nodes but we
can use qemu-user-static [1] to build arm64 container image on x86_64
host.
[1] https://github.com/multiarch/qemu-user-static
=> [skip ci] workflow: add arm64 container build

.github/workflows/container.yml
The github workflow infrastructure doesn't offer arm64 nodes but we
can use qemu-user-static [1] to build arm64 container image on x86_64
host.
[1] https://github.com/multiarch/qemu-user-static
Backport: #1852
(cherry picked from commit f4561236c60ec62b58780795237e8822248096ff)
=> [skip ci] workflow: add arm64 container build (bp #1852)

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
There's no need to use BASEOS_REPO environment variable in the docker install
file because the value should always be "centos".
This is actually breaking the shaman URLs when using a custom base container
image value via BASEOS_REPO.
A good exemple is when trying to build arm64 container image on a x86_64
host which requires to se BASEOS_REPO to a specific namespace (arm64v8/centos)
instead of using the default implicit architecture detection (via the host
architecture).
Note that we were already using the "centos" value for other shaman URLs like
ceph core or ceph-iscsi.
=> [skip ci] centos/daemon-base: do not use BASEOS_REPO env var

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
There's no need to use BASEOS_REPO environment variable in the docker install
file because the value should always be "centos".
This is actually breaking the shaman URLs when using a custom base container
image value via BASEOS_REPO.
A good exemple is when trying to build arm64 container image on a x86_64
host which requires to se BASEOS_REPO to a specific namespace (arm64v8/centos)
instead of using the default implicit architecture detection (via the host
architecture).
Note that we were already using the "centos" value for other shaman URLs like
ceph core or ceph-iscsi.
Backport: #1859
(cherry picked from commit bb23ba9ab6490a5caca70892f2b771e34b549455)
=> [skip ci] centos/daemon-base: do not use BASEOS_REPO env var (bp #1859)

ceph-releases/ALL/centos-arm64/8/daemon-base/__ISCSI_PACKAGES__
Since we have tcmu-runner package available on shaman for arm64 which was
the last piece missing to be able to install ceph-iscsi, then we can
enable the ceph-iscsi installation on the arm64 architecture as well.
This is done only on CentOS 8 distribution.
=> [skip ci] centos-arm64/8: enable ceph-iscsi packages

ceph-releases/ALL/centos-arm64/8/daemon-base/__ISCSI_PACKAGES__
Since we have tcmu-runner package available on shaman for arm64 which was
the last piece missing to be able to install ceph-iscsi, then we can
enable the ceph-iscsi installation on the arm64 architecture as well.
This is done only on CentOS 8 distribution.
Backport: #1846
(cherry picked from commit 4950db359b415dc01834482e458762f9aa1e82f9)
=> [skip ci] centos-arm64/8: enable ceph-iscsi packages (bp #1846)

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
When using the nfs-ganshe repository from download.ceph.com we can enable
the gpgcheck parameter because we are already importing the gpg key.
This is only disable when using the repository from CentOS buildlogs.
=> [skip ci] centos/daemon-base: enable gpgcheck on nfs-ganesha

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
When using the nfs-ganshe repository from download.ceph.com we can enable
the gpgcheck parameter because we are already importing the gpg key.
This is only disable when using the repository from CentOS buildlogs.
Backport: #1860
(cherry picked from commit ac0c05a841b12c060665de9b375e7ce499529f20)
=> [skip ci] centos/daemon-base: enable gpgcheck on nfs-ganesha (bp #1860)

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, contrib/ceph-build-config.sh
This commit adds the Ceph Pacific release to the ceph/ceph registry
namespace.
=> [skip ci] contrib: add pacific to ceph/ceph namespace

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
We now have packages for the pacific release on download.ceph.com so
we can stop to use shaman (except for the devel build).
(cherry picked from commit 20cb635043d86d971f028e2bf2824446440b5557)
=> [skip ci] centos/pacific: packages from download.ceph.com

contrib/build-push-ceph-container-imgs.sh
Fixes: https://github.com/ceph/ceph-container/issues/1869
=> [skip ci] contrib/build-push-ceph-container-imgs.sh: delete trailing manifests

src/daemon/start_mon.sh
This set auth_allow_insecure_global_id_reclaim to false otherwise the
ceph status won't be OK:
```console
health: HEALTH_WARN
mon is allowing insecure global_id reclaim
```
=> [skip ci] demo: stop allowing insecure reconnections

ceph-releases/ALL/ubi8/daemon-base/__CEPHFS_PACKAGES__
The cephfs-mirror package is now available in RHCS 5.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1951100
=> [skip ci] ubi8: enable cephfs-mirror package

ceph-releases/ALL/ubi8/daemon-base/__CEPHFS_PACKAGES__
The cephfs-mirror package is now available in RHCS 5.
Backport: #1880 
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1951100
=> [skip ci] ubi8: enable cephfs-mirror package (bp #1880)

Makefile
We don't need those flavors anymore.
=> [skip ci] Makefile: remove unused flavors

contrib/build-push-ceph-container-imgs.sh
```
dgalloway@smithi056:~$ sudo su - jenkins-build
$ sudo systemctl start docker
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
$ sudo systemctl restart docker
$ sudo systemctl status docker
* docker.service - Docker Application Container Engine
Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
Active: active (running) since Mon 2021-04-19 23:04:51 UTC; 6s ago
Docs: https://docs.docker.com
Main PID: 1892 (dockerd)
Tasks: 25
CGroup: /system.slice/docker.service
`-1892 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
```
=> contrib/build-push-ceph-container-imgs.sh: restart if start fails

contrib/ceph-build-config.sh
58d7bdd only managed the change in the script for building the
daemon-base/daemon container images but not the ceph one.
=> [skip ci] contrib: restart docker if start fails

ceph-releases/ALL/centos/8/daemon/__DOCKERFILE_INSTALL__, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/ALL/centos/daemon/__DOCKERFILE_INSTALL__, ceph-releases/ALL/ubi8/daemon-base/__DOCKERFILE_INSTALL__
The weak dependencies were already disable for ubi8 so we can do this
for CentOS too (even if we don't have the same weak deps during the
ceph packages between upstream and downstream ceph install).
This also disables the weak deps during the container image update and
daemon package install step.
On the daemon-base image this reduces the container image size by 30MB
uncompressed.
Closes: #1874
=> centos/ubi: disable weak dependencies

ceph-releases/ALL/centos/8/daemon/__DOCKERFILE_INSTALL__, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/ALL/centos/daemon/__DOCKERFILE_INSTALL__, ceph-releases/ALL/ubi8/daemon-base/__DOCKERFILE_INSTALL__
The weak dependencies were already disable for ubi8 so we can do this
for CentOS too (even if we don't have the same weak deps during the
ceph packages between upstream and downstream ceph install).
This also disables the weak deps during the container image update and
daemon package install step.
On the daemon-base image this reduces the container image size by 30MB
uncompressed.
Backport: #1890
Closes: #1874
(cherry picked from commit 6c8af8169a3b4a49abf72e72eb897df5ae3d1e9e)
=> [skip ci] centos/ubi: disable weak dependencies (bp #1890)

src/daemon/confd/templates/ceph.conf.tmpl
The extra spaces before the mon.xxx section aren't needed and generate
a config file error starting the Octopus release.
```console
global_init: error reading config file. parse error: expected '<eoi>' in line 12 at position 1
```
Closes: #1751
=> [skip ci] daemon: fix confd ceph template

src/daemon/confd/templates/ceph.conf.tmpl
The extra spaces before the mon.xxx section aren't needed and generate
a config file error starting the Octopus release.
global_init: error reading config file. parse error: expected '<eoi>'
in line 12 at position 1
Backport: #1895
Closes: #1751
(cherry picked from commit 4138a4f2ff814bda0c1839a71ec858821ec9b809)
=> [skip ci] daemon: fix confd ceph template (bp #1895)

src/daemon/start_mon.sh
When bootstrapping a new monitor using ipv6 address with v2+v1 protocol
this command fails because of the brackets wrapping the ipv6 address:
```
++/opt/ceph-container/bin/start_mon.sh:172: start_mon(): ceph-conf -c /etc/ceph/ceph.conf 'mon host'
++/opt/ceph-container/bin/start_mon.sh:172: start_mon(): tr , '\n'
++/opt/ceph-container/bin/start_mon.sh:172: start_mon(): grep -c '[2620:52:0:880:225:90ff:fefc:1a98]'
+/opt/ceph-container/bin/start_mon.sh:172: start_mon(): v2v1=10
+/opt/ceph-container/bin/start_mon.sh:174: start_mon(): '[' 10 -eq 2 ']'
+/opt/ceph-container/bin/start_mon.sh:178: start_mon(): timeout 7 ceph --cluster ceph mon add magna115 '[2620:52:0:880:225:90ff:fefc:1a98]:3300'
```
eg:
```
[root@magna115 ~]# ceph-conf -c /etc/ceph/ceph.conf 'mon host' | tr ',' '\n' | tr -d '[]' …
```
=> start_mon: fix mon addition with ipv6

.github/workflows/rhcs.yml, travis-builds/validate_demo_cluster.sh
This adds a github workflow for testing RHCS compose.
Backport: #1907 
=> [skip ci] workflow: add rhcs compose task (bp #1907)

contrib/ceph-build-config.sh
5b5e7f9 changed the source registry for the CentOS base container images.
Unfortunately the CentOS 7 image on quay.io/centos/centos registry is
amd64 only and not a multiarch manifest like docker.io/centos (with five
different architectures).
This sucks and as a solution we will stick to docker.io registry for the
CentOS 7 container image.
=> contrib: fix centos 7 origin

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Add copr repo for python3-ssh package.
This package is required by ceph-mgr-cephadm as a replacement of remoto and
execnet.
=> [skip ci] centos: add el8 copr repo for python3-asyncssh

.github/workflows/container.yml
In case of ceph monitor failure but the container is still up then
the ceph command will timeout only after 300s.
Adding --connect-timeout parameter to have the job in failure earlier.
=> [skip ci] workflow: add timeout on ceph command

.github/workflows/container.yml
In case of ceph monitor failure but the container is still up then
the ceph command will timeout only after 300s.
Adding --connect-timeout parameter to have the job in failure earlier.
Backport: #1916
(cherry picked from commit 4d96298d43ed77d80efdb44c23a181c2021ebba7)
=> [skip ci] workflow: add timeout on ceph command (bp #1916)

Makefile, contrib/build-push-ceph-container-imgs.sh, contrib/ceph-build-config.sh
Nautilus 14.2.22 was the latest release and likely the last one.
=> [skip ci] contrib: drop nautilus release

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
ceph is built with libarrow and libparquet.
[1] https://arrow.apache.org/
Closes: #1928 
=> [skip ci] centos: add Apache Arrow repository

contrib/ceph-build-config.sh
The 0.8.0 release is 3 years old and since we switched to the quay.io
registry I've seen some error in the CI on manifest-tool (which I wasn't
able to reproduce).
In any case, this updates manifest-tool to the latest stable release.
=> contrib: update manifest-tool to 1.0.3

README.md
Since we're now pushing the ceph/ceph container images to the quay.io
registry then we need to update the documentation.
=> [skip ci] README: update documentation about quay.io

contrib/ceph-build-config.sh
This reverts commit 7cc3401351dd2762312f36cefb2e47451c0695f0.
Because we don't built the Nautilus container image anymore and all
other Ceph releases are based on CentOS 8 then we can revert this change.
=> Revert "contrib: fix centos 7 origin"

README.md, contrib/build-push-ceph-container-imgs-arm64.sh, contrib/build-push-ceph-container-imgs.sh
- registry namespace and repositories remain the same than docker.io [1][2]
- define the registry name explicitly for login, pull and push operations
- update registry API endpoint calls for quay registry [3] 
- update registry credentials variables to be more generic
- base container images (CentOS) are pulled from quay.io [4] 
[1] https://quay.io/repository/ceph/daemon-base
[2] https://quay.io/repository/ceph/daemon
[3] https://docs.quay.io/api/
[4] https://quay.io/repository/centos/centos
=> contrib: publish daemon-base/daemon to quay.io

contrib/commit-rhcs.sh
Since the upstream branch doesn't follow the downstream RHCS branch
then we can set it statically.
=> contrib/rhcs: set upstream branch explicitly

contrib/commit-rhcs.sh
Since the upstream branch doesn't follow the downstream RHCS branch
then we can set it statically.
Backport: #1940
(cherry picked from commit 568f79dd5172d6dac57729cd2b20a9c9b2fe565a)
=> [skip ci] contrib/rhcs: set upstream branch explicitly (bp #1940)

ceph-releases/ALL/ubi8/daemon/container.yaml
This reverts commit 59450b60137b2e9daaedac95ca750946fbeefc6e.
RH release engineering has created these repositories now, so it's safe to tell ODCS to use them.
=> Revert "ubi8: ignore absent pulp repositories"

ceph-releases/ALL/ubi8/daemon/container.yaml
This reverts commit 59450b60137b2e9daaedac95ca750946fbeefc6e.
RH release engineering has created these repositories now, so it's safe
to tell ODCS to use them.
Backport: #1945
(cherry picked from commit f9b91cde04cc6559c43d44f21f13f2212aa9dc7a)
=> [skip ci] Revert "ubi8: ignore absent pulp repositories"

contrib/build-push-ceph-container-imgs.sh, contrib/ceph-build-config.sh
Looks like the pagination parameter wasn't updated during the switch to
quay.io registry.
The `page_size` parameter doesn't exist with quay and we should use `limit`
instead.
The default `limit` value is 50 but let's keep it at 100 as before (it's
also the maximum value supported)
=> [skip ci] contrib: update quay api pagination parameter

ceph-releases/ALL/centos-arm64/8/daemon-base/__CEPH_MGR_PACKAGES__
This was missing from the CentOS arm64 configuration.
=> centos/arm: add python3-saml package

ceph-releases/ALL/centos-arm64/8/daemon-base/__CEPH_MGR_PACKAGES__
This was missing from the CentOS arm64 configuration.
Backport: #1953 
(cherry picked from commit 29640fb4116cc6c4c082488b1314c9b804e5a76b)
=> [skip ci][stable-6.0] centos/arm: add python3-saml package

ceph-releases/ALL/centos-arm64/8/daemon-base/__CEPH_MGR_PACKAGES__
This was missing from the CentOS arm64 configuration.
Backport: #1953
(cherry picked from commit 29640fb4116cc6c4c082488b1314c9b804e5a76b)
=> [skip ci][stable-5.0] centos/arm: add python3-saml package

contrib/build-push-ceph-container-imgs-arm64.sh, contrib/build-push-ceph-container-imgs.sh, contrib/ceph-build-config.sh
This is needed so the CI can build&push the images.
Co-authored-by: Dimitri Savineau <dsavinea@redhat.com>
=> build: update contrib scripts

contrib/build-push-ceph-container-imgs.sh
otherwise it tries to push nonexistent tags.
Resolves #
Checklist:
=> [skip ci] build: use BASEOS_TAG=stream8 in push_ceph_imgs

contrib/build-push-ceph-container-imgs-arm64.sh, contrib/build-push-ceph-container-imgs.sh
pushing point release images is currently failing because it tries to push
nonexistent tags.
=> [skip ci] contrib: fix tag names in contrib scripts

src/daemon-base/__CEPH_BASE_PACKAGES__
Since the recent change to stream8 as a base image to build ceph/ceph
containers various orchestration have started to fail since the udevadm
binary is not present in this image.
Adding systemd-udev which contains the binary.
Resolves https://github.com/ceph/ceph-container/issues/1984
Checklist:
=> src/daemon-base: re-add udevadm to the container image

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
This reverts commit ea259682ec905267bcc07fda4bd546044c26ceb5.
the new plan is to submodule the things we needed from this repo, so it's no longer necessary. and since centos 8 eol, it looks like apache may have removed the /centos/8/ repo
Resolves #
Checklist:
=> Revert "centos: add Apache Arrow repository"

contrib/build-push-ceph-container-imgs-arm64.sh, contrib/build-push-ceph-container-imgs.sh
The arm64 ceph/daemon container image isn't using the stream prefix
compared to the amd64 build.
This also updates the pull command to reflect that change required for
the manifest creation.
=> [skip ci] contrib: add missing stream prefix on daemon arm64

ceph-releases/ALL/centos/8/__DOCKERFILE_CLEAN_COMMON__, src/__DOCKERFILE_CLEAN_COMMON__, src/daemon/__DOCKERFILE_CLEAN_DAEMON__
This commit removes some attempts to make the final image smaller,
because they introduce other problems and have very little impact on the
overall image-size and just adds complexity.
Regarding `gzexe`:
gzexe is a tool that compresses binaries and wrap the
compressed data inside a shellscript. This will then automatically
decompress into a temporary file and execute that data whenever the
wrapper-shellscript is called.
ceph-container has been using this to compress `confd`, `kubectl`, and
`etcdctl` (and previously also `forego`). A critical problem here is that the
wrapper script cleans after itself with a subshell like this:
`(sleep 5; rm -fr "$gztmpdir") 2>/dev/null &`
The entrypoints/scenario-scrips sets traps on a list of signals, among
them SIGCHLD. So whenever the entrypoint has …
=> don't strip and gzexe binaries in CLEAN stage

src/daemon-base/__CEPH_BASE_PACKAGES__
Since we moved to stream 8, `procps-ng` and `hostname` packages
aren't present anymore. This adds them back in the image.
Having `ps` binary doesn't consume a lot of space and is
useful for devel/debug purposes.
(Although `hostname` is added back for ci/testing only, it doesn't hurt
to add it back too)
=> base: add packages

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, tests/tox.sh
The last build failed:
https://2.jenkins.ceph.com/job/ceph-container-build-push-imgs-devel-nightly/1003/consoleFull
With:
```
[91mcurl: (22) The requested URL returned error: 404 Not Found
[0m[91merror: skipping
https://chacra.ceph.com/r/ceph/octopus/d46a73d6d0a67a79558054a3a5a72cb561724974/centos/8/flavors/default//noarch/ceph-release-1-0.el8.noarch.rpm
- transfer failed
```
Looking at the repo page, we can see that
ceph-release-1-0.el8.noarch.rpm does not exist but
/ceph-release-1-1.el8.noarch.rpm is present.
I'm not sure why/where things started to change. Also previous
successful builds were pointing to 3.chacra.ceph.com and now simply
chacra.ceph.com, I'm not sure what the difference is.
See this successful build: Retrieving …
=> build: fix centos latest

ceph-releases/ALL/ubi8/daemon-base/content_sets.yml
Simplify the comment at the top of OSBS's `content_sets.yml`.
Remove the outdated Mojo link and link to the open-source OSBS documentation instead.
=> ubi8: update content_sets.yml header comments

ceph-releases/ALL/ubi8/daemon-base/content_sets.yml
These Pulp repos will not exist for RH Ceph Storage 6. We'll only keep the "tools" repository.
=> ubi8: remove mon and osd repos from content_sets.yml

src/__DOCKERFILE_POSTINSTALL_TWEAKS__
as of nfs-ganesha 4, the default path for the pidfile becomes
`/var/run/ganesha/ganesha.pid`
If this directory doesn't exist, nfs-ganesha doesn't start.
=> ganesha: ensure /var/run/ganesha is created

tests/tox.sh
deleting the `pause.pid` file fixes this issue.
=> tests: workaround 'Error: cannot re-exec process' error

ceph-releases/ALL/ubi9/daemon-base/__ISCSI_PACKAGES__
neither are supported on RHEL9
Signed-off-by: Justin Caratzas <jcaratza@redhat.com>
Resolves #
Checklist:
=> Remove ceph-iscsi and tcmu-runner from ubi9

ceph-releases/ALL/ubi9/daemon-base/container.yaml
We cannot build quincy on RHEL 9 on s390x yet due to a `CheckCxxAtomic` false positive, 
https://tracker.ceph.com/issues/56492
Revert this change when that issue is resolved and we can build quincy on s390x.
=> ubi9: exclude s390x

contrib/rhcs.md
Explain how to use ODCS to generate a one-off unsigned compose for testing.
Remove the reference to the rhceph-6 tools repo in prod pulp, because release engineering has not created that just yet.
=> contrib/rhcs.md: document using odcs

src/daemon-base/__GANESHA_PACKAGES__
In order for NFS-Ganesha to use System Security Services Daemon
(SSSD)[1], it requires the sssd-client packages to be installed. This
should add less than 500 kB to the image.
NFS-Ganesha can use SSSD for user ID management. SSSD supports LDAP,
Active Directory, and FreeIPA. Notably, SSSD is the primary tool used
to allow FreeIPA support.
[1] https://sssd.io
Signed-off-by: Blaine Gardner <blaine.gardner@redhat.com>
Resolves #
Checklist:
=> base: add sssd-client to NFS-Ganesha packages

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
If an arm64 build passes but the x86 one fails, shaman will return the arm64 repo for an x86 build.  This results in errors like:
```
No match for argument: nfs-ganesha
No match for argument: nfs-ganesha-ceph
No match for argument: nfs-ganesha-rgw
No match for argument: nfs-ganesha-rados-grace
No match for argument: nfs-ganesha-rados-urls
Error: Unable to find a match: nfs-ganesha nfs-ganesha-ceph nfs-ganesha-rgw nfs-ganesha-rados-grace nfs-ganesha-rados-urls
```
Resolves #
Checklist:
=> build: Request appropriate arch for nfs-ganesha repo

tests/tox.sh
Example where this would be needed:
```
docker rm -f 4fcd7c2012b6
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
time="2022-08-09T17:22:11Z" level=error msg="container \"4fcd7c2012b63e6bf9bffd9b7d490d12f1d557ba924e889192ec858821019d91\" does not exist"
Error: cannot remove container 4fcd7c2012b63e6bf9bffd9b7d490d12f1d557ba924e889192ec858821019d91 as it could not be stopped: timed out waiting for file /tmp/podman-run-1111/libpod/tmp/exits/4fcd7c2012b63e6bf9bffd9b7d490d12f1d557ba924e889192ec858821019d91: internal libpod error
docker rm -f 4fcd7c2012b6
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
ERRO[0000] Joining network namespace for container 4fcd7c2012b63e6bf9bffd9b7d490d12f1d557ba924e889192ec858821019d91: error …
```
=> tests: Retry rm'ing container

ceph-releases/ALL/ubi9/daemon-base/__DOCKERFILE_PREINSTALL__
The ubi9 base image deletes `libsystemd` from the `systemd` package. To fix this and reinstate the `libsystemd` shared library, we must reinstall the `systemd` package.
We can revert this change when the ubi9-minimal image does not ship a broken `systemd` package.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2114004
=> ubi9: reinstall systemd package

src/daemon-base/__CEPH_BASE_PACKAGES__, src/daemon-base/__CEPH_EXPORTER_PACKAGE__
This adds the `ceph-exporter` package to the Ceph container image.
=> daemon-base: add ceph-exporter package

tests/tox.sh
Jenkins adds spaces which makes the function exit 1.
Fixes:
```
++ docker ps -a -q
+ containers_to_remove=10eb12ab5f5e
+ '[' 10eb12ab5f5e ']'
+ ATTEMPTS=0
++ docker ps -a -q
++ wc -l
+ NUM_CONTAINERS=1
+ '[' 0 -eq 5 ']'
+ '[' 1 -eq 0 ']'
+ docker rm -f 10eb12ab5f5e
10eb12ab5f5ef303c62c71bfe3b04d7b33f42d50289f415b1665e1b2e72cce09
+ (( ATTEMPTS++ ))
ERROR: InvocationError for command /usr/bin/bash tests/tox.sh (exited with code 1)
```
=> tests: Use old increment method

ceph-releases/ALL/centos/8/daemon-base/__GANESHA_PACKAGES__, ceph-releases/ALL/ubi9/daemon-base/__GANESHA_PACKAGES__, src/daemon-base/__GANESHA_PACKAGES__
The latest Ceph builds don't contain sssd-client along with the
nfs-ganesha packages. The upstream builds are from CentOS 8, which has
overrides defined. Add sssd-client to these overrides as well
Also add the package to the RHEL-based ubi9.
Signed-off-by: Blaine Gardner <blaine.gardner@redhat.com>
Resolves #
Checklist:
=> base: add sssd-client to centos 8 and ubi9 images

Makefile, contrib/build-push-ceph-container-imgs.sh, contrib/ceph-build-config.sh
Octopus 15.2.17 was the latest release of this serie.
=> [skip ci] contrib: drop octopus release

ceph-releases/ALL/centos/8/daemon-base/__GANESHA_PACKAGES__, ceph-releases/ALL/ubi9/daemon-base/__GANESHA_PACKAGES__, src/daemon-base/__GANESHA_PACKAGES__
In order for NFS-Ganesha to use System Security Services Daemon
(SSSD)[1], it requires the sssd-client packages to be installed. This
should add less than 500 kB to the image.
NFS-Ganesha can use SSSD for user ID management. SSSD supports LDAP,
Active Directory, and FreeIPA. Notably, SSSD is the primary tool used
to allow FreeIPA support.
[1] https://sssd.io
Signed-off-by: Blaine Gardner <blaine.gardner@redhat.com>
(cherry picked from commit 8eed9ba52d99aaffd691bd1aa56fd3ac3bb267d5)
=> (stable-7.0) base: add sssd-client to NFS-Ganesha packages

ceph-releases/ALL/centos/8/daemon-base/__GANESHA_PACKAGES__, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/ALL/ubi8/daemon-base/__GANESHA_PACKAGES__, src/daemon-base/__GANESHA_PACKAGES__
In order for NFS-Ganesha to use System Security Services Daemon
(SSSD)[1], it requires the sssd-client packages to be installed. This
should add less than 500 kB to the image.
NFS-Ganesha can use SSSD for user ID management. SSSD supports LDAP,
Active Directory, and FreeIPA. Notably, SSSD is the primary tool used
to allow FreeIPA support.
[1] https://sssd.io
Signed-off-by: Blaine Gardner <blaine.gardner@redhat.com>
(cherry picked from commit 8eed9ba52d99aaffd691bd1aa56fd3ac3bb267d5)
=> (stable-6.0) base: add sssd-client to NFS-Ganesha packages

src/daemon-base/__CEPH_BASE_PACKAGES__
This adds the sg3_utils package.
=> base: add sg3_utils package

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
https://access.redhat.com/solutions/6962401
https://access.redhat.com/solutions/5884221
Passed: https://jenkins.ceph.com/job/ceph-dev-container-only/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos8,DIST=centos8,MACHINE_SIZE=gigantic/10/console
=> build: Prevent `error: db5 error` errors

ceph-releases/ALL/ubi9/daemon-base/__DOCKERFILE_PREINSTALL__
The ubi9-minimal image no longer has the systemd package. The container maintainer has added a check to the build process to make sure it will not reappear.
This reverts commit cb46d8bdeeaebf07f2fcfbfd53f8621334028c15.
=> Revert "ubi9: reinstall systemd package"

contrib/commit-rhcs.sh
the downstream image is based on el9, let's update this script.
=> contrib: update commit-rhcs.sh

ceph-releases/ALL/ubi9/daemon-base/container.yaml
We've settled the s390x build failure in https://tracker.ceph.com/issues/56492
This reverts commit cd3197c6921abcb2846691906cdc67cf46557213.
=> Revert "ubi9: exclude s390x"

ceph-releases/ALL/ubi9/daemon-base/gating.yaml
We were never able to get this gating test to work properly, and the CVP team is asking us to remove this now so we don't consume test resources.
=> remove gating.yaml

tox.ini
typical error:
`ceph_ansible-all_daemons: failed with bash is not allowed, use allowlist_externals to allow it`
Signed-off-by: Guillaume Abrioux <gabrioux@ibm.com>
=> tox: replace whitelist_externals with allowlist_externals

contrib/rhcs.md
Document the product `VERSION` argument that we implemented in 81fb72da67716266052ccbf80a257947903a37c5 . Users should not set `UBI_VERSION` outside this script.
=> contrib/rhcs.md: fix VERSION argument

ceph-releases/ALL/ubi8/__DOCKERFILE_PREINSTALL__
For ubi8, the product version number is 5, not 6.
=> ubi8: correct product version number

contrib/rhcs.md
We're using OSBS 2 now. Point at this version of the documentation.
=> contrib/rhcs.md: latest osbs link

src/daemon-base/__GANESHA_PACKAGES__
This adds the package dbus-daemon on el9 based OS images.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2174461
=> daemon-base: add dbus-daemon package (el9)

contrib/commit-rhcs.sh, contrib/common.sh, contrib/compose-rhcs.sh
This modifies commit-rhcs.sh and compose-rhcs.sh.
The composed dir path was hardcoded, it is now generated automatically depending on the value of the env var `VERSION`.
=> contrib: various fixes

contrib/common.sh
Print the list of valid versions when the user did not set one.
=> contrib: give example values in VERSION error message

maint-lib/makelib.mk
when we run the script `compose-rhcs.sh` it generates the following output:
```
$ VERSION=6 ./contrib/compose-rhcs.sh
...
DAEMON_BASE_IMAGE : ceph/daemon-base:fix-tags-quincy-ubi9/ubi-minimal-latest-x86_64
DAEMON_IMAGE      : ceph/daemon:fix-tags-quincy-ubi9/ubi-minimal-latest-x86_64
DEMO_IMAGE        : ceph/demo:fix-tags-quincy-ubi9/ubi-minimal-latest-x86_64
```
The tags generated are wrong.
This commits makes it generate better tags:
```
$ VERSION=6 ./contrib/compose-rhcs.sh
...
DAEMON_BASE_IMAGE : ceph/daemon-base:fix-tags-quincy-ubi9-ibm-latest-x86_64
DAEMON_IMAGE      : ceph/daemon:fix-tags-quincy-ubi9-ibm-latest-x86_64
DEMO_IMAGE        : ceph/demo:fix-tags-quincy-ubi9-ibm-latest-x86_64
```
=> compose-rhcs: fix a bug in generated tags

src/daemon-base/__CEPH_BASE_PACKAGES__
This adds the `cephfs-top` package in the daemon-base image.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2168965
=> daemon-base: add cephfs-top package

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/ALL/centos/daemon-base/__RADOSGW_PACKAGES__
This adds gcc, luarocks and lua-devel as they are required for the lua scripting feature support in RGW.
Fixes: #2116
=> daemon-base: add required pkgs for rgw lua scripting support

Makefile, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, contrib/build-push-ceph-container-imgs.sh, contrib/ceph-build-config.sh, contrib/common.sh, maint-lib/ceph_version.sh
This add the required changes in order to build Ceph Reef
container images.
=> branch reef

ceph-releases/ALL/ubi9-ibm/__DOCKERFILE_BRANDING__
Update container image list for IBM Storage Ceph 6.
Do not search-and-replace individual tags, because those could change.
=> ubi9-ibm: update container image list

ceph-releases/ALL/ubi8-ibm/daemon/gating.yaml, ceph-releases/ALL/ubi8-redhat/daemon/gating.yaml, ceph-releases/ALL/ubi8/gating.yaml, ceph-releases/ALL/ubi9-ibm/daemon-base/gating.yaml, ceph-releases/nautilus/ubi8/gating.yaml, ceph-releases/quincy/ubi9-redhat/daemon-base/gating.yaml, ceph-releases/reef/ubi9-redhat/daemon-base/gating.yaml
Remove `gating.yaml` from the tree. This is a follow-up to PR https://github.com/ceph/ceph-container/pull/2081
=> remove `gating.yaml`

ceph-releases/reef/ubi9-ibm/__DOCKERFILE_BRANDING__
We're going to ship this grafana container to a repository with a name that more accurately describes what this image is.
=> reef/ubi9: rename dashboard container to grafana

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
nfs-ganesha builds are broken because of [1].
let's pin to V5.3.2 for now. This is intended to be reverted when
[2] is merged.
[1] https://github.com/nfs-ganesha/nfs-ganesha/commit/da4245a9796cf5ca3e5eed8e4fc7b88a0c486e4e
[2] https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/557171
=> nfs-ganesha: work around build issue

src/daemon/common_functions.sh
=> get mem on cgroupsv2

ceph-releases/main/centos/__GANESHA_REPO__
This reverts the commit b86898a9623bd93398ee9e4059d08ecda7ab3a4c as it was a temporary work around after nfs-ganesha builds were broken.
=> revert commit b86898a9623bd93398ee9e4059d08ecda7ab3a4c

.github/workflows/container.yml, Makefile, contrib/build-push-ceph-container-imgs.sh, maint-lib/makelib.mk
Reverts the logic in https://github.com/ceph/ceph-container/commit/15054d97b0fcf406542d9c1ea6cc6897f45ad732 and https://github.com/ceph/ceph-container/commit/032e6221e4e6e92333be9cec067e569ea41270f9.
The addition of the tag repo was not reflected in quay.io, which means that we keep trying to push images to non-existent repos like https://quay.io/ceph/ceph/daemon-base that don't exist (https://quay.io/ceph/daemon-base is the true repo path).
We can revisit this change if we also change the logic in quay.io to match.
Checklist:
=> Revert tag repo logic

src/daemon-base/__GANESHA_PACKAGES__
The `rpcbind` package provides the `rpcinfo` tool which can be used to determine the health status of a running NFS-Ganesha server daemon.
Resolves #
Checklist:
=> add rpcbind to ganesha packages

.github/workflows/container.yml
Remove docker binary provided by docker-ce-cli as it is conflicting with "podman-docker" package resulting in failing ARM builds
Resolves #
Checklist:
=> chore: remove docker binary provided by docker-ce-cli

ceph-releases/reef/ubi9-ibm/__DOCKERFILE_BRANDING__
Add substitution for nvmeof container when branding IBM
=> ubi9-ibm: add nvmeof container

contrib/rhcs.md
We're developing RHCS 7 actively. Use the latest version number in the example commands.
=> contrib/rhcs.md: use "7" in example commands

ceph-releases/reef/ubi9-ibm/__DOCKERFILE_BRANDING__
Pull images from the beta repositories.
Revert this after we've shipped the beta.
=> ubi9-ibm: use beta container URLs

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
nfs-ganesha 5.7 is now being built and pushed to
https://shaman.ceph.com/builds/nfs-ganesha/, but we're still only using 5.5 builds.
5.7 should also have the new cmount_path feature so let's use that.
=> bump ganesha version in main containers to 5.7

ceph-releases/reef/ubi9-ibm/__DOCKERFILE_BRANDING__
We've shipped the 7.0 beta, so we can go back to the production URLs.
This reverts commit 2f6ed33db527fcc1e5d8a107b4ac2125ab0c8e41.
=> Revert "ubi9-ibm: use beta container URLs"

ceph-releases/quincy/ubi9-ibm/daemon-base/__ADD__
This will allow us to add new swid files downstream without needing to modify this file
=> use wildcards for swid file addition

ceph-releases/reef/ubi9-ibm/daemon-base/__ADD__
Add Swidtag ADD lines for IBM 7's Dockerfile. We just added this for IBM 6, but needed it in this location as well, since IBM 7 is based on reef
Resolves #
Checklist:
=> add swidtag files to IBM 7 Dockerfile

Makefile, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, contrib/build-ceph-base.sh, contrib/ceph-build-config.sh, maint-lib/makelib.mk
New $PRERELEASE variable pulls pkgs from prerelease dir on download.ceph.com (requires PRERELEASE_USERNAME/PRERELEASE_PASSWORD in env) Existing $FORCE_BUILD ignores images on quay.io and builds unconditionally Add ability to pass in desired container flavors
Hack ceph-release after installation, because ceph-release is built
during ceph build, and doesn't know what we need
Use tempfile to pass tagname back to parent
New $TEST_BUILD_ONLY avoids attempting to push image to quay.io Avoid logging into quay.io if PRERELEASE
Resolves #
Checklist:
=> Changes to allow staging/testing a container image

Makefile
Given that squid isn't available yet at download.ceph.com let's remove it from the FLAVORS list.
=> Makefile: do not build squid by default

ceph-releases/ALL/ubi9-ibm/daemon-base/__CEPH_NODE_PROXY_PACKAGE__
This adds the ceph-node-proxy RPM package to the ubi9-based IBM Ceph downstream image.
=> add ceph-node-proxy package to ubi9-based IBM images

contrib/build-ceph-base.sh
Typical failure seen in CI:
```
+ sudo chgrp jenkins-build /var/run/docker.sock
contrib/build-ceph-base.sh: line 20: PRERELEASE: unbound variable
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```
seems to have been introduced by 60f64185d6ee4a1620a4e475ec29fb91e0b44183
=> contrib: add default value to PRERELEASE variable

contrib/build-ceph-base.sh
Typical failure seen in CI:
```
contrib/build-ceph-base.sh: line 98: TEST_BUILD_ONLY: unbound variable
```
seems to have been introduced by 60f64185d6ee4a1620a4e475ec29fb91e0b44183
=> contrib: add default value to TEST_BUILD_ONLY variable

ceph-releases/ALL/ubi9-redhat/daemon-base/__CEPH_NODE_PROXY_PACKAGE__
There's no good reason for not including this package in RH Ceph container image too given that even though this feature is focusing on IBM specific hardware, it might be possible it works with more hardware (soon).
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2268114
=> ubi9-redhat: add ceph-node-proxy RPM

src/__DOCKERFILE_POSTINSTALL_TWEAKS__
A safety tweak to make sure we only edit whole lines that match; also handle commented-out lines.
Checklist:
(neither of those things necessary here, I think)
=> tweaks: use full-line commands to sed

src/daemon-base/__CEPHFS_PACKAGES__, src/daemon-base/__CEPH_BASE_PACKAGES__
Currently `cephfs-top` is a part of the ceph base packages. This is to move it to be alongside the rest of the cephfs packages. This will allow for changing cephfs packages (enabling and disabling as well) based on release/distribution/etc
=> Code Cleanup: Move cephfs-top package to CEPHFS package list

src/daemon-base/Dockerfile
The `pam` RPM (and `/etc/security` directory) is not present in the ubi9-minimal base images. For minimal images, `pam` is only available after we install ceph.
Edit the `/etc/security/limits.conf` file after ceph (and pam) is installed.
This fixes this error introduced in https://github.com/ceph/ceph-container/pull/2194:
```
/bin/sh: line 1: /etc/security/limits.conf: No such file or directory
```
=> edit /etc/security/limits.conf after installing ceph

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
Because of a new dependency in spdk, grpc and protobuf tools are now required for the build, but not all the pieces exist in epel8. ktdreyer constructed a copr to hold the packages.  Dependencies (namely libprotobuf.so) are present in epel8.
Resolves #
Checklist:
=> Add the COPR for grpc for centos 8 daemon-base

ceph-releases/reef/ubi9-ibm/daemon-base/content_sets.yml, ceph-releases/reef/ubi9-redhat/daemon-base/content_sets.yml
For RH Ceph Storage 7.1 and IBM Storage Ceph 7.1, the `ceph-mgr-dashboard` package developers recently added a dependency on `python3-grpcio-tools`. This requires `libprotoc.so.25` from the `protobuf-compiler` package. `protobuf-compiler` is not in baseos or appstream. It is only in the codeready-builder repositories.
Related: [rhbz#2262984](https://bugzilla.redhat.com/show_bug.cgi?id=2262984)
=> content_sets.yml: add codeready-builder repositories

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
=> centos: make the grpc copr repo available by default

ceph-releases/reef/ubi9-ibm/__DOCKERFILE_BRANDING__
This reverts commit 26c185c6730a227e8afae88cfa8b303d6e5c470e.
We shipped the 7.1 Beta, so no longer need to ref the beta registry
Resolves #
Checklist:
=> Revert "ubi9-ibm: use beta container registry"

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, contrib/ceph-build-config.sh
prerelease now used for other projects (ceph-iscsi)
Checklist:
=> centos: add 'ceph' to prerelease paths on download.ceph.com

contrib/build-push-ceph-container-imgs-arm64.sh, contrib/build-push-ceph-container-imgs.sh
`*-bis*` image tags were designed for ceph-ansible. Let's drop these tags as we don't need them anymore.
=> common: drop `bis` image tags

contrib/build-push-ceph-container-imgs.sh
In response to c8 going EOL (https://lists.ceph.io/hyperkitty/list/dev@ceph.io/thread/H7I4Q4RAIT6UZQNPPZ5O3YB6AUXLLAFI/), we will need to have the orch and upgrade suites run with c9 containers instead of c8.
Resolves #
Checklist:
=> contrib: add extra identifier tag to c8 containers instead of c9

Makefile
As long as `ceph-release` rpm is not available at [1], quincy builds will fail.
Let's disable Quincy builds until this issue is addressed.
[1] https://download.ceph.com/rpm-quincy/el9//noarch/
=> Makefile: temporarily disable quincy builds

contrib/build-push-ceph-container-imgs.sh
This image was built for ceph-ansible, therefore, it is no longer needed to keep building this image.
=> do not build 'daemon' image anymore

contrib/build-push-ceph-container-imgs.sh
`stream8` is hardcoded, let's use the same logic as in `build_ceph_imgs()`.
Also, do not try to push `daemon` images as we no longer build them by default.
=> update push_ceph_imgs() function

ceph-releases/squid/ubi9-ibm/daemon-base/content_sets.yml, ceph-releases/squid/ubi9-redhat/daemon-base/content_sets.yml
We're adding support for aarch64 in a future release. Define the content sets for OSBS here.
=> ubi9: add aarch64 content sets for squid

Makefile
This reverts commit 851d67f16f03b5aa11c0c7f397d040bb0ad11e74 as `ceph-release` is now available at [1].
[1] https://download.ceph.com/rpm-quincy/el9/noarch/
=> Revert "Makefile: temporarily disable quincy builds"

contrib/build-push-ceph-container-imgs.sh
The daemon image is no longer built, so we should not try to create the corresponding manifest.
=> do not create manifest for daemon image

contrib/rhcs.md
This PR updates the `contrib/rhcs.md` document in a few ways.
* We're developing RHCS 8 actively. Use the latest version number in the example commands.
* Ceph now depends on `libprotoc.so.25`, which is in RHEL 9's codeready-builder repository. Add the codeready-builder repo to the local Yum configuration. (see https://github.com/ceph/ceph-container/pull/2201)
* Use the new Red Hat ODCS download server URL.
* Use HTTPS for rhsm-pulp URLs
=> contrib/rhcs.md: miscellaneous updates

.github/workflows/container.yml, Makefile, contrib/build-push-ceph-container-imgs.sh, contrib/ceph-build-config.sh
These changes will make the project build Ceph Squid by default in addition to quincy, reef and main
=> build squid release by default

ceph-releases/squid/ubi9-ibm/__DOCKERFILE_BRANDING__
cephadm in Squid has a new `DEFAULT_NGINX_IMAGE`.
For RH Ceph Storage 8.0, we use the nginx image in Red Hat's registry.
For IBM Storage Ceph 8.0, we will cross-ship this image to IBM's registry.
=> squid: add nginx container substitution for ibm

ceph-releases/squid/ubi9-ibm/__DOCKERFILE_BRANDING__
cephadm in Squid will have a new `DEFAULT_OAUTH2_PROXY` image.
Add the substitution statement for IBM Storage Ceph 8.0 so that the ibm-ceph container points at the appropriate image registry.
=> squid: add oauth2 container substitution for ibm

.github/workflows/container.yml, ceph-releases/ALL/centos-arm64/9/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/quincy/__GANESHA_PACKAGES__, ceph-releases/quincy/centos-arm64/__GANESHA_PACKAGES__, ceph-releases/reef/__GANESHA_PACKAGES__, ceph-releases/reef/centos-arm64/__GANESHA_PACKAGES__, ceph-releases/squid/centos/__GANESHA_PACKAGES__, src/daemon-base/__GANESHA_PACKAGES__
nfs-ganesha 6 introduced a new RPM `gmonitoring`.
This commit includes this new package into the Ceph Squid container image.
=> squid: add gmonitoring package

ceph-releases/squid/ubi9-ibm/daemon-base/container.yaml, ceph-releases/squid/ubi9-redhat/daemon-base/container.yaml
This reverts commit 55ad0f204a1d654ee565abf874aecad0cc209d0e.
We've resolved https://tracker.ceph.com/issues/66306 with https://github.com/ceph/ceph/pull/59558 .
=> ubi9: re-enable ppc64le for squid

contrib/ceph-build-config.sh
Deleted tags still show up in the REST API.  They have a non-null end_ts field.  Since those images can't be pulled, they should not be listed as currently available, and should not affect the search for the latest available tag when checking from the build.
Resolves #
Checklist:
=> ceph-build-config.sh: filter out deleted tags

ceph-releases/ALL/centos-arm64/9/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
This should unbreak the 17.2.8 build.
There is a more elegant solution to this overall issue here (https://github.com/ceph/ceph-container/pull/2169) but a lot has changed since then and paths, versions, etc. need to be verified.
Resolves #
Checklist:
=> quincy: Use nfs-ganesha 4

ceph-releases/squid/ubi9-ibm/daemon-base/content_sets.yml, ceph-releases/squid/ubi9-redhat/daemon-base/container.yaml, ceph-releases/squid/ubi9-redhat/daemon-base/content_sets.yml
The `rhceph-8-tools-for-rhel-9-aarch64-rpms` repository does not exist on `cdn.redhat.com`. ODCS will not use RPMs from that Pulp repo. Remove the references from `content_sets.yml`.
We will build the aarch64-enabled container at IBM, not Red Hat. We can disable aarch64 in the ubi9-redhat `container.yaml` file.
=> ubi9: disable aarch64 for Red Hat OSBS build and remove references to RH aarch64 CDN repository

ceph-releases/reef/ubi9-ibm/daemon-base/__ISCSI_PACKAGES__
Add the `ceph-iscsi` and `tcmu-runner` packages for the IBM Storage Ceph 7 (reef) product version. (EDIT: this is now `reef`-only, and we'll land `squid` in a separate PR after we ship IBM Storage Ceph 8.0.)
Fixes: #2251
=> add ceph-iscsi for ibm ceph 7 (reef)
