ceph/ceph-container

ceph-base/DockerfileFirefly
This image contains a default installation of Ceph.
This image will be re-used in the future to build Monitors, OSD, MDS and
RGW containers.
=> Add Docker base image

ceph-base/Dockerfile
ENV key=val syntax was introduced in docker 1.4+, this format fails with
`invalid ENV format` for docker < 1.4. Since the other dockerfiles in the
repo are supporting docker 1.0, it probably makes sense that we change
this to support older docker versions for now
Signed-off-by: Abhishek Lekshmanan <abhishek.lekshmanan@gmail.com>
=> ceph_base: allow older versions of docker to build

base/Dockerfile
The Dockerfile for base uses `wget`, which does not exist in the ubuntu:14.04 base.  This adds `wget`.
=> Add missing wget in base

radosgw/Dockerfile, radosgw/README.md, radosgw/entrypoint.sh
=> Add radosgw support

mds/Dockerfile, mon/Dockerfile, osd/Dockerfile, radosgw/Dockerfile
Put the `entrypoint.sh` script in the same place for all components:  `/entrypoint.sh`
=> Standardize the entrypoint script location

README.md
Fills out the root README a bit, to provide links and descriptions for the various components.
=> Add links to/descriptions of components

base/Dockerfile, base/README.md, base/entrypoint.sh
Hi,
Pushing few patches concerning mainly two things:
- There are still some references to old Docker repositories (ulexus/ or ceph/ceph-), that I replaced. I kept the ones for rbd in ulexus/ since they don't exist (yet ?) on ceph/.
- I added an helper script in ceph/base to be able to assist in the execution of this image directly (which can be conveniant to use ceph directly).
If you intend to create ceph/rados ceph/rbd ceph/rbd-* , please create a patch with:
grep -Rl "ulexus/" |grep -v ".git" |xargs sed -i 's^ulexus/^ceph/^g'
Thanks,
Bertrand
=> Exec /bin/bash by default

radosgw/Dockerfile, radosgw/README.md, radosgw/entrypoint.sh
Just noticed that ceph/rgw doesn't exist while ceph/radosgw does.
=> Fix ceph/radosgw name instead of ceph/rgw

README.md, config/Dockerfile, config/README.md, config/ceph-config.service, config/entrypoint.sh
This container allows to automatically bootstrap a cluster or distribute existing ceph config to new hosts. It makes use of etcd to store the inital configuration. It is especially cool when run on CoreOS and bootstrapping a cluster from nothing without manual intervention. It is compatible to the existing configuration mechanisms in the `ceph-mon` containers. 
If this fits in the vision of `ceph-docker` I would be happy to keep on helping to maintain this config mechanism.
I'm using this on my own ceph cluster as can be seen here: https://github.com/BugRoger/d26a/tree/master/units/ceph
=> Sync cluster bootstrap using etcd

base/Dockerfile, config/Dockerfile
1) Install version 2.0.4 of etcdctl to ceph/base
2) Remove etcdctl 0.4.6 from ceph/config
=> Install etcdctl to base; remove from config

base/Dockerfile
Moving away from Firefly and use Giant instead.
Fixes: #31 
=> Use the latest stable version of Ceph

mds/Dockerfile
=> libfuse2 and mds are now included in `ceph/base`

.gitignore, config/README.md, config/entrypoint.sh
This PR fixes the check for cases where the cluster configuration doesn't exist.  Before, the script would die if the etcd keys didn't exist.  This also changes the etcd location schema (but will use the old, if it is present) and allows the user to override it entirely (documented in `README.md`)
The new default key location is `/ceph/<cluster-name>/config`, which seems more natural to me, but input is welcome.
=> Fix config

rbd-volume/entrypoint.sh
When I try to to load the module from Docker container, an error occurs: modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/3.19.0/modules.dep.bin'. 
I think this is due to the lack of the kernel modules inside the container. Better to load rbd module outside Docker container.
=> rbd-volume: remove modprobe rbd

base/Dockerfile, demo/Dockerfile, demo/README.md, demo/entrypoint.sh
This commit introduces a container that runs all the Ceph service. This
is likely a step toward a common image that gets activated on demand.
Ultimately we want a single container in which we can activate which
service we want.
=> Add Docker AIO support

radosgw/Dockerfile
The radosgw package is part of ceph/base now, I should have fixed that with #61...
=> Remove radosgw package installation

config/ceph-config.service, mds/ceph-mds@a.service, mon/ceph-mon.service, osd/ceph-osd.service
This makes the EnvironmentFile includes from each of the sample unit files optional, meaning that the units will not fail if the file does not exist.
=> Make EnvironmentFile includes optional

mds/README.md, mds/entrypoint.sh
This PR adds support for _optional_ (and disabled by default) CephFS creation to the MDS.  
Even if CephFS creation is enabled, it should check, first, to make sure that the pools and filesystem don't already exist before creating them.
This should be non-breaking to existing installations.
=> Add support for cephfs and pool creation to MDS

daemon/entrypoint.sh
Add a differentiator to allow for common OSD execution (automatically figure out what to do).
Note:  better would be to do this, _then_ try ceph-disk, _then_ try manual bootstrapping.  That, however, would require a bit more rearrangement.
=> Example common OSD differentiator

daemon/entrypoint.sh
Allows the specification of the daemon to run by command-line argument instead of environment parameter.
=> Add argument parsing option for daemon selection

mon/entrypoint.sh
We can easily discover the hostname and populate the variable. If the
user wants something specific they can still override it.
ps: this is useful for k8s as well, if we set a specicif variable it
will be duplicated for every replication controller.
=> The monitor name should not be mandatory

daemon/README.md, daemon/entrypoint.sh, mon/README.md, mon/entrypoint.sh
We can't use `--net=host` with k8s. Thus if we manually set `MON_IP` as
an environement variable we will get duplicate content when using a
replication controller.
Introducing a new variable to auto detect the IP address of the
container.
This will generally work for every use case that don't want to use
`--net=host`.
=> Necessary changes for k8s to work

daemon/entrypoint.sh, osd/entrypoint.sh
I know I required manually-configured HOSTNAME originally, but I cannot think of a good reason for it.  That could be failing memory on my part, though.
Regardless, this PR makes the HOSTNAME for OSDs _default_ to the hostname of the container, as requested in Issue #113
=> Allow native hostname extraction for OSDs, by default

daemon/README.md, daemon/entrypoint.sh
In 'some' cases the operators might not want to run ceph-disk prepare
inside the container but might want it outside.
In this scenario, we only activate the OSD and don't prepare it.
Signed-off-by: leseb <seb@redhat.com>
=> Introduce a ceph_disk_activate

daemon/entrypoint.sh
kviator call was not wrapped in a ```KV_TYPE != none``` check
=> Hack-fix for #116

daemon/entrypoint.sh
Using a cluster name other than `ceph` is not working.
This PR is to fix a few lines of code I have spotted.
Unfortunately I can't set `--cluster` when I call `ceph-disk activate`:
````
+ ceph-disk -v activate /dev/sda1
INFO:ceph-disk:Running command: /sbin/blkid -p -s TYPE -ovalue -- /dev/sda1
INFO:ceph-disk:Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mount_options_xfs
2015-07-15 15:18:53.769457 7ffabab197c0 -1 did not load config file, using default settings.
INFO:ceph-disk:Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_mount_options_xfs
````
=> Be more ${CLUSTER} aware

daemon/entrypoint.sh
Running `entrypoint.sh mon` more than once results in `key is already set`.
I think it should be safe to rewrite this key as many times as needed.
This is what I get otherwise:
```
+ echo 'Adding Mon Host - core-1.cell-0.dc-1.demo.lan'
Adding Mon Host - core-1.cell-0.dc-1.demo.lan
+ kviator --kvstore=etcd --client=127.0.0.1:4001 cas ceph-config/ceph-cell-0/mon_host/core-1.cell-0.dc-1.demo.lan 172.16.0.81
root@core-1:/# kviator --kvstore=etcd --client=127.0.0.1:4001 cas ceph-config/ceph-cell-0/mon_host/core-1.cell-0.dc-1.demo.lan 172.16.0.81
key is already set
```
=> Adding Mon Host: key is already set

daemon/Dockerfile, daemon/README.md, daemon/config.kv.sh, daemon/config.static.sh, daemon/entrypoint.sh
The entrypoint script has gotten a bit ragged; this is an attempt to refactor it and make it a bit more flexible, with less repetition.
In particular, I have broken out the "static" and "kv" backends, which both adds separation and leaves open the option of others providing their own configuration backends. More thought and work is probably in order.
=> Refactor entrypoint script

daemon/entrypoint.sh
mds won't start for me with the following error:
2015-07-16 16:20:14.168684 7f95b6028700 0 librados: client.bootstrap-mds authentication error (1) Operation not permitted
Error connecting to cluster: PermissionError
when running
ceph --cluster ${CLUSTER} --name client.bootstrap-mds $KEYRING_OPT health
with $KEYRING_OPT set to
--keyring /etc/ceph/${CLUSTER}.client.admin.keyring
It appears that the admin keyring (/var/lib/ceph/bootstrap-mds/ceph.keyring) is not accepted, however, it does work with the bootstrap-mds keyring in /var/lib/ceph/bootstrap-mds/ceph.keyring
=> entrypoint.sh: mds auth error w/ admin keyring

daemon/entrypoint.sh
The OSD_DEVICE and OSD_JOURNAL need a space between them.
=> Need a space for ceps-disk prepare with a journal

daemon/entrypoint.sh
Remove double declaration and use the ${HOSTNAME} when required.
Signed-off-by: leseb <seb@redhat.com>
=> Do some cleanup

daemon/config.kv.sh
Use the initial `monmap` (from KV backend) instead of failing when the most recent `monmap` cannot be acquired.
=> Attempt to get the most recent monmap

examples/coreos/rbdmap/50-rbd.rules, examples/coreos/rbdmap/README.md, examples/coreos/rbdmap/ceph-rbdnamer, examples/coreos/rbdmap/rbdmap, examples/coreos/rbdmap/rbdmap.service
These scripts allow mounting rbd devices directly on the CoreOS host without requiring ceph-common.
Mounted filesystems may then be bind-mounted to docker containers without special privileges.
They may be copied directly or dropping via cloud-init or some other means.
=> Scripts to mount rbd devices directly CoreOS host without ceph-common

daemon/README.md, daemon/entrypoint.sh
This patch is to dynamically choose between `osd_directory` and `osd_activate`.
The currently implementation forces `osd_directory` always.
=> Default to osd_activate if OSD_DEVICE is provided

daemon/entrypoint.sh
Because right now if the directory does not exist the `if` statement returns `false` and it must return `true`.
=> Check if the directory does not exist or is empty

daemon/entrypoint.sh
This was missing for the `osd_directory` scenario.
=> Calculate the OSD weight

base/Dockerfile
Update etcdctl to version 2.2.0.
A merge of this PR (or any PR, actually) will also trigger a universal build, thus addressing issue #155 incidentally.
=> Version bump etcdctl: 2.2

daemon/entrypoint.sh
If OSD_GET_ADMIN_KEY=0 (default) nothing happens.
If OSD_GET_ADMIN_KEY=1 and a KV backend is present it gets the admin keyring and stores it in `/etc/ceph/${CLUSTER}.client.admin.keyring`
=> Added OSD_GET_ADMIN_KEY option

README.md, mds/README.md, mon/README.md, osd/README.md, radosgw/README.md
Add deprecation notices for:
- `ceph/osd`
- `ceph/mon`
- `ceph/mds`
- `ceph/radosgw`
in favor of `ceph/daemon`
This doesn't _remove_ them.  It simply updates the documentation to mark the discrete daemon containers as deprecated.
=> Add deprecation notices for discrete daemons

daemon/entrypoint.sh
I've got:
```
chown: cannot access '/var/lib/ceph/mds/mds-4ecf90c279f5/keyring': No such file or directory
```
When started MDS and I believe this is a typo that left after some previous paths refactoring.
=> Typo in MDS keyring path

daemon/entrypoint.sh
When you configure the clustername with a non-default value (default: ceph) the current ceph-mon mkfs creates a directory under /var/lib/ceph/mon/ceph-${hostname}. When the exec (line 141) for ceph-mon starts it looks inside the directory: /var/lib/ceph/mon/${CLUSTER}-${HOSTNAME}. Result is that the cluster will never start with a non-default clustername
The mkfs populates the directory correct when you use --mon-data.
=> mon-data added to ceph-mon mkfs.

daemon/entrypoint.sh
From entrypoint.sh, 'ceph-disk activate' call is made to
activate the disk and later start the ceph-osd process
as a daemon. Currently as systemd is not initalised
as part of base Centos image, this seizes to run and errors out.
Also, another call is made from entrypoint.sh after the
initialization to kick start ceph osd process in the
foreground for the ceph-osd docker container to continuously run.
As a result, there are two calls made to run ceph-osd and
this will result in the container erroring out and exiting.
This patch aims to fix the same.
Signed-off-by: Deepthi Dharwar <ddharwar@redhat.com>
=> Fix to run ceph/daemon osd on Centos.

daemon/entrypoint.sh
Introduced in #184 OSD creation doesn't take into account custom cluster name
=> Missing cluster name argument

daemon/README.md
Added an explanation of how to use `radosgw-admin` from the Docker host to run administrative commands.
=> Hint about radosgw-admin usage

README.md, base/README.md
'centos' branch READMEs still carry Ubuntu as the OS name
causing confusing for readers visiting github, thus fixing
it here
Signed-off-by: Deepak C Shetty <deepakcs@redhat.com>
=> Fix READMEs for 'centos' branch

daemon/README.md, daemon/entrypoint.sh
Backporting this patch to suit centos Ceph-hammer version.
Implementing the network detection for k8s scenarios. Now we do not use
the MON_IP_AUTODETECT anymore but use a more general variable called
NETWORK_AUTO_DETECT. Updating the doc.
Signed-off-by: Deepthi Dharwar <ddharwar@redhat.com>
=> ceph/daemon centos: Backport change ip and network detecting logic

daemon/Dockerfile, daemon/ceph-disk.patch, daemon/entrypoint.sh
This pull provides a patch to ceph-disk, allowing the permissions to be overridden.  A disk-type OSD will then run with perms ceph:disk, so it can get raw block dev access for the journal file.
=> Fix for issue #171

daemon/ceph.defaults
As-is, BTRFS filesystems can't always be created for OSDs - pre-existing data won't be appropriately wiped.  Turns out -f was specified for XFS filesystems, so do the same thing for BTRFS ones.
=> Add an appropriate default option for BTRFS

daemon/entrypoint.sh
fixes: /entrypoint.sh: line 117: [: -v: binary operator expected
=> fix ip existence check

daemon/Dockerfile, daemon/config.kv.sh
kviator can't store binary data (see ceph/ceph-docker #220 ).  This works around that limit via sharutils and uuencoding/decoding the monmap.
=> properly store binaries with kviator

daemon/README.md
Explain why monitors should be started with a volume for /var/lib/ceph.
=> README.md update for monitors

daemon/entrypoint.sh
Add a dev_part function to properly compute the numbered partition on the named block device, and use it throughout.  This seems to fix issue #226 .
=> Compute names for partition block devices correctly

daemon/entrypoint.sh
Feature proposed by @oll-78.
It brings the ability to run multiple OSDs within a single container.
I thought we were already able to do so but didn't find any mention in
the code. The only thing I recall is a patch from @dmitryint in #24 but
since I never used it I'll let either @dmitryint or @Ulexus comment on
this. It seems that this patch uses ceph-disk instead.
Signed-off-by: Oleg Lazo <oll@niif.spb.su>
=> daemon: multiple osd in one container

daemon/config.kv.sh
The monmap is stored in the KV store, but there's no obvious means to update it when it changes.  This patch updates the monmap whenever it's successfully pulled from peers, meaning the KV store's version will update when a mon restarts.  A bit awkward, but it ensures that if several new mons are added the KV store's monmap isn't too old.
=> Update KV store when monmap is successfully pulled

daemon/entrypoint.sh
`ceph osd crush create-or-move` is called in activate step. In
prepare stage, there is no whoami generated. So it will failed when
getting OSD_ID casuing the container failed to start.
=> Fix failed ceph disk prepare step

daemon/entrypoint.sh
Fix a reversion in the code.  If OSD_JOURNAL is specified, we should use
the provided OSD_DEVICE with no modification.  If you've picked a journal,
we can assume you know what you're doing.
Without this, it's impossible to run multiple OSDs on a single disk (useful
for NVMe).
Signed-off-by: Mike Shuey <shuey@purdue.edu>
=> Fix reversion that breaks multiple OSDs on a device

daemon/ceph.defaults
use the proper name
fixes: #264
=> daemon: fix osd_journal variable

daemon/confd/src/ceph.conf.toml.in, daemon/config.kv.sh
* confd create a /etc/ceph/ceph.conf file but for cluser name different
of 'ceph' the configuration file must be /etc/ceph/$CLUSTER.conf
=> Use KV store with any cluster name

.travis.yml, travis-builds/bootstrap_osd.sh, travis-builds/build_imgs.sh, travis-builds/validate_cluster.sh
We rely on Travis's infrastructure to build the 'daemon' image and run
all the ceph daemons. So we run a monitor, an osd (with directory
scenario, a mds and one rgw).
We have a validation script to make they all started properly. During
the validation sequence, we wait for 20 seconds to let the cluster
stabilize and populate the pgs.
=> CI: build daemon image on travis and test it

ceph-releases/jewel/ubuntu/14.04/base/Dockerfile
Travis is using Docker 1.8.x and thus does not support 'ARG' in the
Dockerfile. So instead re-using the old fashion way.
[ci skip]
=> base: remove 'arg' so travis is happy

travis-builds/build_imgs.sh
Travis is configured to build on master and all the branches. If Travis
is testing a branch like build-master-jewel-centos-7 we don't need to
figure out which image to build since root path of base, daemon and demo
exist. If we don't do this we will always build other images.
=> ci: execute local builds instead of figuring out what to build

.travis.yml, ceph-releases/hammer/ubuntu/14.04/daemon/my_init/my_init, ceph-releases/infernalis/centos/7/base/Dockerfile, ceph-releases/infernalis/ubuntu/14.04/daemon/my_init/my_init, ceph-releases/jewel/centos/7/base/Dockerfile, ceph-releases/jewel/ubuntu/14.04/daemon/my_init/my_init
since we use --net=host we don't need the k8s scenario to be enabled
=> ci: demo do not use k8s mode

.travis.yml, ceph-releases/jewel/ubuntu/14.04/daemon/README.md, ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh, travis-builds/bootstrap_osd.sh
the current directory mode aims to run multiple osd processes in a
single container. It uses runit, which is hard to find and not packaged
for some distros. This commit introduces a simple directory mode that
will only run one osd process per container. Prior to do that it will
check if a lock is already held by another osd process. If so it won't
start the osd and will just try to find another one to run. If nothing
is found or all the osds available are already running with exit the
container explaining that all the osds are already running.
=> daemon: new directory mode

ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh
I set up a ceph-docker,when a osd container down,I plan restart it,so I change a environment of OSD_TYPE from disk to activate in docker-compose.yml,but it can't start success,because it can't get correct osd_id of itself.
when I create 3 osd,this folder will be created 
/var/ceph/lib/osd/ceph-0
/var/ceph/lib/osd/ceph-1
/var/ceph/lib/osd/ceph-2
the osd_activate function will only get the biggest osd_id from /var/ceph/lib/osd/ceph-2
the OSD_ID is 2
so,I change it get osd_id from ceph-disk
thanks
=> fix bug about OSD_ID

ceph-releases/jewel/ubuntu/14.04/daemon/Dockerfile
While running a dev env, we usually modify entrypoint files so we better
have the entrypoint being called at the end of the Dockerfile.
This speeds up the build process.
=> daemon: move the entrypoints at the end of the Dockerfile

ceph-releases/jewel/ubuntu/14.04/demo/entrypoint.sh
Since jewel, certain limitations apply to OSD object name lengths: specifically if ext4 is in use for block devices or a directory based OSD is configured, OSD's must be configured to limit object name length:
```
osd max object name len = 256
osd max object namespace len = 64
```
Or, disable the check:
```
osd check max object name len on startup = false
```
When using ceph/demo, I think most of users are using an ext4 fs. So we should
open this setting by default.
> More discussions can be found here:
> 
> https://bugs.launchpad.net/charms/+source/ceph-osd/+bug/1580320
> http://ceph.com/releases/v10-2-0-jewel-released/
If we don't add this, though `ceph/demo` will be ok in a few minutes, but it will soon be `HEALTH_ERR`, and all the `ceph-osd` exits.
```
ps aux | grep ceph-osd …
```
=> Disable osd check max obj name len in jewel:demo

ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh
Hi,
1.
If we got some IP address such as 10.1.86.10, end with zero.
It match the rule "grep -v "0$" " and MON_IP won't set anything.
Using grep -w can help us.
2.
CEPH_PUBLIC_NETWORK alwayls grep the network 0.0.0.0/1.
Maybe using "grep -vE "^127|^0" " is a better choice.
=> Fix bug of NETWORK_AUTO_DETECT

ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh
Previously, the partition would be added onto OSD_DEVICE which is already assumed to contain the partition, causing activate to fail if OSD_JOURNAL is specified (see #313)
=> entrypoint: fix activate with OSD_JOURNAL

ceph-releases/jewel/ubuntu/14.04/daemon/README.md, ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh
When 'osd' is only set in the docker run command as $1 we need to detect
which scenario is desired. The commit splits the logic into a new
function and makes the overall detection clearer in term of code
readability.
Half fix for #324
=> daemon: better osd scenario prediction

ceph-releases/jewel/centos/7/base/Dockerfile, ceph-releases/jewel/fedora/24/base/Dockerfile, ceph-releases/jewel/ubuntu/14.04/base/Dockerfile, ceph-releases/jewel/ubuntu/14.04/daemon/README.md, ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh, ceph-releases/jewel/ubuntu/16.04/base/Dockerfile
rbd-mirror is use to asyncrhonously replicate ceph block images from one
cluster to another. It is usually used to overcome ceph's synchronous
nature and for disaster recovery purpose.
=> daemon: add rbd-mirror daemon

ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh
when running osd_activate and OSD_JOURNAL was used, it used device instead of partition..
Now it's the other way around.
=> fixed osd_activate to work with partitions

ceph-releases/jewel/centos/7/daemon/my_init, ceph-releases/jewel/centos/7/daemon/my_init/LICENSE.txt, ceph-releases/jewel/centos/7/daemon/my_init/my_init
In a previous comment I was thinking that using non-full path would work
(to call the binaries). However it seems that we need fullpath.
Updating the path with the correct location for redhat and debian based
systems.
=> daemon: fix osd_dir path per distro

ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh
Sometimes the old code used to go into osd_disk function when already an OSD.
So it should go to osd_activate function.
My suggested change will most likely better detect already prepared OSD's.
Note that I haven't tested this code yet in a live node, but it's such a minor change, I don't see why it shouldn't work.
I can test it if you deem it necessary, otherwise it will get tested it as soon as it's merged pushed to docker hub :-)
=> osd_trying_to_determine_scenario better OSD detect

ceph-releases/jewel/ubuntu/14.04/demo/entrypoint.sh
This PR doesn't solve the issue, but at least gives users a hint as to what's going on and how to fix it.
```
$ docker run --net=host -e MON_IP=192.168.99.101 -e CEPH_PUBLIC_NETWORK=192.168.99.0/24 b5d4a5cf6fa2
creating /etc/ceph/ceph.client.admin.keyring
creating /etc/ceph/ceph.mon.keyring
monmaptool: monmap file /etc/ceph/ceph.monmap
monmaptool: set fsid to c28732cf-18a8-45cd-98ff-a218bd18bb2b
monmaptool: writing epoch 0 to /etc/ceph/ceph.monmap (1 monitors)
creating /tmp/ceph.mon.keyring
importing contents of /etc/ceph/ceph.client.admin.keyring into /tmp/ceph.mon.keyring
importing contents of /etc/ceph/ceph.mon.keyring into /tmp/ceph.mon.keyring
ceph-mon: set fsid to c28732cf-18a8-45cd-98ff-a218bd18bb2b
ceph-mon: created monfs at /var/lib/ceph/mon/ceph-default for mon.default …
```
=> Throw a warning about hostname -s == 'default'

ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh, ceph-releases/jewel/ubuntu/14.04/demo/entrypoint.sh
this commit improves the way we detect for IP addresses while using the
NETWORK_AUTO_DETECT variable.
Usually this is used for k8s setup when we don't know which IP adddress
will be used by the container.
=> daemon: allow more interfaces to be discovered

ceph-releases/jewel/ubuntu/14.04/demo/entrypoint.sh
A followup from https://github.com/ceph/ceph-docker/pull/339
This is working for me with the default hostname for docker-machine. Is there any reason we can't just lock this down to localhost?
=> Use localhost since everything runs in one container

ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh
Some ceph-disk prepare commands were missing --cluster which prevented it from working with multiple clusters.
=> entrypoint: pass $CLUSTER to ceph-disk

examples/kubernetes/ceph-mds-v1-dp.yaml, examples/kubernetes/ceph-mon-check-v1-dp.yaml, examples/kubernetes/ceph-mon-v1-dp.yaml, examples/kubernetes/ceph-mon-v1-ds.yaml, examples/kubernetes/ceph-osd-v1-ds.yaml
A minor update to the Kubernetes resources to use the official repo. It is using the `latest` tag but should partly solve the issue raised in #342
=> Use the official ceph-docker images for Kubernetes examples

ceph-releases/jewel/ubuntu/14.04/daemon/README.md, ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh
This new scenario only works with OSD_DISK.
You can now prepare osd disks with either bluestore or dmcrypt:
* set `OSD_BLUESTORE=1` to use bluestore
* set `OSD_DMCRYPT=1` to encrypt osd directory data
For dmcrypt the admin key must be present on the node so the encrypted
key can be stored on the monitor store during the preparation stage.
=> add support for bluestore and dmcrypt

ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh
It looks like the current entrypoint script will only work on Ubuntu, and that my_init is designed to provide distribution-independence.
I tested this change on CentOS 7 (and Kubernetes).
=> Fix daemon entrypoint script for non-Ubuntu distros.

examples/kubernetes-coreos/50-rbd.rules, examples/kubernetes-coreos/Dockerfile, examples/kubernetes-coreos/README.md, examples/kubernetes-coreos/ceph, examples/kubernetes-coreos/ceph-disk, examples/kubernetes-coreos/ceph-rbdnamer, examples/kubernetes-coreos/install-ds.yaml, examples/kubernetes-coreos/install-job.yaml, examples/kubernetes-coreos/rados, examples/kubernetes-coreos/rbd, examples/kubernetes-coreos/startup.sh
this is an accumlation of files in the coreos example directory
and additional pieces required to make it work.  the goal was to
have a simple and reliable way to both run ceph on kubernetes on
coreos and be able to access ceph resources (CephFS and RBD) from
any kubernetes node.
=> adds sample files for running kubernetes on coreos

ceph-releases/jewel/fedora/24/base/Dockerfile, ceph-releases/jewel/ubuntu/14.04/daemon/my_init/my_init
Runit is not part of the default package in fedora. This patch builds it
from source in the fedora base image.
This fixes #381 
Signed-off-by: Ganesh Maharaj Mahalingam <ganesh.mahalingam@intel.com>
=> Fix osd startup failure in fedora

examples/kubernetes/generator/README.md, examples/kubernetes/generator/ceph-key.py
Noticed this when the script broke on my arch-linux box. Python3 is pretty much the de-facto version of Python nowadays, right?
Also I found some dead imports and a markdown file in the generator folder that I missed in #385.
=> upgrade examples/kubernetes/generator/ceph-key.py to python 3

ceph-releases/jewel/fedora/24/base/Dockerfile
It looks like I was a little too eager. `nfs-ganesha-rgw` is currently not being built for Fedora.
This should fix the image build error
=> Remove nfs-ganesha-rgw for Fedora

ceph-releases/jewel/centos/7/base/Dockerfile, ceph-releases/jewel/centos/7/daemon/Dockerfile, ceph-releases/jewel/fedora/24/base/Dockerfile, ceph-releases/jewel/fedora/24/daemon/Dockerfile, ceph-releases/jewel/ubuntu/14.04/base/Dockerfile, ceph-releases/jewel/ubuntu/14.04/daemon/Dockerfile, ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh, ceph-releases/jewel/ubuntu/16.04/base/Dockerfile, ceph-releases/jewel/ubuntu/16.04/daemon/Dockerfile
It seems we've had a few issues with runit recently and thought I'd start a discussion (with code) for switching it out for something else.
We've used forego (a go based foreman replacement) in other projects so decided to test it out an alternative for launching multiple processes in ceph-docker. It's currently untested but thought I'd put it out there first before spending more time getting it ready.
The main change is that forego will run the processes specified in a 'Procfile' which is generated slightly differently to the runit. Overall there are slightly fewer dependencies with a single binary that will work across all base OSes. Logs are still sent to stdout/err with each line prefixed with the process name (cluster name and osd ID).
Thoughts? Not a visible change but may simplify …
=> Removing runit

ceph-releases/jewel/ubuntu/14.04/demo/entrypoint.sh
use it like this: `-e CEPH_REST_API_PORT=5001`.
=> demo: ability to configure restapi port

ceph-releases/hammer/ubuntu/14.04/daemon/entrypoint.sh, ceph-releases/hammer/ubuntu/14.04/demo/entrypoint.sh, ceph-releases/infernalis/ubuntu/14.04/daemon/entrypoint.sh, ceph-releases/infernalis/ubuntu/14.04/demo/entrypoint.sh, ceph-releases/jewel/redhat/7.2/entrypoint.sh, ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh, ceph-releases/jewel/ubuntu/14.04/demo/entrypoint.sh
So that scripts can tell when an entrypoint is done right before the `exec` calls.
Fixes issue #399
=> add a "SUCCESS" marking string

ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh
Sometimes devices do not have any GPT labels and thus can not be
identified properly. If nothing is present we just create one.
Closes: https://github.com/ceph/ceph-ansible/issues/1046
=> osd: verify device state

tests/conftest.py
Alternatively, wait 0.5 seconds if it wasn't able to.
=> Use the new `SUCCESS` marker when creating a container

travis-builds/purge_cluster.sh
The docker ps command was returning no containers that caused the docker
stop command to fail. That, combined with the set -e flag from the
caller was causing the purge_cluster.sh script to exit prematurely. This
prevented the purge_cluster.sh script from properly cleaning up previous
ceph configuration files.
Signed-off-by: Ivan Font <ifont@redhat.com>
=> Fix CI errors caused by container status commands

tests/base/test_ceph_conf.py, tests/conftest.py
Adds a bunch of tests for `ceph.conf`, cleans up `conftest.py` that had some duplication, and adds a new helper for calling `execute` that should make it simpler to run commands on the containers
=> ceph.conf tests

ceph-releases/jewel/redhat/7.2/entrypoint.sh, ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh
As described in #436, using `-d` to run the ceph-osd process which makes
docker logs growing really fast.
Using `-d` is not ideal nor really useful.
Run `ceph-osd` process with `-f` (which will log to files) instead of
running with `-d -f` which will only log on stdout and not log file.
`-f` seems to log errors only, which should be enough.
Closes: #436
=> osd: reduce log verbosity

ceph-releases/infernalis/ubuntu/14.04/daemon/config.k8s.sh, ceph-releases/jewel/ubuntu/14.04/daemon/config.k8s.sh
This ensures that monmaptool is only passed containers with valid IPv4/IPv6 addresses.
This partially resolves https://github.com/ceph/ceph-docker/issues/389
=> Ensure non-empty IP address for containers passed to monmaptool

ceph-releases/jewel/ubuntu/14.04/daemon/config.k8s.sh
Race condition at times prevents the proper detection of ceph-mon pod IP
addresses resulting in the creation of an invalid monmap. This change
implements a 10 second retry loop to attempt to grab the ceph-mon pod IP
addresses before giving up and exiting. If we exit, we allow kubernetes to
restart the pod.
Signed-off-by: Ivan Font <ifont@redhat.com>
=> Timeout loop to detect IP addresses of ceph-mons

tests/tox.sh, tox.ini
This is an initial take on harnessing the functional testing from ceph-ansible in ceph-docker.
This will greatly simplify the setup, validation, and teardown of the environment since ceph-ansible already has a way to do all those, including the needed support for docker itself.
For this to work it will need ceph-ansible changes to allow consuming a dev image that `build_imgs.sh` will create, and changes to ceph-build to call tox
=> toxification of functional tests

examples/kubernetes/README.md, examples/kubernetes/ceph-cephfs-test.yaml, examples/kubernetes/ceph-rbd-test.yaml, examples/kubernetes/cephfs-pvc-pod.yaml, examples/kubernetes/delete_ceph_cluster.sh, examples/kubernetes/gce/README.md, examples/kubernetes/gke/README.md, examples/kubernetes/rbd-dyn-pv-claim.yaml, examples/kubernetes/rbd-dyn-pvc-pod.yaml, examples/kubernetes/rbd-pv-claim.yaml, examples/kubernetes/rbd-pv.yaml, examples/kubernetes/rbd-pvc-pod.yaml, examples/kubernetes/rbd-storage-class.yaml, examples/kubernetes/rgw_s3_client.py
- Update RBD PVC docs and node-type in resources
Updated docs to remove the ceph-client node-type selector in resources
and instead run sed commands to update the node-type for the special
case of ceph-client requirements for GKE images. Updated RBD PVC
examples to be more specific to RBD to differentiate between CephFS and
RBD.
- Adds documentation for setting up Ceph Kubernetes cluster on Google
Compute Engine with steps on testing Rados Gateway S3 interface, CephFS,
Ceph RBD, RBD and CephFS static provisioning of persistent volume
claims, and lastly RBD dynamic provisioning of persistent volume claims.
- Adds new resources for demonstrating use of RBD dynamic provisioning of
persistent volume claims.
- Updates RGW S3 client script to support RGW NodePort service type.
- Updates Ceph …
=> Ceph cluster on GCE K8s cluster

examples/kubernetes/create_ceph_cluster.sh
Executing the yml files in a kubernetes cluster with version 1.5.x raises invalid attributes for the yml file. This can be fixed adding the --validate=false on the kubectl call.
=> Don't validate yml files for creating the cluster

ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh
This PR changes the egrep's regexp of zap_device function in entrypoint.sh to make possible to find devices that begins with **_xv_**, like **_/dev/xvdi_**.
=> Update egrep of zap_device function

examples/kubernetes/gce/README.md, examples/kubernetes/gke/README.md
Also in this PR:
- Update GCE doc kubectl exec commands
- Reverse ordering of `ceph` namespace kubectl config so that we create the `ceph` namespace first before setting the kubectl config context to use it by default.
=> Add video demo link to Ceph Kubernetes on GCE example

ceph-docker-workflow.sh, generate-dev-env.sh, travis-builds/build_imgs.sh
Now that kraken is out the workflow and the ci build need some refactor.
The main difference is that kraken doesn't have a base image anymore. We
also prioritize kraken in the build process if nothing is found.
=> workflow changes for kraken

ceph-releases/jewel/opensuse/Leap_42.2/base/Dockerfile
squashing multiple RUN statements onto one and reducing the image size
by cleaning up the zypper cache when we're done.
Signed-off-by: Abhishek Lekshmanan <abhishek@suse.com>
=> opensuse: make zypper commands into a single RUN statement

ceph-releases/kraken/ubuntu/16.04/daemon/start_mon.sh, ceph-releases/kraken/ubuntu/16.04/daemon/variables_entrypoint.sh, ceph-releases/kraken/ubuntu/16.04/demo/entrypoint.sh
This fixes issues when all Ceph Mon Pods are deleted and recreated. As they don't come up with the old data and are missing their original data.
Closes https://github.com/ceph/ceph-docker/issues/485
=> Add MON_DATA_DIR var to allow data to be saved in a set directory

ceph-releases/kraken/centos/7/daemon/Dockerfile, ceph-releases/kraken/ubuntu/16.04/daemon/Dockerfile, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_disk_activate.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_disk_prepare.sh, ceph-releases/kraken/ubuntu/16.04/daemon/variables_entrypoint.sh, ceph-releases/kraken/ubuntu/16.04/daemon/zap_device.sh
We can now set a partition uuid for the journal and the lockbox (used
when dmcrypt is used).
=> osd: add support for setting partition uuids

ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_disk_activate.sh
This patch is about making the script much more readable.
1- create variables with obvious names
2- avoid code duplication by creating variables feeded in some conditional statements
=> osd_disk_activate: Simplificating script

ceph-releases/kraken/ubuntu/16.04/daemon/common_functions.sh
During when not specifying anything for the osd type we try to determine
what needs to be done. Depending on what find we have to source the file
first before calling the function.
=> daemon: fix osd_trying_to_determine_scenario function

ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_disks.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_mds.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_osd.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_rgw.sh
When doing a test -eq, having quotes around the right value is clearly misleading as we do compare integers not text.
This patch is just about removing the quotes around the right member.
=> cleanup: bash eq compare means integer not text

ceph-releases/kraken/ubuntu/16.04/daemon/config.kv.sh, ceph-releases/kraken/ubuntu/16.04/daemon/config.static.sh, ceph-releases/kraken/ubuntu/16.04/daemon/entrypoint.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_mon.sh, ceph-releases/kraken/ubuntu/16.04/daemon/variables_entrypoint.sh, ceph-releases/kraken/ubuntu/16.04/daemon/zap_device.sh
In the whole code base, we have a several inverted logic.
Using the "! -z" syntax is just a "-n" test.
This simple patch is just about using the direct way of testing instead of using the inverted logic.
This makes the code more straigh-forward to read.
=> cleanup: Avoid inverted logic

ceph-releases/kraken/ubuntu/16.04/daemon/zap_device.sh
'Payload Offset' field from crypsetup return a number of physical sectors.
The actual code is considering the sector size to be 512 when devices can report a different value like 4096.
This patch is about reading the physical block device size by using blockdev, and use it on the 'dd' command line to specify the proper 'bs' field.
If we fail at detecting that value, then we default to 512 which is the legacy value for sectors.
=> zap_device: 'Payload offset' unit is sector size

ceph-releases/kraken/ubuntu/16.04/daemon/common_functions.sh, ceph-releases/kraken/ubuntu/16.04/daemon/config.static.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_mon.sh
The actual code is using a lot of regexp and a complex logic to define if we should use ipv4 or ipv6.
This patch try to simplify the read of the start_mon() function by:
- adding basic functions to extract ip or network information
- embedded the logic if 'ip' is missing directly in those functions
- improve the ipv6 support
- simplify the logic by making common calls between ipv4|6
First, the get_ip & get_network functions are created to externalize
the detection code from the main function. This way the logic is easier
to read.
This logic is simplified by unificating cases where NETWORK_AUTO_DETECT > 1 (aka 4 or 6).
We now have the same code base for both.
The newly created functions embedded the logic to detect the network configuration regarding if 'ip' is present or not.
For IPV6, …
=> start_mon: Reworking network detection

ceph-releases/kraken/ubuntu/16.04/daemon/common_functions.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_rgw.sh
In this program, there is two occurences of duplicated code that over-complicate the reading.
This patch just take care of getting the conditional code being smaller
and then execute the command with arguments.
This patch is also adding an exec prior the final command as per docker rule.
The last process to be executed should be run in exec when using bash as init.
=> start_rgw: Avoid duplicated code

ceph-releases/kraken/ubuntu/16.04/daemon/populate_kv.sh
cat | grep is just grep. So let's remove a useless command here
=> populate_kv: 'cat file | grep x' is 'grep x file'

ceph-releases/kraken/ubuntu/16.04/daemon/docker_exec.sh, ceph-releases/kraken/ubuntu/16.04/daemon/entrypoint.sh
If a container fails to start, it's pretty complicated to understand what went wrong and why.
As per the container thing, it's even more difficult as if a command fails, the container stops making any tracing impossible.
If you can't modify the container, then it's pretty difficult to analyse the issue.
This patch offer to "control" the verbosity of bash with a DEBUG environement variable.
If you need to trace a particular container, just set DEBUG to any value at run time like :
sudo docker run -d --name ceph-mon -e DEBUG=1 -e NETWORK_AUTO_DETECT=1 daemon mon
Later, if we want various behavior, we could read the value of DEBUG and trigger different options.
This first patch makes things easy by just considering the presence and not the value of DEBUG.
=> entrypoint: Enabling bash -x with DEBUG environment variable

ceph-releases/kraken/ubuntu/16.04/daemon/config.kv.etcd.sh
In order to create the Ceph filesystem we need the admin keyring. The kv
etcd scenario was missing this function.
=> daemon: kv store for mds add admin key function

misslinks.sh
The current location of the script breaks the ceph-workflow script as
the script is evaluated as a release. Moving the script to the git root
dir and pushd into ceph-releases before execution.
=> script: move misslinks script to root dir

ceph-releases/kraken/ubuntu/16.04/daemon/config.k8s.sh, ceph-releases/kraken/ubuntu/16.04/daemon/config.kv.etcd.sh, ceph-releases/kraken/ubuntu/16.04/daemon/config.static.sh
Depending on the method we use to deploy the admin key can not be
fetched so this commit clarifies the code printed during execution.
=> daemon: clarify the get_admin_key function

ceph-releases/kraken/centos/7/daemon/Dockerfile, ceph-releases/kraken/centos/7/demo/Dockerfile, ceph-releases/kraken/ubuntu/16.04/daemon/Dockerfile, ceph-releases/kraken/ubuntu/16.04/demo/Dockerfile
Prior to this commit we were relying on the "ceph" package pulling all
the ceph-mon, ceph-osd, ceph-mgr packages. So now we call each packages
individually.
=> daemon: explicitly install all the ceph packages

ceph-releases/kraken/ubuntu/16.04/daemon/check_zombie_mons.py, ceph-releases/kraken/ubuntu/16.04/daemon/config.k8s.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_mon.sh, ceph-releases/kraken/ubuntu/16.04/daemon/variables_entrypoint.sh, ceph-releases/kraken/ubuntu/16.04/daemon/watch_mon_health.sh, examples/kubernetes/generator/templates/ceph/admin.keyring.tmpl
This will use the nodeNames instead of the pod names for the monmap
***
This allows users to use `hostNetwork: true` mode for Ceph mons in Kubernetes.
=> Added MON variable for Kubernetes hostNetwork mode

ceph-releases/kraken/ubuntu/16.04/daemon/start_mon.sh
Problem: using a cluster name different thant 'ceph' makes the monitor
mkfs failing.
Solution: add the --cluster option solves this problem as it will pass
the right cluster name so the mkfs can found the location of the ceph
configuration file.
=> daemon: fix mon mkfs with different cluster name

ceph-releases/jewel/ubuntu/14.04/base/Dockerfile, ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh, ceph-releases/jewel/ubuntu/14.04/demo/entrypoint.sh, ceph-releases/jewel/ubuntu/16.04/base/Dockerfile, ceph-releases/kraken/ubuntu/16.04/daemon/Dockerfile, ceph-releases/kraken/ubuntu/16.04/daemon/entrypoint.sh, ceph-releases/kraken/ubuntu/16.04/demo/Dockerfile, ceph-releases/kraken/ubuntu/16.04/demo/entrypoint.sh
Error:  nfs-ganesha-fsal : Depends: glusterfs-common (>= 3.8.8) but it
is not going to be installed
Solution: temporary remove the package and re-introduce it once the
issue is resolved.
This is urgent as this breaks all the builds on Xenial.
=> daemon: resolve broken package dependancy

ceph-releases/kraken/ubuntu/16.04/daemon/entrypoint.sh
Prior to this patch is no valid CEPH_DAEMON was found no one would know
that the ceph-mgr can be activated. Using the mgr option as $1 when
doing your "docker run" or the variable CEPH_DAEMON=MGR you can enable
it.
=> daemon: add missing help message for ceph-mgr

ceph-releases/kraken/ubuntu/16.04/daemon/debug.sh
When using a patching filesystem by using DEBUG=fs=<url> command line,
the root filesystem could be reallocated into a sub directory.
That's typically the case if you download a tarball from github.
This patch is trying to detect the root filesystem by searching the
first directory to feature a list of typical directories of a / like
/usr, /bin or similar.
Once it's found, the --strip= option of tar is used to skip the useless
directories.
=> debug: Detecting root directory inside patched filesystem

ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_disk_prepare.sh
Problem: if the container was ran with OSD_TYPE=disk and restarted the
code will try to prepare the disk if even an already prepared OSD is
found.
Solution: exist the osd_disk_prepare function once we found an already
prepared OSD.
Fixes: #568
=> daemon: exit the prepare function if the OSD is already prepared

ceph-releases/hammer/centos/7/daemon/check_zombie_mons.py, ceph-releases/hammer/ubuntu/14.04/daemon/entrypoint.sh, ceph-releases/infernalis/ubuntu/14.04/daemon/check_zombie_mons.py, ceph-releases/infernalis/ubuntu/14.04/daemon/entrypoint.sh, ceph-releases/jewel/ubuntu/14.04/daemon/check_zombie_mons.py, ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh, ceph-releases/kraken/ubuntu/16.04/daemon/check_zombie_mons.py, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_directory.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_directory_single.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_disks.sh, ceph-releases/kraken/ubuntu/16.04/daemon/watch_mon_health.sh
get the OSD_ID from directory name after the last "-"
for example:
kube-system-3 -> OSD_ID = "3"
instead of OSD_ID="system" with the current command
fixes #579
=> fixes get osd_id from directory name

.travis.yml
We deploy the ceph-demo container on Travis using 'test' as a cluster
name. On error when only call 'ceph -s' which assumes a cluster named
'ceph'. This commits resolves this.
=> test: travis cluster name on error

ceph-releases/jewel/ubuntu/16.04/demo/Dockerfile, ceph-releases/jewel/ubuntu/16.04/demo/s3cfg
When enabling auto demo user creation with ceph/demo:tag-build-master-jewel-ubuntu-16.04, container fails to start because there is no s3cfg there.
=> adding s3cfg for ubuntu 16.04 ceph/demo image

ceph-releases/kraken/ubuntu/16.04/daemon/common_functions.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_osd.sh
As described in https://github.com/ceph/ceph-docker/issues/572, we
currently don't source `/etc/sysconfig/ceph` on RedHat based systems and
`/etc/default/ceph` on Ubuntu based systems.
This is important we source this file so we can enable
TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES.
This commits adds some functions to determine on which OS the container
image is running. Then during the OSD execution sources the right file.
Fixes: https://github.com/ceph/ceph-docker/issues/572
=> daemon: source ceph env files

ceph-releases/hammer/centos/7/base/Dockerfile, ceph-releases/jewel/centos/7/base/Dockerfile, ceph-releases/jewel/ubuntu/14.04/base/Dockerfile, ceph-releases/kraken/centos/7/daemon/Dockerfile, ceph-releases/kraken/ubuntu/16.04/daemon/Dockerfile
When "yum install <list-of-packages>" fails to install package(s) in the list, it will simply print a warning, eg, "No package ceph-radosgw available". It still exits with a "0" exit code in this case, leading Docker to continue on with the build process as if nothing is wrong.
This can happen if one of the packages is accidentally unavailable in our Yum repositories.
If we fail to install a package in this list, we need the build process to fail immediately so we know the container will not be usable.
Rather than only relying on "yum install"'s exit code, use rpm to double-check that the packages were indeed installed locally.
=> ensure packages are installed after "yum install"

ceph-releases/jewel/centos/7/daemon/Dockerfile, ceph-releases/jewel/fedora/24/daemon/Dockerfile, ceph-releases/jewel/opensuse/Leap_42.2/daemon/Dockerfile, ceph-releases/jewel/rhel/7.3/daemon/Dockerfile, ceph-releases/jewel/ubuntu/14.04/daemon/Dockerfile, ceph-releases/jewel/ubuntu/16.04/daemon/Dockerfile, ceph-releases/kraken/centos/7/daemon/Dockerfile, ceph-releases/kraken/ubuntu/16.04/daemon/Dockerfile, ceph-releases/luminous/centos/7/daemon/Dockerfile, ceph-releases/luminous/rhel/7.3/daemon/Dockerfile, ceph-releases/luminous/ubuntu/16.04/daemon/Dockerfile
It's better to detect bash script syntax errors at build time instead of
runtime.
=> daemon: use bash syntax validation command

ceph-releases/jewel/rhel/7.3/daemon/Dockerfile, ceph-releases/luminous/rhel/7.3/daemon/Dockerfile
Prior to this change, The Red Hat Ceph Storage container images did not override labels from the RHEL 7 base image. In Red Hat's container catalog, the entry for rhceph displays some text about RHEL 7, not Ceph.
Override the RHEL 7 base image's labels with our product's labels.
=> add summary, display-name, tags LABELs for RHEL

examples/kubernetes/create_ceph_cluster.sh, examples/kubernetes/create_secrets.sh, examples/kubernetes/generator/generate_secrets.sh, examples/kubernetes/generator/templates/ceph/admin.keyring.jinja, examples/kubernetes/generator/templates/ceph/bootstrap.keyring.jinja, examples/kubernetes/generator/templates/ceph/ceph.conf.jinja, examples/kubernetes/generator/templates/ceph/input.yaml, examples/kubernetes/generator/templates/ceph/mon.keyring.jinja
These two commits add templates and code to use jinja2 as template processor. sigil can still be enabled setting the TEMPLATE_ENGINE variable.
sigil is not easy to come by, while jinja2 is available on Fedora (python3-jinja2-cli package) and can be installed easily using pip ([jinja2-cli](https://pypi.python.org/pypi/jinja2-cli) package). The language is used for popular projects like ansible or Django.
This addresses issue #338 even though it is not entirely without dependencies.
=> Jinja template processor for Kubernetes example

examples/helm/build-all.sh, examples/helm/ceph/templates/jobs/job.yaml, examples/helm/ceph/templates/mds/deployment.yaml, examples/helm/ceph/templates/mon/deployment.yaml, examples/helm/ceph/templates/mon/service.yaml, examples/helm/ceph/templates/mon/statefulset.yaml, examples/helm/ceph/templates/osd/daemonset.yaml, examples/helm/ceph/templates/rgw/deployment.yaml, examples/helm/ceph/values.yaml, examples/helm/deploy_steps.md
adopt k8s 1.6 also, added limits for node exporter, fixed build script, made some files from readOnly to readwrite so chown will not fail, added addnotation as per issue 573, added debug option, exposed the ceph_init image, changed NETWORK_AUTO_DETECT to 4 in statefull set (as per one issue)
It has been tested, things improved, but still most of the already reported issues remain, including lack of compatibility with the new images...
=> Helm charts: fixes&compat. fixes, still most from known issues remain

ceph-releases/jewel/ubuntu/14.04/daemon/start_mon.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_mon.sh, ceph-releases/luminous/ubuntu/16.04/daemon/start_mon.sh
When the container restarts we re-inject the old version of the map
which results in the monitor failing to start/join the existing quorum.
So now we fetch the latest version prior to re-run it.
Fixes: #626
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1448954
=> daemon: try to fetch the last version of monmap

ceph-releases/jewel/centos/7/base/Dockerfile, ceph-releases/jewel/rhel/7.3/daemon/Dockerfile, ceph-releases/kraken/centos/7/daemon/Dockerfile, ceph-releases/luminous/centos/7/daemon/Dockerfile, ceph-releases/luminous/rhel/7.3/daemon/Dockerfile
The container can not bootstrap a dmcrypt scenario since it tries to
create an ext4 partition. Since ext4 is not present, the preparation
fails.
Fixes: https://github.com/ceph/ceph-ansible/issues/1496
=> daemon: add e2fsprogs for ext4

tests/setup.yml, tox.ini
This adds ``dedicated_journal`` and ``dmcrypt_journal_collocation`` tests from ceph-ansible. It also adds ``luminous`` as a ceph release factor so we can test luminous containers as well.
=> tests: more testing scenarios

tox.ini
This avoids an issue we were seeing where tasks were not skipped when they should have been.
e.g. https://jenkins.ceph.com/view/ceph-docker/job/ceph-docker-nightly-ceph_ansible2.2-jewel-centos7-cluster/10/console
Signed-off-by: Andrew Schoen <aschoen@redhat.com>
=> tests: test with ansible==2.2.3

ceph-releases/jewel/ubuntu/14.04/daemon/start_mon.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_mon.sh, ceph-releases/luminous/ubuntu/16.04/daemon/start_mon.sh
In a scenario where all mon hsots are rebooted some mons fail to come
back up, using -c which points at the configuration file is safer
because we can know that all monitors are defined there.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1455357
Signed-off-by: Andrew Schoen <aschoen@redhat.com>
=> start mon: use -c instead of --inject-monmap

tests/teardown.sh, tests/tox.sh
This is useful when executing tox outside a CI environment; if tests
fail nothing is cleaned up. While that might be desirable, let's provide
a way to manually tear everything down.
Signed-off-by: Zack Cerza <zack@redhat.com>
=> Add tests/teardown.sh

ceph-releases/jewel/ubuntu/14.04/daemon/osd_scenarios/osd_disk_activate.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_disk_activate.sh, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_disk_activate.sh
When ceph cluster name includes number, osd disk activation will fail.
Fix: BZ-1458512 (https://bugzilla.redhat.com/show_bug.cgi?id=1458512)
=> OSD activate fails if cluster name includes number

ceph-releases/jewel/ubuntu/14.04/daemon/common_functions.sh, ceph-releases/jewel/ubuntu/14.04/daemon/osd_scenarios/osd_directory.sh, ceph-releases/jewel/ubuntu/14.04/daemon/osd_scenarios/osd_disk_prepare.sh, ceph-releases/jewel/ubuntu/14.04/daemon/start_rgw.sh, ceph-releases/kraken/ubuntu/16.04/daemon/common_functions.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_directory.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_disk_prepare.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_rgw.sh, ceph-releases/luminous/ubuntu/16.04/daemon/common_functions.sh, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_directory.sh, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_disk_prepare.sh, ceph-releases/luminous/ubuntu/16.04/daemon/start_rgw.sh
Prior to this change if the command to get the ceph health failed we
didn't have any indication of what went wrong. This is now easier to
debug.
=> daemon: improve ceph health check error

ceph-releases/jewel/ubuntu/14.04/daemon/debug.sh, ceph-releases/kraken/ubuntu/16.04/daemon/debug.sh, ceph-releases/luminous/ubuntu/16.04/daemon/debug.sh
When setting DEBUG=verbose, this only activates bash tracing with set
-x. This patch adds more info during the debug like the name of the
script and the line being executed. See:
$ ./a.sh
+./a.sh:6: echo a
a
=> daemon: improve debugging line

ceph-releases/luminous/centos/7/daemon/disk_introspection.sh, ceph-releases/luminous/rhel/7.3/daemon/disk_introspection.sh, ceph-releases/luminous/ubuntu/16.04/daemon/README-INTROSPECTION.md, ceph-releases/luminous/ubuntu/16.04/daemon/disk_introspection.sh, ceph-releases/luminous/ubuntu/16.04/daemon/entrypoint.sh.in, ceph-releases/luminous/ubuntu/16.04/daemon/variables_entrypoint.sh
=> daemon: disk introspection method

ceph-releases/jewel/ubuntu/14.04/daemon/config.kv.etcd.sh, ceph-releases/kraken/ubuntu/16.04/daemon/config.kv.etcd.sh, ceph-releases/luminous/ubuntu/16.04/daemon/config.kv.etcd.sh
The double brackets are non-needed on an array and even if I wanted to
use them they were mispositionned.
```
creating /etc/ceph/ceph.client.admin.keyring
creating /etc/ceph/ceph.mon.keyring
creating {item//:/ }
bufferlist::write_file({item//:/ }): failed to open file: (2) No such
file or directory
could not write {item//:/ }
```
=> daemon: fix array

ceph-releases/jewel/ubuntu/14.04/daemon/config.k8s.sh, ceph-releases/kraken/ubuntu/16.04/daemon/config.k8s.sh, ceph-releases/luminous/ubuntu/16.04/daemon/config.k8s.sh
When building a command line we need to use an array.
Fixes: https://github.com/ceph/ceph-docker/issues/676
=> daemon: use an array to build command line

ceph-releases/jewel/centos/7/daemon/Dockerfile, ceph-releases/jewel/fedora/24/daemon/Dockerfile, ceph-releases/jewel/opensuse/Leap_42.2/daemon/Dockerfile, ceph-releases/jewel/rhel/7.3/daemon/Dockerfile, ceph-releases/jewel/ubuntu/14.04/daemon/Dockerfile, ceph-releases/jewel/ubuntu/16.04/daemon/Dockerfile, ceph-releases/kraken/centos/7/daemon/Dockerfile, ceph-releases/kraken/ubuntu/16.04/daemon/Dockerfile, ceph-releases/luminous/centos/7/daemon/Dockerfile, ceph-releases/luminous/rhel/7.3/daemon/Dockerfile, ceph-releases/luminous/ubuntu/16.04/daemon/Dockerfile
Since we directly call the bash command, using chmod +x to make the file
executable is not needed. Moreover since we don't pass any argument to
the script generate_entrypoint.sh there is no need for '-c' option.
Somehow this resolves the issue during our build:
```
Step 16 : RUN chmod +x /generate_entrypoint.sh &&   bash -c
"/generate_entrypoint.sh" &&   rm -f /generate_entrypoint.sh &&   bash
-n /*.sh
---> Running in 6fa5c8d5735e
bash: /generate_entrypoint.sh: /bin/bash: bad interpreter: Text file
busy
```
=> dockerfile: chmod +x is not needed

ceph-releases/jewel/ubuntu/14.04/daemon/config.k8s.sh, ceph-releases/kraken/ubuntu/16.04/daemon/config.k8s.sh, ceph-releases/luminous/ubuntu/16.04/daemon/config.k8s.sh
Quoting an array that contains multiple words (processed by bash)
doesn't treat the array with multiple fields.
Using a new IFS and read like suggested in
https://github.com/koalaman/shellcheck/wiki/SC2206 helps us.
Fixes: https://github.com/ceph/ceph-docker/issues/681
=> daemon: fix array for creating monmap in k8s

ceph-releases/jewel/ubuntu/14.04/daemon/common_functions.sh, ceph-releases/kraken/ubuntu/16.04/daemon/common_functions.sh, ceph-releases/luminous/ubuntu/16.04/daemon/common_functions.sh
Simply using ${OSD_DEVICE:-none} will let the shell execute its content.
To avoid this we use the no-op :, which evaluates its
argument and then throws it away, rather than executing it.
=> daemon: use a null operator to declare a variable

ceph-releases/jewel/ubuntu/14.04/daemon/common_functions.sh, ceph-releases/kraken/ubuntu/16.04/daemon/common_functions.sh, ceph-releases/luminous/ubuntu/16.04/daemon/common_functions.sh
Using `:-` won't apply any default, we need `:=` instead.
Please enter the commit message for your changes. Lines starting
=> daemon: use the right variable assignment syntax

ceph-releases/luminous/ubuntu/16.04/daemon/common_functions.sh, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_disk_activate.sh
Open LUKS devices when necessary, do not wait for ceph-disk to do it for
us.
=> daemon: rework dmcrypt implementation

ceph-releases/jewel/ubuntu/14.04/daemon/config.kv.etcd.sh, ceph-releases/jewel/ubuntu/14.04/daemon/config.static.sh, ceph-releases/kraken/ubuntu/16.04/daemon/config.kv.etcd.sh, ceph-releases/kraken/ubuntu/16.04/daemon/config.static.sh, ceph-releases/luminous/ubuntu/16.04/daemon/config.kv.etcd.sh, ceph-releases/luminous/ubuntu/16.04/daemon/config.static.sh
Add a new parameter `ADMIN_SECRET` that allow to deploy a ceph cluster
with a custom admin secret.
=> Mon: Allow to deploy with custom admin secret

ceph-releases/jewel/ubuntu/14.04/daemon/populate_kv.sh, ceph-releases/kraken/ubuntu/16.04/daemon/populate_kv.sh, ceph-releases/luminous/ubuntu/16.04/daemon/populate_kv.sh
I found an error when populating KV store.
If we use the double quote here, the function kv will read all parameter as single variable $1.
And the key name on ETCD would be "max_open_files 131072" instead of "max_open_files".
e.g.
```txt
2017-07-12 02:07:14  bash: Adding key /auth/cephx true with value  to KV store.
2017-07-12 02:07:14  bash: Adding key /global/max_open_files 131072 with value  to KV store.
2017-07-12 02:07:14  bash: Adding key /osd/osd_journal_size 100 with value  to KV store.
```
We should remove the double quote and make it work.
```txt
2017-07-12 02:06:51  bash: Adding key /auth/cephx with value true to KV store.
true
2017-07-12 02:06:51  bash: Adding key /global/max_open_files with value 131072 to KV store.
131072
2017-07-12 02:06:51  bash: Adding key …
```
=> Fix an error when populating KV store.

ceph-releases/jewel/centos/7/base/Dockerfile, ceph-releases/jewel/fedora/24/base/Dockerfile, ceph-releases/jewel/ubuntu/14.04/base/Dockerfile, ceph-releases/jewel/ubuntu/16.04/base/Dockerfile, ceph-releases/kraken/centos/7/daemon/Dockerfile, ceph-releases/kraken/ubuntu/16.04/daemon/Dockerfile, ceph-releases/luminous/centos/7/daemon/Dockerfile, ceph-releases/luminous/ubuntu/16.04/daemon/Dockerfile
`ADD` appears to download the file and also automatically untar the archive if it ends in .tgz.
The build started to fail because /forego.tgz is a directory.
I'm not sure how many docker versions the file needs to support, if this breaks things for somebody on older versions I'd recommend to remove `ADD` all together and wget it explicitly. This would also slightly reduce the image size if you get+remove the archive within the same layer.
=> Fix forego breaking docker build

ceph-releases/luminous/ubuntu/16.04/daemon/start_mgr.sh
If ceph configuration was created from kvstore the configuration for the
ceph manager daemon must be recreate at each start.
=> Fix configuration of ceph-mgr in case ceph.conf was created from kvstore

examples/kubernetes/generator/templates/ceph/ceph.conf.jinja
Per this issue [1] with jinja2-cli, the appropriate usage for
capturing environment variables is
`{{ environ('FOO', 'somedefault') }}`. Without the format written as such,
environment variables set via `export FOO=somedefault` will not be
reflected in the rendered template.
[1] https://github.com/mattrobenolt/jinja2-cli/issues/31
=> Make ceph.conf.jinja template use environ()

ceph-releases/jewel/ubuntu/14.04/daemon/common_functions.sh, ceph-releases/jewel/ubuntu/14.04/daemon/osd_scenarios/osd_disk_prepare.sh
this `sleep 5` has been added to fix a `no such file or directory`
error but making a call to `wait_for_file()` in
`apply_ceph_ownership_to_disks()` is a better fix.
=> osd_disk_prepare: Replace `sleep 5` by a `wait_for_file` call

examples/kubernetes/README.md
As all the other resources are created on the ceph namespace, it makes sense to create the provisioner on the same namespace.
=> Add missing ceph namespace on RBD provisioner deployment

ceph-releases/jewel/ubuntu/14.04/daemon/osd_scenarios/osd_disk_activate.sh, ceph-releases/jewel/ubuntu/14.04/daemon/variables_entrypoint.sh, ceph-releases/kraken/ubuntu/16.04/daemon/osd_scenarios/osd_disk_activate.sh, ceph-releases/kraken/ubuntu/16.04/daemon/variables_entrypoint.sh, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_disk_activate.sh, ceph-releases/luminous/ubuntu/16.04/daemon/variables_entrypoint.sh
Fixes: https://github.com/ceph/ceph-docker/pull/732 and https://github.com/ceph/ceph-docker/issues/509
=> daemon: fix default array for CRUSH_LOCATION

ceph-releases/jewel/ubuntu/14.04/daemon/start_rgw.sh, ceph-releases/jewel/ubuntu/14.04/daemon/variables_entrypoint.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_rgw.sh, ceph-releases/kraken/ubuntu/16.04/daemon/variables_entrypoint.sh, ceph-releases/luminous/ubuntu/16.04/daemon/start_rgw.sh, ceph-releases/luminous/ubuntu/16.04/daemon/variables_entrypoint.sh
You can now specify on which IP rgw will listen, for that simply set an
IP to RGW_CIVETWEB_IP.
=> rgw: ability to specify bind ip

examples/kubernetes/delete_ceph_cluster.sh
PVs are not namespaced in kubernetes. This script can potentially delete all the other PVs in the cluster. Thus namespacing the deletion of the PVs. Also it would be a good practice to delete the namespace at last.
=> Update teardown script

examples/kubernetes/delete_ceph_cluster.sh
PVs are not namespaced , so we should pick up PVs only from ceph namespace.
=> Update teardown script further

ceph-releases/jewel/ubuntu/14.04/daemon/common_functions.sh, ceph-releases/kraken/ubuntu/16.04/daemon/common_functions.sh, ceph-releases/luminous/ubuntu/16.04/daemon/common_functions.sh
We now limit the depth to 3 which means:
[root@ceph-osd0 ~]# find -L /var/lib/ceph/ -mindepth 1 -maxdepth 3
/var/lib/ceph/bootstrap-osd
/var/lib/ceph/bootstrap-osd/ceph.keyring
/var/lib/ceph/bootstrap-mds
/var/lib/ceph/bootstrap-mds/ceph.keyring
/var/lib/ceph/bootstrap-rgw
/var/lib/ceph/bootstrap-rgw/ceph.keyring
/var/lib/ceph/mon
/var/lib/ceph/mon/ceph-ceph-osd0
/var/lib/ceph/osd
/var/lib/ceph/mds
/var/lib/ceph/mds/ceph-mds-ceph-osd0
/var/lib/ceph/radosgw
/var/lib/ceph/radosgw/ceph-osd0
/var/lib/ceph/tmp
/var/lib/ceph/tmp/ceph-disk.prepare.lock
/var/lib/ceph/mgr
/var/lib/ceph/mgr/ceph-ceph-osd0
/var/lib/ceph/osd-lockbox
/var/lib/ceph/osd-lockbox/6e6cc345-ef0e-45a4-ab31-1fa7399ce51f
/var/lib/ceph/osd-lockbox/2f81eda4-392e-4ea3-b3f5-b55f3661bd4b …
=> daemon: do not chown recursively osd directory

ceph-releases/luminous/ubuntu/16.04/daemon/common_functions.sh, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_disk_activate.sh
With bluestore we changed the partition number to 5 instead because of
db, wal etc.
=> daemon: lockbox partition nb is 5 now

ceph-releases/kraken/ubuntu/16.04/daemon/config.kv.etcd.sh, ceph-releases/luminous/ubuntu/16.04/daemon/config.kv.etcd.sh
We forgot to create the mon key, fixing this.
Closes: https://github.com/ceph/ceph-docker/issues/747
=> daemon: fix populate kv

ceph-releases/jewel/ubuntu/14.04/daemon/start_mds.sh, ceph-releases/kraken/ubuntu/16.04/daemon/start_mds.sh, ceph-releases/luminous/ubuntu/16.04/daemon/start_mds.sh
For some reasons, when the pool does not exist, the stat hangs.
Adding a timeout to the command fixes the issue.
=> fix mds stat hang command

ceph-releases/jewel/ubuntu/14.04/daemon/common_functions.sh, ceph-releases/kraken/ubuntu/16.04/daemon/common_functions.sh, ceph-releases/luminous/ubuntu/16.04/daemon/common_functions.sh
Fixes #750 
While investigating this issue, it appears from the git blame of the file, the error was introduced when a dev cleaned up the shellcheck lining errors. I don't want to suggest any blame, and I'm glad to see that people are interested in maintaining clean, maintainable code. This error could have been caught with unit testing, and ideally, I'd like to add unit tests starting with this code. I can see a few ways to proceed, however, and I'd like to discuss the community's interest and thoughts. Here are my thoughts so far:
- With a codebase of scripts this large, it may be more appropriate to convert code to Python and add unit tests for all Python code. Python has strong unit testing and libraries and seems more suitable for a project that is this size and growing larger. This …
=> Fix improper following of device symlinks

ceph-releases/luminous/ubuntu/16.04/daemon/config.static.sh
Logging inside the container is not useful since it writes to the
overlayfs partition, resulting in potential performance degradation on
the container.
If you need to check the logs, just look at journald.
=> daemon: do not log inside the container

ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_disk_activate.sh
Fix error while opening encrypted part for bluestore scenario:
`authentication error (22) Invalid argument`
=> osd_disk_activate: fix osd_bluestore with dmcrypt activation error

README.md
Currently shields.io does not support tags but it's ongoing.
See progress here: https://github.com/badges/shields/issues/935
=> contrib: add flag for docker hub status

ceph-releases/luminous/ubuntu/16.04/daemon/common_functions.sh
Sometimes (typically after a prepare) the LUKS device is already open.
If that's the case ceph-disk will try to open it and complain.
Quick fix for now, will work on a better way to handle that.
=> daemon; fix dmcrypt opening partition

ceph-releases/luminous/ubuntu/16.04/daemon/start_mon.sh
This fix the rbd keyring that is not registered in ceph for rbdmirror
nodes.
=> mon: Add rbd keyring to mon keyring

ceph-releases/luminous/ubuntu/16.04/daemon/debug.sh
When running the container with DEBUG=verbose, it's also useful to know
the env var of the container.
=> daemon: show env var of the container

ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_disk_activate.sh
`ceph-disk list <device>` returns:
```
/dev/sdb :
/dev/sdb1 ceph data, prepared, cluster test, osd.1, journal /dev/sdc2
```
therefore, `awk '/ceph journal/ {print $1}'` won't catch the actual
associated journal partition.
This commit fixes it by using sed instead.
=> osd_disk_activate: fix wrong catching of journal part

ceph-releases/luminous/centos/7/daemon/disk_list.sh, ceph-releases/luminous/rhel/7.3/daemon/disk_list.sh, ceph-releases/luminous/ubuntu/16.04/daemon/common_functions.sh, ceph-releases/luminous/ubuntu/16.04/daemon/config.kv.etcd.sh, ceph-releases/luminous/ubuntu/16.04/daemon/config.static.sh, ceph-releases/luminous/ubuntu/16.04/daemon/debug.sh, ceph-releases/luminous/ubuntu/16.04/daemon/disk_introspection.sh, ceph-releases/luminous/ubuntu/16.04/daemon/disk_list.sh, ceph-releases/luminous/ubuntu/16.04/daemon/entrypoint.sh.in, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_activate_journal.sh, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_directory.sh, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_disk_activate.sh, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_disk_prepare.sh, ceph-releases/luminous/ubuntu/16.04/daemon/start_mds.sh, ceph-releases/luminous/ubuntu/16.04/daemon/start_mgr.sh, ceph-releases/luminous/ubuntu/16.04/daemon/start_nfs.sh, ceph-releases/luminous/ubuntu/16.04/daemon/start_rbd_mirror.sh, ceph-releases/luminous/ubuntu/16.04/daemon/start_rgw.sh, ceph-releases/luminous/ubuntu/16.04/daemon/variables_entrypoint.sh
ceph-disk list output is really hazardous, so we now have a simpler
scenario to detect journal, block.wal, block.db. It's meant to be used
by ceph-ansible (or other tools) that needs to run the osd activation
stage. For this, it needs to know some variables about the OSD itself.
=> daemon: ceph-disk list replacement tool

ceph-releases/luminous/ubuntu/16.04/daemon/common_functions.sh, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_disk_prepare.sh
We don't need to call close_encrypted_part when not using dmcrypt; fixes
error:
Device 635e0cbc-5b37-49f0-8159-8a8fdf65d648 is not active.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1495979
=> daemon: only call close_encrypted_part on dmcrypt

ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_disk_prepare.sh
Even if it runs with || true and won't fail this is really confusing for
users.
=> daemon: do not run umount lockbox

ceph-releases/luminous/ubuntu/16.04/daemon/common_functions.sh, ceph-releases/luminous/ubuntu/16.04/daemon/disk_list.sh, ceph-releases/luminous/ubuntu/16.04/daemon/entrypoint.sh.in, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_disk_activate.sh, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_disk_prepare.sh
followup of https://github.com/ceph/ceph-docker/pull/789/files
=> Ceph disk lit 2

ceph-releases/luminous/ubuntu/16.04/daemon/common_functions.sh
This fixes the case where a disk is specified with by-path, blkid can
not resolve part uuid from disks like
/dev/disk/by-path/pci-0000:00:01.1-ata-1.0
The command was actual wrong has it'll append '1' at the end of
/dev/disk/by-path/pci-0000:00:01.1-ata-1.0
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1494127
=> daemon: use dev_part for DATA_UUID

examples/kubernetes/README.md, examples/kubernetes/ceph-mds-v1-dp.yaml, examples/kubernetes/ceph-mon-check-v1-dp.yaml, examples/kubernetes/ceph-mon-v1-dp.yaml, examples/kubernetes/ceph-mon-v1-ds.yaml, examples/kubernetes/ceph-osd-activate-v1-ds.yaml, examples/kubernetes/ceph-osd-prepare-v1-ds.yaml, examples/kubernetes/ceph-osd-v1-ds.yaml, examples/kubernetes/ceph-rgw-v1-dp.yaml, examples/kubernetes/create_secrets.sh, examples/kubernetes/generator/README.md, examples/kubernetes/generator/generate_secrets.sh
Make changes to key generator, README docs, and kubernetes config yaml
files to support bootstrapping RBDs.
=> Add RBD bootstrap key support to kubernetes

generate-dev-env.sh
The generate-dev-env.sh script should not return failure on the final
`popd` if a preceding `pushd` was never executed.
=> Fix generate-dev-env returning failure on success

ceph-releases/luminous/ubuntu/16.04/daemon/config.kv.etcd.sh
The static config creates a keyring for RBD_MIRROR_BOOTSTRAP_KEYRING,
which is used by rbd-mirror and also by the start script for the
mon. The etcd config was not creating this keyring, preventing mon and
rbd-mirror from starting.
Add RBD_MIRROR_BOOTSTRAP_KEYRING to the list of keyrings to generate
when using etcd.
=> luminous: Create the bootstrap-rbd keyring when using etcd

ceph-releases/luminous/ubuntu/16.04/daemon/common_functions.sh
This was a leftover, ceph-disk list returns
```
root@257b2b1826f2:/# ceph-disk list /dev/sdc | awk '/ceph block.db/
{print $1}'
/dev/sdc1
/dev/sdc3
```
So we have 2 values where we expect one. Now we use start_disk_list
which will report the right device.
=> daemon: do not rely on ceph-disk list for bluestore dmcrypt

tox.ini
We now test stable-3.0 with ansible 2.3.1 and also we added the new osd
scenarios from with https://github.com/ceph/ceph-ansible/pull/2000
=> [skip ci] ci: better coverage with new osd scenarios

ceph-releases/jewel/ubuntu/14.04/daemon/config.k8s.sh, ceph-releases/jewel/ubuntu/14.04/daemon/start_mon.sh, ceph-releases/jewel/ubuntu/14.04/daemon/variables_entrypoint.sh, ceph-releases/luminous/ubuntu/16.04/daemon/config.k8s.sh, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_directory.sh, ceph-releases/luminous/ubuntu/16.04/daemon/start_mon.sh, ceph-releases/luminous/ubuntu/16.04/daemon/variables_entrypoint.sh
- not use hard coded label selector in kubectl
- don't auth add if keyring is missing
- init luminous osd directory
=> do not use hard coded label selector in kubectl

ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_directory.sh
Previously OSDs only started correctly when using the default cluster name.
=> luminous: Respect the configured cluster name when starting OSDs

ceph-releases/luminous/ubuntu/16.04/demo/ceph_demo
* change selinux for the working dir when selinux is set in Enforcing
mode
* make ceph-nano work with old docker version, the volume syntaxt is
different
=> [skip ci]  nano: multiple enhancements

ceph-releases/luminous/rhel/7.3/daemon/README.md, ceph-releases/luminous/ubuntu/16.04/daemon/README.md, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_disk_prepare.sh, ceph-releases/luminous/ubuntu/16.04/daemon/osd_scenarios/osd_disks.sh, ceph-releases/luminous/ubuntu/16.04/daemon/variables_entrypoint.sh
It is too dangerous to have this kind of capability, especially if there
is automation in place that uses this option.
Prior to deploy an OSD you must make sure the device is in a proper
shape. Also, ceph-disk prepare will create a GPT label if there is no
label on the drive.
=> daemon: remove OSD_FORCE_ZAP option

ceph-releases/luminous/ubuntu/16.04/daemon/zap_device.sh
Instead of requiring a single device when zapping we can now use
"all_ceph_disks" to zap all ceph devices.
=> [skip ci] dameon: ability to zap all ceph disks

ceph-releases/jewel/ubuntu/14.04/daemon/confd/conf.d/ceph.conf.toml.in, ceph-releases/jewel/ubuntu/14.04/daemon/confd/templates/ceph.conf.tmpl
This should enable deployments of clients with client specific configurations, such as a RGW deployment with one RGW instance serving the s3 API and another serving the s3websites API.
The config:
```
[client]
keyring = /etc/ceph/local1.client.admin.keyring
[client.rgw.rgwstatic]
rgw_dns_s3website_name = "hargwwebsite"
rgw_enable_apis = s3website
rgw_enable_static_website = "true"
rgw_host = "rgwstatic"
```
ceph.defaults:
```
/client_host/client.rgw.rgwstatic/rgw_host "rgwstatic"
/client_host/client.rgw.rgwstatic/rgw_enable_static_website "true"
/client_host/client.rgw.rgwstatic/rgw_dns_s3website_name "hargwwebsite"
/client_host/client.rgw.rgwstatic/rgw_enable_apis "s3website"
```
=> daemon: Adds support for client config subsections with confd

ceph-releases/luminous/ubuntu/16.04/daemon/start_rbd_mirror.sh
rbd-mirror needs to use multiple keyrings to connect to multiple
clusters. Passing the -k argument prevents it from doing so. It finds
the correct keyring on its own via the -n argument, so the -k is
unnecessary anyhow.
=> luminous: Don't provide a keyring argument to rbd-mirror

ceph-releases/jewel/ubuntu/14.04/daemon/zap_device.sh, ceph-releases/luminous/ubuntu/16.04/daemon/zap_device.sh
devices like : `/dev/xvda` don't match the current regexp, therefore the
purge fails on AWS environment.
=> zap: fix issue on AWS environment

examples/kubernetes/README.md
Without which pool it maps to, it's confusing what is going on. Also the claim wont actually mount without the userId and secret. I kept getting `failed to get secret from ["claimnamespace"/""]`
=> Added required fields and also pool

examples/kubernetes/README.md
RBAC is now part of k8s, so for simplicity I linked to the non RBAC role version
=> Update the URL. 404 for current.

ceph-releases/luminous/centos/7/daemon/Dockerfile, ceph-releases/luminous/centos/7/daemon/clean_container.sh, ceph-releases/luminous/rhel/7.3/daemon/Dockerfile, ceph-releases/luminous/rhel/7.3/daemon/clean_container.sh, ceph-releases/luminous/ubuntu/16.04/daemon/Dockerfile, ceph-releases/luminous/ubuntu/16.04/daemon/clean_container.sh
The actual container is running a pretty classic ubuntu container full of useless stuff.
As a result the container is pretty big on the filesystem.
This patch aims at gaining disk's space by using the following techniques:
- stripping raw binaries/libraries
- removing useless data files like documentation
- removing useless binaries
- removing useless packages like perl
- removing testing code/binaries
- removing pre-compiled python files as we nearly don't use them
- compressing debugging tools
- clearing log files
Note the stripping process is done in two passes :
- first one targets "easy" stuff
- second one targets more tricky such that may be discussed if some
issue occurs
A typical output looks like the following :
Step 18 : RUN bash "/clean_container.sh"
---> Running in …
=> Cleaning container

images/Makefile, images/base/Dockerfile, images/base/Dockerfile.rootfs, images/base/Dockerfile.rootfs-centos, images/base/Dockerfile.rootfs-opensuse, images/base/Dockerfile.rootfs-rhel, images/base/Dockerfile.rootfs-ubuntu, images/base/Makefile, images/daemon-base/Dockerfile.luminous-ubuntu, images/daemon-base/Makefile, images/daemon/Dockerfile.luminous-ubuntu, images/daemon/Makefile, images/image.mk
In an attempt to get more alignment between upstream Ceph and the Rook project, I've started the work to use rook-style images within the ceph-container project. The approach is described in https://github.com/rook/rook/issues/1404. It also borrows some of the tricks in #877 to reduce the image sizes further.
I'm opening up this for early review, its not ready to merge nor has it been tested with Rook. I took the following path:
- Use Makefiles to build images
- Use multiple images for better factoring (base os, ceph daemon base, ceph daemon)
- Reduce the size of the images to the extent possible
- Support multiple base OS flavors as does ceph-container today.
- Reduce the duplication of code and DockerFiles
- Support for multiple arch `amd64` and `arm64`
- Provide minimal clean ceph …
=> [DNM] new approach of building images

ceph-releases/luminous/ubuntu/16.04/daemon/start_mgr.sh
The dashboard is disabled in any cases if it's not in the ENABLED_MODULES variable
=> Remove code that didn't work anymore

ceph-releases/luminous/opensuse/42.3/daemon/Dockerfile
The luminous/openSUSE dockerfile needed to be updated with the latest location of package repos. And there were a few other updates as well. Like `s3cmd` actually needed to be installed.
=> lum:openSUSE: Dockerfile updates

ceph-releases/luminous/ubuntu/16.04/daemon/Dockerfile
ceph-volume requires sudo, and supports LVM.  This change adds those packages to the image so that we can make progress toward deprecating ceph-disk.
=> Add sudo and lvm packages for ceph-volume

ceph-releases/luminous/ubuntu/16.04/daemon/disk_list.sh
since the `mount_ceph_data()` function in disk_list.sh is now looking
for the partuuid to mount it, we must use `/dev/disk/by-partuuid`.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1537980
=> disk_list: fix wrong path to device

ceph-releases/luminous/ubuntu/16.04/daemon/start_nfs.sh
while still logging the daemon both to STDOUT and the location
configured in the daemon's configuration file.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1546192
=> Exit CephNFS with error if ganesha daemon fails

ceph-releases/jewel/ubuntu/14.04/daemon/variables_entrypoint.sh, ceph-releases/luminous/ubuntu/16.04/daemon/variables_entrypoint.sh
In addition to f8f783ba, this commits moves the `MON_DATA_DIR` variable
so it can be properly defined with its right value.
=> variables: move hostname and names variables

contrib/build-push-ceph-container-imgs.sh
sudo does not have a tty for the running user, also the 'make'
invocation will not call sudo.
=> ci: build and push, no invoke sudo

examples/kubernetes/ceph-mds-v1-dp.yaml, examples/kubernetes/ceph-mgr-dashboard-v1-svc.yaml, examples/kubernetes/ceph-mgr-prometheus-v1-svc.yaml, examples/kubernetes/ceph-mgr-v1-dp.yaml, examples/kubernetes/ceph-mon-v1-dp.yaml, examples/kubernetes/ceph-rbac.yaml, examples/kubernetes/rbd-provisioner/README.md, examples/kubernetes/rbd-provisioner/clusterrole.yaml, examples/kubernetes/rbd-provisioner/clusterrolebinding.yaml, examples/kubernetes/rbd-provisioner/deployment.yaml, examples/kubernetes/rbd-provisioner/role.yaml, examples/kubernetes/rbd-provisioner/rolebinding.yaml, examples/kubernetes/rbd-provisioner/serviceaccount.yaml, examples/kubernetes/rbd-provisioner/storage-class.yaml
We have recently upgraded our cluster to Kubernetes 1.9 and Ceph Luminous. This requires a few modifications and updates (RBAC, missing and updated manifests, rbd provsioner and storage class). This is based on recent updates to the [ceph config in rcll-sim-cluster](https://github.com/timn/rcll-sim-cluster/tree/master/kubernetes/ceph).
=> [skip ci] Update for Kubernetes 1.9 and Luminous

maint-lib/stagelib/envglobals.py, maint-lib/stagelib/git.py
Previously, `file_is_dirty('')` was used to determine if the branch had
any dirty files, but because of the regex match in the method, this
cannot be guaranteed to return as expected. Add a `branch_is_dirty`
method to fix this.
=> staging: fix bug when checking for dirty branch

CONTRIBUTING.md, README.md
The readme after all of the great documentation we wrote for the new
project structure was huge. Split it into a readme useful for most
people who want to casually use/understand the project and a new
`CONTRIBUTING.md` aimed at developers.
=> [skip ci] Split part of the readme into CONTRIBUTING.md

CONTRIBUTING.md, Makefile, README.md, maint-lib/flavors-modified-vs-master.py
Typing "FLAVORS_TO_BUILD" on the commandline a lot of times is tiring.
Changing this to just "FLAVORS" makes this easier, and the name is still
adequate.
This PR is built on top of #930
=> [skip ci] FLAVORS_TO_BUILD is too damn long

Makefile, ceph-releases/ALL/opensuse/42.3/__OS_REPO__, ceph-releases/ALL/opensuse/__DOCKERFILE_MAINTAINER__, ceph-releases/ALL/opensuse/__DOCKERFILE_POSTINSTALL_CLEANUP__, ceph-releases/ALL/opensuse/__ZYPPER_INSTALL__, ceph-releases/ALL/opensuse/__ZYPPER_UPDATE__, ceph-releases/ALL/opensuse/__ZYPPER__, ceph-releases/ALL/opensuse/daemon-base/__CEPH_REPO__, ceph-releases/ALL/opensuse/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/ALL/opensuse/daemon-base/__RADOSGW_PACKAGE__, ceph-releases/ALL/opensuse/daemon/__BUILD_DEPS_REPO__, ceph-releases/ALL/opensuse/daemon/__CLOUD_REPO__, ceph-releases/ALL/opensuse/daemon/__DOCKERFILE_INSTALL__
After changing to the new project structure, this should add luminous-opensuse-42.3 build support.
=> [skip ci] Add luminous-opensuse-42.3

CONTRIBUTING.md
Add commit guidelines to contributing documentation.
=> [skip ci] doc: add commit guidelines

contrib/build-push-ceph-container-imgs.sh
It is expected that "git describe --exact-match HEAD --tags --long"  can
fail so we don't want to exist on an error. For this we unset -e then
re-activate it.
=> [skip ci] ci: unset -e on expected failure

Makefile, contrib/build-push-ceph-container-imgs.sh
This PR is about 
- controlling the parallelism of the build.parallel target to avoid saturating build hosts
- adding a push.parallel to speed up the push process
=> Improving parallelism

src/daemon/start_nfs.sh, tests/tox.sh
Fixes the start error: ganesha.nfsd-182[main] create_log_facility :LOG
:CRIT :Cannot create new log file (/var/log/ganesha/ganesha.log),
because: No such file or directory
=> nfs: create ganesha log directory

README.md
Docker Hub automated builds are no more, so these flags have been
irrelevant.
=> [skip ci] README: remove some status flag

ceph-releases/ALL/opensuse/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/ALL/opensuse/daemon/__DOCKERFILE_INSTALL__
`zypper info` does not work in environments without internet access. Use
'rpm --query` in place of this to suppor these build environments.
=> [DNM] opensuse: Change package info from zypper to rpm

maint-lib/flavors-modified-vs-master.py
We must fetch origin master to make sure our understanding of
origin/master's content is up to date. If we don't do this we will find
irrelevant/wrong results.
=> make: improve flavor modified

Makefile
Ignore duplicating IDs and clean after build
=> [skip ci] Updating clean process

src/daemon/osd_scenarios/osd_disk_activate.sh
Regarding #893, This fix have been tested in my local
=> Fix osd id can't be found when osd device path used "by-id" format

maint-lib/stagelib/replace.py
Staging was not failing when an environment variable intended to be used
as a variable replacement was unset. Make staging exit with error.
=> staging: fail when env var replacement not set

maint-lib/flavors-modified-vs-master.py
This fixes the script integration by silencing any output.
=> maint-lib: make git fetch silent

Makefile, maint-lib/makelib.mk
I'd like to support the case for building/staging images with different tag names. This comes in 2 parts
1. Allowing the user to change the tag itself
2. Allowing the user to specify a tag without a registry
This is built off of #979 (shorten flavor spec)
-----
```
> make FLAVORS=luminous,opensuse,42.3 DAEMON_BASE_TAG=my-daemon-base-img DAEMON_TAG=my-daemon-img REGISTRY='' stage
CEPH_VERSION      : luminous
ARCH              : x86_64
BASEOS_REG        : _
BASEOS_REPO       : opensuse
BASEOS_TAG        : 42.3
IMAGES_TO_BUILD   : daemon-base daemon
STAGING_DIR       : staging/luminous-opensuse-42.3-x86_64
RELEASE           : make-allow-user-defined-image-names
DAEMON_BASE_IMAGE : my-daemon-base-img
DAEMON_IMAGE      : my-daemon-img
``` …
=> make: allow user-defined image tags

.travis.yml, contrib/build-push-ceph-container-imgs.sh, tests/tox.sh
CentOS is the distro that currently has:
* the best CI coverage in terms of functional tests
* all the packages for all the various ceph projects
So this is natural to us to change our latest image to poin to CentOS
instead of Ubuntu.
Closes: https://github.com/ceph/ceph-container/issues/984
=> [skip ci] contrib: use centos as latest instead of ubuntu

Makefile, maint-lib/makelib.mk
In an environment where users have custom base containers that they want
to use with ceph-container, allow them to override BASE_IMAGE.
=> make: Allow user to specify BASE_IMAGE

ceph-releases/ALL/daemon/__WEB_INSTALL_CONFD__, ceph-releases/ALL/daemon/__WEB_INSTALL_ETCDCTL__, ceph-releases/ALL/daemon/__WEB_INSTALL_KUBECTL__
Confd/etcd/kubectl didn't got updated since a very long while and mostly because of the complex tree/file architecture.
Since we have the new tree & build tools, its much more easier to update versions for all flavors.
This PR offer to bump :
- etcd from 2.2.4 to 3.2.18
- confd from 0.10.0 to 0.15.0
- kubectl from 1.6.0 to 1.8.11
=> Updating confd/etcd/kubectl

CONTRIBUTING.md, maint-lib/stagelib/replace.py, tests/stage-test/src/daemon-base/src-daemon-base-test-file, tests/stage-test/stage-key/daemon-base/src-daemon-base-test-file, tests/stage-test/test_staging.sh
__ENV_[VAR]__s are now allowed to contain nested __ENV_[VAR]__s as well
as __VARIABLE_FILE__s.
I initially thought that there shouldn't be the need for nested
__ENV_[VAR]__s, but I have encountered a case where I want to use the
__ENV_[HOST_ARCH]__ var within another __ENV_[VAR]__.
=> staging: allow nested env replacements

src/daemon-base/Dockerfile
When building the code with an empty CEPH_POINT_RELEASE, the build fails
with the following message :
Error response from daemon: ENV must have two arguments
This was introduced by commit 18c0ba745c29b9834c3b4e04972e41519376337f.
If CEPH_POINT_RELEASE is empty, the Dockerfile is missing a parameter.
This patch simply add some double quotes around the variable to avoid this.
From the container itself, it looks like :
[root@2beae00c96d3 /]# env |grep CEPH
CEPH_VERSION=luminous
CEPH_POINT_RELEASE=
[root@2beae00c96d3 /]#
=> Dockerfile: Don't fail if CEPH_POINT_RELEASE is unset

ceph-releases/ALL/opensuse/__DOCKERFILE_INSTALL__
cat'ing the zypper log on fail gets to be overwhelming. The last 300
lines should be sufficient for most debugging.
=> [skip ci] opensuse: tail the zypper log instead of cat

contrib/build-push-ceph-container-imgs.sh
return can only be used inside a function
=> [skip ci] do not use return when not in a function

ceph-releases/ALL/opensuse/__DOCKERFILE_INSTALL__
The appropriate ordering of commands is to do update before refresh.
=> opensuse: do zypper update before zypper refresh

src/__DOCKERFILE_POSTINSTALL_TWEAKS__, src/daemon-base/Dockerfile
This commit introduces 'tweaks', tweak is a new capability that allows
you to configure the container OS. Typically this makes a particular
service more container aware or change its default configuration so it
can work better in containers.
Its first implementation is for configuring LVM.
lvm when creating devices tries to talk to udev. In a container this is
not possible and lvm can not reach udev on the host. Disabling the sync
and the rules help us getting through the lv creation.
Later to scan the lv on the host you can use lvs --readonly
=> [skip ci] introduce post install tweaks

src/daemon/demo.sh
When running demo with cn (ceph nano) someone can decide to go with a
directory different from the traditional /var/lib/ceph. If so the
bootstrap will fail if osd_data is not changed.
=> [skip ci] demo: add "osd_data" config to ceph.conf

maint-lib/makelib.mk, maint-lib/stagelib/envglobals.py, src/STAGING_ENV_VARS.md, tests/stage-test/stage-key/staging_output.txt, tests/stage-test/test_staging.sh
In prep for making BASEOS_REG a tunable, rename it to BASEOS_REGISTRY so
the variable is more clear.
=> staging: rename BASEOS_REG to BASEOS_REGISTRY

Makefile, maint-lib/makelib.mk
There could be some confusion about whether `REGISTRY` refers to the
base registry from which the base image is pulled or whether it is the
repository with which the build images will be tagged. The intention is
that it is the latter. Clarify the confusion by changing `REGISTRY` to
`TAG_REGISTRY`.
=> make: rename REGISTRY to TAG_REGISTRY

src/daemon/start_mgr.sh
We don't need to use the admin key for work with modules. The mgr key
has enough permissions for that.
Also removed the uncessary ceph -v command. Leftover.
=> mgr: use the mgr key to enable module

Makefile, ceph-releases/ALL/rhel7/__DOCKERFILE_CLEAN_COMMON__, ceph-releases/ALL/rhel7/__DOCKERFILE_MAINTAINER__, ceph-releases/ALL/rhel7/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/ALL/rhel7/daemon-base/__DOCKERFILE_POSTINSTALL_CLEANUP__, ceph-releases/ALL/rhel7/daemon-base/__DOCKERFILE_PREINSTALL__, ceph-releases/ALL/rhel7/daemon-base/__ISCSI_PACKAGES__, ceph-releases/ALL/rhel7/daemon-base/__RADOSGW_PACKAGE__, ceph-releases/ALL/rhel7/daemon/__DOCKERFILE_INSTALL__, ceph-releases/ALL/rhel7/daemon/__DOCKERFILE_POSTINSTALL_CLEANUP__, ceph-releases/ALL/rhel7/daemon/__DOCKERFILE_PREINSTALL__, ceph-releases/ALL/rhel7/daemon/install.sh
This commit is about adding the necessary files for building a RHEL7 based image.
The main differences with the Centos image:
- no cleaning to keep packages untouched
- /var/log is cleaned up
- only use RHEL repositories (to be added by the buildsystem)
- specific LABELs
- disabling subscription-manager during the build
=> [skip ci] ceph-releases: Adding rhel7

ceph-releases/ALL/opensuse/__DOCKERFILE_INSTALL__, ceph-releases/ALL/opensuse/__ZYPPER__
The build may (will) fail if the repos added don't have trusted keys.
=> opensuse: auto add repo keys on repo add

ceph-releases/ALL/opensuse/__DOCKERFILE_INSTALL__
When builds fail, the large run statement makes it hard to track what
was the command on which the build failed. Add echo statements to help.
=> opensuse: Add debug echo statemets to install

ceph-releases/ALL/centos-arm64/__DOCKERFILE_MAINTAINER__, ceph-releases/ALL/centos-arm64/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/ALL/centos-arm64/daemon-base/__DOCKERFILE_POSTINSTALL_CLEANUP__, ceph-releases/ALL/centos-arm64/daemon-base/__DOCKERFILE_PREINSTALL__, ceph-releases/ALL/centos-arm64/daemon-base/__RADOSGW_PACKAGE__, ceph-releases/ALL/centos-arm64/daemon/__CONFD_PACKAGE__, ceph-releases/ALL/centos-arm64/daemon/__DOCKERFILE_INSTALL__, ceph-releases/ALL/centos-arm64/daemon/__DOCKERFILE_POSTINSTALL_CLEANUP__, ceph-releases/ALL/centos-arm64/daemon/__DOCKERFILE_PREINSTALL__, ceph-releases/ALL/centos-arm64/daemon/__FOREGO_PACKAGE__, ceph-releases/ALL/centos-arm64/daemon/__WEB_INSTALL_CONFD__, ceph-releases/ALL/centos-arm64/daemon/disabled_scenario, contrib/build-push-ceph-container-imgs-arm64.sh, contrib/build-push-ceph-container-imgs.sh
This commit is about adding support for arm64 for centos.
In a perfect world, supporting a new arch is supposed to get anything
changed.
We are in a situation where the build of centos on ARM64 trigger the
following issues :
- nfs-ganesha & tcmu-runner packages are not available
- confd is not available from github
This commit is a little bit special as it try to workaround this
situation. It does create a centos-arm64 OS which links most of the
files from centos.
In this project, we are not supposed to have symlinks but as we are
using the same OS with a very few constrains specific to this arch,
Blaine & I considered that was the best approach.
The differences with centos are :
- __GANESHA_PACKAGES__ is empty to avoid it to be installed
- __WEB_INSTALL_CONFD__ is set to /bin/true to …
=> [skip ci] ceph-releases: Adding centos-arm64

src/daemon/Dockerfile
As per the actual configuration, it is useless defining VOLUME[] in our
Dockerfile.
=> [skip ci] daemon: Removing VOLUME[] from Dockerfile

ceph-releases/ALL/opensuse/__DOCKERFILE_INSTALL__, ceph-releases/ALL/opensuse/__DOCKERFILE_POSTINSTALL_CLEANUP__
When the build fails on the zypper clean step, the dockerfile does not
output the zypper log. Move the zypper clean instruction from
`__DOCKERFILE_POSTINSTALL_CLEANUP__` to the end of `__DOCKERFILE_INSTALL__`
to gain the zypper log output from the install code.
=> opensuse: move zypper clean to get debugging

ceph-releases/ALL/rhel7/daemon-base/__DOCKERFILE_PREINSTALL__
The first commit in this PR changes the component name from "-docker" to "-container".
The second commit in this PR temporarily hardcodes the release value to "7".
Ordinarily OSBS will dynamically set the "release" label to the
proper value (see https://github.com/projectatomic/atomic-reactor/blob/master/atomic_reactor/plugins/pre_bump_release.py)
When the component name changes like this, OSBS will not know that the last release was "6" in order to bump it to "7". We must hardcode "release" for our first rhceph-rhel7-container build.
(We can revert this commit when we have the first rhceph-rhel7-container non-scratch build present in RH's downstream build system.)
=> ceph-releases/rhel7: rename component to "-container"

ceph-releases/jewel/daemon/common_functions.sh, ceph-releases/kraken/daemon/common_functions.sh, src/daemon/common_functions.sh
/etc/ceph wasn't beeing checked properly so now we check the length of
the output to see if there are any Ceph files.
=> [skip ci] common: fix detect_ceph_files function

src/daemon/demo.sh
We don't have official images before Jewel so it's safe to make an
exception only for this.
=> [skip ci] demo: do not bootstrap mgr on jewel

ceph-releases/jewel/daemon/config.static.sh
Otherwise ceph will never be happy.
=> [skip ci] demo: jewel osd pool default size = 1

src/daemon/demo.sh
In jewel version and earlier we need to add the OSD to the crush
hierarchy manually, newer versions do that on startup.
=> [skip ci] demo: add osd to crush

contrib/build-push-ceph-container-imgs-arm64.sh
Prior to this commit we were getting the wrong name for the image tags.
We had "luminous-centos-arm64-7-aarch64" which was wrong.
luminous-centos-7-aarch64 is what we need.
Ultimately we will get master-XXXX-luminous-centos-7-aarch64
=> [skip ci] contrib: fix arm64 img script

contrib/build-push-ceph-container-imgs-arm64.sh
ed708988c1ec18ff5cb1a8bb70fd76bc80e515bf changed the variable names and
decoupled them too so let's use the right variable.
=> [skip ci] contrib: fix arm64 build with the new syntax

ceph-releases/ALL/centos/daemon-base/__ISCSI_PACKAGES__, contrib/build-push-ceph-container-imgs-arm64.sh, contrib/build-push-ceph-container-imgs.sh
Let arm64 script override push_ceph_imgs_latests and also use return and
not 'True' which does not exist in bash as opposed to 'true'.
=> [skip ci] contrib: override push_ceph_imgs_latests function

ceph-releases/ALL/centos-arm64/daemon-base/__DOCKERFILE_VERIFY_PACKAGES__, ceph-releases/ALL/centos-arm64/daemon/__DOCKERFILE_VERIFY_PACKAGES__, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_VERIFY_PACKAGES__, ceph-releases/ALL/centos/daemon/__DOCKERFILE_POSTINSTALL_CLEANUP__, ceph-releases/ALL/centos/daemon/__DOCKERFILE_VERIFY_PACKAGES__, ceph-releases/ALL/opensuse/__DOCKERFILE_POSTINSTALL_CLEANUP__, ceph-releases/ALL/opensuse/__DOCKERFILE_VERIFY_PACKAGES__, ceph-releases/ALL/rhel7/daemon-base/__DOCKERFILE_VERIFY_PACKAGES__, ceph-releases/ALL/rhel7/daemon/__DOCKERFILE_VERIFY_PACKAGES__, ceph-releases/ALL/ubuntu/daemon-base/__DOCKERFILE_VERIFY_PACKAGES__, ceph-releases/ALL/ubuntu/daemon-base/__EXTRA_POSTINSTALL_CLEANUP__, ceph-releases/ALL/ubuntu/daemon/__DOCKERFILE_VERIFY_PACKAGES__, ceph-releases/ALL/ubuntu/daemon/__EXTRA_POSTINSTALL_CLEANUP__, src/daemon-base/Dockerfile, src/daemon/Dockerfile
It is most safe to check that no packages have been cleaned after the
cleaning process is over, as a flavor may remove packages at any point
during cleaning.
Add a `__DOCKERFILE_VERIFY_PACKAGES__` step to the daemon and base
Dockerfiles after the cleaning step has finished to accomplish this.
Move all flavor verification steps to a corresponding
`__DOCKERFILE_VERIFY_PACKAGES__` variable file.
I did a `make build.all`, and all flavors built successfully; however, rhel7 is not in the all list and didn't get tested.
=> Dockerfiles: Move package verification after clean

src/daemon-base/Dockerfile, src/daemon/Dockerfile
This fixes a bug I missed in commit 11883989ec3124a2e88c74bf45d668a8b4d7229d
If iSCSI packages is left blank, the Dockerfile's verify packages step
may produce code that ends in a trailing `\` character, which will cause
the build to fail. Fix this by adding a final `&& echo ...` message.
`/bin/true` will work just as well, but the echo may be more useful for
debugging.
=> images: fix bug if iSCSI packages left blank

contrib/build-push-ceph-container-imgs.sh
This is needed in order to test the manifest subcommand
=> [skip ci] contrib: enable experimental docker cli

contrib/build-push-ceph-container-imgs.sh
before this commit we were activating the feature in the wrong file.
config.json is the right one.
=> [skip ci] contrib: rework enable_experimental_docker_cli

contrib/build-push-ceph-container-imgs.sh
We must log first so this creates the config.json file, then we enable
the experimental cli feature.
=> [skip ci] contrib: loging to the registry before enabling the cli

contrib/build-push-ceph-container-imgs.sh
It seems that the file gets somehow created after pull/push so we edit
it (config.json) after that.
=> contrib: move enable_experimental_docker_cli before creating manifest

Makefile, contrib/build-push-ceph-container-imgs.sh
Any images not set in the `FLAVORS` default variable in the Makefile
will not be built and pushed upstream. This currently only includes
opensuse, but it may include more in the future.
Now use `make build.all` to build and push *all* images, not just the
default values for `FLAVORS`.
=> images: build and push all images not just default

Makefile
Fixes a missing separator error when running make.
=> makefile: Convert bad spaces to a tab

ceph-releases/ALL/centos-arm64/daemon/__WEB_INSTALL_CONFD__, ceph-releases/ALL/daemon/__WEB_INSTALL_CONFD__
In 0.16.0, issue #641 have been closed so confd is now available for arm64 hosts.
This commit bumps the release to 0.16.0 for all and remove the empty
__WEB_INSTALL_CONFD__ of centos-arm64 to let it use the global one.
=> confd: Updating to 0.16.0

README.md
This PR just fix a broken link to the `ceph-daemon` source directory on README.md.
=> Fix a broken link on README.md

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
This adds issue and pull request templates.
The following issue templates are available:
* Bug report
* Feature request
And a "default" one which contains both bug report and feature request in one.
Let me know what you think and/or if it should just be the PR template.
An example of how the issue type selection looks, can be found in this example repository: https://github.com/galexrt/github-issue-templates. Just go to the project, go to "Issues" and then "New issue".
Resolves #939.
/cc @BlaineEXE
[skip ci]
=> github: Added issue and pull request templates

Makefile
We don't always have packages for ubuntu and we can't hold a release
just because of that. So until we get a proper maintainer for the
ubuntu image we will stop building and pushing the image. However it's
up to anyone to build it locally.
Resolves #
Checklist:
=> [skip ci] contrib: stop building and pushing ubuntu on mimic

contrib/build-push-ceph-container-imgs.sh
The actual code is using the .all target which rebuilds all possibles FLAVORS.
In this part of the project, we only want to build the supported flavors encoded in the FLAVORS variable.
This patch switch from the .all to the .parallel targets to avoid using ALL_BUILDABLE_FLAVORS.
Resolves #
Checklist:
=> [skip ci] build-push-ceph-container-imgs.sh: Building only FLAVORS

contrib/build-push-ceph-container-imgs-arm64.sh
Add arm64 support to the images we build and push on the docker
registry.
=> [skip ci] build and push mimic images for arm64

contrib/build-push-ceph-container-imgs.sh
For the ceph-ansible luminous container restart on image change test we
need to have an identical image to latest-luminous but with a different
ID.
=> [skip ci] contrib: build latest-bis-luminous

contrib/build-push-ceph-container-imgs.sh
Problem: using "make RELEASE=master-bis-luminous
FLAVORS=luminous,centos,7 build" gives the following tag:
daemon:master-bis-luminous-luminous because FLAVORS uses the release
field to produce the tag.
Solution: there is no nede to pass the release in RELEASE so we can get
daemon:master-bis-luminous only.
=> [skip ci] contrib: fix latest release name

tests/tox.sh
In our CI, job can fail because workspace isn't cleaned properly with
following typical error:
```
java.nio.file.FileSystemException:
/home/jenkins-build/build/workspace/ceph-container-nightly-ceph_ansible-jewel-centos7-cluster/staging/luminous-opensuse-42.3-x86_64/daemon/__PACKAGES__:
Operation not permitted
```
staging step is processed as `root` and files are left as it, so we
should use the `clean.all` target from the Makefile to clean everything
after a build is done, regardless the status of the build
(success/failed).
=> tests: clean workspace after a build

contrib/build-push-ceph-container-imgs.sh
This is needed by ceph-ansible to verify idempotency of the playbook
when running it twice.
=> [skip ci] contrib: build a jewel-bis image

src/daemon/osd_scenarios/osd_volume_activate.sh
If the ceph-volume lvm list command fails we want to show the stack
trace from the log file.
=> [skip ci] ceph-volume: show error before activate

src/daemon/zap_device.sh
Although the previous implementation was harmless, it failed to only
remove a single partition from a device. Now you can pass -e
OSD_DEVICE=/dev/sda1, as well as an nvme partition such as
/dev/nvme0n1p2.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1572933
=> zap_device: ability to zap partitions only

contrib/build-push-ceph-container-imgs.sh
The current implementation had numerous issues:
* the releases were built **only** if the tag was present on master,
this is wrong, a tag is applied on a stable branch, e,g: stable-3.0
* the release process would always expect the last commit to be a tag
(in order to build a release)
Now the code checks the tags present on the github remote and compares
it to the one present on the docker hub, if one does not exist
(typically the last new one) it gets built.
=> [skip ci] contrib: build release tags correctly

contrib/build-push-ceph-container-imgs.sh
We have arm64 builds too and we were downloading the amd64 image which
obviously can't run on arm64.
=> [skip ci] contrib: download cn depending on the arch

ceph-releases/ALL/rhel7/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/ALL/rhel7/daemon-base/__DOCKERFILE_VERIFY_PACKAGES__, ceph-releases/ALL/rhel7/daemon-base/__ROOK_PACKAGES__
This reverts commit 4765d7fdbec44ab9acc14fce614398dd737b1334.
The `rook` RPM Requires `ceph-mon`, `ceph-osd`, and `ceph-mgr`, which causes Pungi to pull these packages into the RHCS Tools repository.
Revert the rook addition to the RHCS container so we can remove Rook for RHCS 3.1. When the rook packaging is fixed in https://bugzilla.redhat.com/show_bug.cgi?id=1598522 we can add it back in.
=> Revert "DAEMON_PACKAGES: Adding rook package"

tests/tox.sh
in ceph-ansible requirements.txt is now managed in each respective
branch so it's now the same filename in all branches.
=> tests: update python requirements

tests/tox.sh
Update the ceph-ansible requirements.txt picked up in ceph-container
tests accordingly with the ceph-ansible branch being tested.
(cherry picked from commit c748e107bcbdf6c76398c7238778763667607799)
=> tests: update ceph-ansible requirements.txt picked up

contrib/build-push-ceph-container-imgs.sh
We recently introduced v3.0.1rc1 which was not covered by the regex that
searches tags, now it's taken into account.
=> [skip ci] contrib: allow pattern matching for rc tags

.travis.yml, src/daemon/demo.sh, src/daemon/start_rgw.sh, src/daemon/variables_entrypoint.sh
We can now pass -e RGW_FRONTENDS and enable more options.
=> [skip ci] rgw: allow override RGW_FRONTENDS

ceph-releases/ALL/rhel7/__DOCKERFILE_MAINTAINER__, ceph-releases/ALL/rhel7/daemon-base/__DOCKERFILE_PREINSTALL__
Resolved the following checks:
FAIL:Label 'io.openshift.expose-services' has to be specified.
FAIL:Label 'maintainer' has to be specified.
FAIL:Dockerfile instruction `MAINTAINER` is deprecated.
=> [skip ci] rhel7: make Dockerfile linting happy

Makefile
PR #1083 stopped building openSUSE images. Re-enable builds of openSUSE
containers.
Checklist:
=> makefile: Build and push openSUSE images

ceph-releases/ALL/rhel7/daemon-base/__DOCKERFILE_PREINSTALL__
The following label added in daae090424157c41a2567acd4c0764c54703a41f :
`LABEL io.openshift.expose-services` is an incorrect syntax.
By the way, this LABEL is not needed and should be removed according to
https://github.com/user-cont/colin/issues/165
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1610454
=> rhel7: remove wrong label format

src/daemon/variables_entrypoint.sh
Since we enforce the shortname, we must keep backward compatibility with
previous configuration that used to use fqdn.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1603202
=> mon: backward compatibility with fqdn configuration

src/daemon/common_functions.sh
The cluster name is already known thanks to the $CLUSTER env var so
let's re-use it.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1614878
=> mount_lockbox: do not discover CLUSTER name

tests/teardown.sh
Description of your changes: Sets owner of `$CEPH_ANSIBLE_SCENARIO_PATH/staging` to jenkins user so the slaves can wipe the workspace before each job.
Resolves #1048 
Checklist:
=> tests: set owner of staging dir to jenkins user

contrib/build-push-ceph-container-imgs.sh
This fixes the situation where we have a tag v3.0.1 but v3.0.1rc1 exists
too. The old version of the grep will match both to true so it won't
find any new addition. The regex wasn't precise enough. Now we either
check the exact match is the last or in-between the list.
=> [skip ci] contrib: fix stable release build

tests/teardown.sh
maint-lib/stagelib/__pycache__ was still owned by root
=> tests: make clean during teardown

src/daemon/demo.sh
The RGW_NAME variable is intended to be use instead of the
hostname when applicable.
Fixes: d1e2d07b8b8c ("demo: oversimply the setup")
Signed-off-by: Zac Medico <zmedico@gmail.com>
@leseb
=> demo: respect ${RGW_NAME} more

src/daemon/__DAEMON_PACKAGES__, src/daemon/docker_exec.sh, src/daemon/entrypoint.sh.in, src/daemon/osd_scenarios/osd_disk_activate.sh, src/daemon/osd_scenarios/osd_volume_activate.sh
The actual SIGTERM handler was racy as it didn't waited the targeted PID to actually die before running the post script.
Adding a wait() just after the kill was an initial though but failed as we are in a sig context and another wait is already pending in the exec().
This part of the program have to handle two cases :
- managing a fault of the exec'd program (return < 0 or SEGFAULT)
- managing the graceful shutdown triggered by the SIGTERM sent by docker
Both cases are considering watching the state of the exec'd program.
Having two wait() calls (one in _term(), one in exec()) isn't possible.
The actual implementation is considering the following :
- we just track the presence of the exec'd process by watching if the PID is running. The return code have no interest here.
- if we got a …
=> docker_exec: Reworking SIGTERM handler

src/daemon/populate_kv.sh
If anybody executes properly the `populate_kvstore` script before booting the cluster, it is expected that it works.
Currently, however, monitor daemons fail with:
ERROR 100: Key not found (/ceph-config/ceph/client_host)
Resolves #901
Checklist:
=> Create /ceph-config/ceph/client_host automatically

contrib/build-ceph-base.sh, contrib/ceph-build-config.sh
Add a meaningful error message if ARCH is not provided when executing
the script.
=> [skip ci] contrib: fix build ceph base

Makefile, maint-lib/makelib.mk
Resolves # 1191
Previous misunderstanding of make's order-only prerequisites. Now
enforce order by explicitly calling make rather than using target
dependencies.
Checklist:
=> Make fix 1191 parallel build fails

contrib/ceph-build-config.sh
When we run in DRY_RUN, no command is executed on the local machine.
DRY_RUN is usually useful to understand what would have been build.
So this patch is avoiding install the docker packages when DRY_RUN is engaged.
Signed-off-by: Erwan Velu <erwan@redhat.com>
Resolves #
Checklist:
=> contrib/ceph-build-config.sh: Don't install packages in DRY_RUN mode

contrib/build-ceph-base.sh
The actual build procedure have a mismatch between the name of the local
image and the one trying to be pushed.
The log shows the following :
info 'Building a new image ceph/ceph-amd64:v11.0.1-20181010'
make_cmd='make --directory=/home/jenkins-build/build/workspace/ceph-container-build-ceph-base-push-imgs/ceph-container/contrib/..         FLAVORS=kraken-11.0.1,centos,7         IMAGES_TO_BUILD=daemon-base         TAG_REGISTRY=ceph         DAEMON_BASE_TAG=ceph/ceph-amd64:v11.0.1-20181010         BASEOS_REGISTRY=amd64         BASEOS_REPO=centos         BASEOS_TAG=7       build'
[...]
docker push ceph/ceph-amd64:v11.0.1-20181010
The push refers to a repository [docker.io/ceph/ceph-amd64]
An image does not exist locally with the tag: ceph/ceph-amd64
But the actual docker images is : …
=> contrib/build-ceph-base.sh: Removing TAG_REGISTRY

contrib/commit-rhcs.sh
This simple script allow resyncing the downstream versions with the upstream ones.
It does clone the upstream, make the compose, add some checks and offer to commit it.
This clearly simplify the release process.
Resolves #
Checklist:
=> [skip ci] contrib: Adding commit-rhcs

src/daemon/populate_kv.sh
Typo introduced in https://github.com/ceph/ceph-container/pull/1186, that was making it not actually fixing #901.
Resolves #
Checklist:
=> Fix typo when creating client_host

contrib/build-ceph-base.sh, contrib/ceph-build-config.sh, contrib/make-ceph-base-manifests.sh
I went through running a dry-run of the ceph/ceph image creation scripts, and I made 2 notable fixes.
I noticed that all ceph/ceph images have been built repeatedly for the past 5+ days. The centos:7 base image hasn't updated in a week or more. The source of this issue resulted from the base image not having an ID when doing `docker history ceph/ceph:v...`. Fix this.
Fix an unlikely bug where a manifest image doesn't exist where the
script tries to apply minor/major version tags to it. Also a minor issue
to checking for dry run status.
N/A
Checklist:
=> contrib: minor fixes to base manifest script

Makefile, README.md, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, contrib/ceph-build-config.sh
Testing the master release of ceph is useful for many.
This patch is about adding a new flavor to support it.
To achieve that the following changes are made in this commit :
- download.ceph.com remains the repo for releases
- shaman.ceph.com   becomes the repo for master
REPO_URL variable is feed with the proper repo regarding the CEPH_VERSION
Finding the right repo on shaman requires 'jq' which is provided by epel.
So epel is now installed _before_ we try to install the ceph/ganesha rpms.
Note both ganesha & ceph are taken from shaman when CEPH_VERSION is set to master
On shaman, the main package is name ceph-release-1-0 while its ceph-release-1-1 on download.ceph.com
RELEASE_VER variable is feed with the appropriate value regarding the CEPH_VERSION
As shaman doesn't provides any arm64 …
=> centos: Adding CEPH_VERSION=master support

contrib/build-push-ceph-container-imgs.sh
We are now building through each PR merged the latest ceph package
available at build time, which corresponds to the latest version dev
version. This commit adds a tag to that image 'latest-master' so whoever
wants to always fetch the latest ceph dev version can.
=> contrib: push tag latest-master

contrib/ceph-build-config.sh
So we can attempt to run the manifest script on arm64.
=> [skip ci] contrib: ability to override BUILD_SERVER_GOARCH

Makefile, ceph-releases/ALL/debian/9/__OS_CODENAME__, ceph-releases/ALL/debian/__DOCKERFILE_MAINTAINER__, ceph-releases/ALL/debian/__DOCKERFILE_POSTINSTALL_CLEANUP__, ceph-releases/ALL/debian/daemon-base/__DOCKERFILE_INSTALL__, ceph-releases/ALL/debian/daemon-base/__DOCKERFILE_PREINSTALL__, ceph-releases/ALL/debian/daemon-base/__DOCKERFILE_VERIFY_PACKAGES__, ceph-releases/ALL/debian/daemon-base/__EXTRA_POSTINSTALL_CLEANUP__, ceph-releases/ALL/debian/daemon-base/__GANESHA_PACKAGES__, ceph-releases/ALL/debian/daemon/__DOCKERFILE_INSTALL__, ceph-releases/ALL/debian/daemon/__DOCKERFILE_VERIFY_PACKAGES__, ceph-releases/ALL/debian/daemon/__EXTRA_POSTINSTALL_CLEANUP__
Ceph is deployed more and more on many aarch64 machines.
We can see that many users are becoming ARM players.
Signed-off-by: Nan Li <herbert.nan@linaro.org>
Resolves #
Checklist:
=> Add debian flavor for aarch64

contrib/build-ceph-base.sh, contrib/ceph-build-config.sh, contrib/make-ceph-base-manifests.sh
Add `export SHELLOPTS` to export the parent's shell options to
subshells so they definitely run with `-e` option.
Add `-E` (errtrace) option to scripts since this is needed for `-e` to
properly fail from subshells.
Move ERR trap to build config so that the manifest creation script also
gets this.
Resolves #
Checklist:
=> [skip ci] contrib: fix error handling in ceph/ceph scripts

contrib/ceph-build-config.sh
Since 4cab875f888cb7933423430bd7b80e4792c2115a we fail for return code
!= 0 in subshell (-E option), thus when trying to fetch the repo for the
'master' release this fails since master packages do not live in
download.ceph.com. Building master was introduced in
c8c1931c8dc575495607fea7794d5aaab3b6f457 and I'm partially reverting it.
In the first, the base build script should have not been modified.
=> contrib: do not build master on 'base' builds

src/daemon/start_rbd_target_api.sh, src/daemon/start_rbd_target_gw.sh, src/daemon/start_tcmu_runner.sh
The rbd-target-api, rbd-target-gw and tcmu-runner containers need configfs mounted at /sys/kernel/config.
Closes: https://github.com/ceph/ceph-container/issues/1214
=> iscsi: fix mount configfs

contrib/ceph-build-config.sh
We must declare DRY_RUN but not assign anything, if we don't the script
will fail because of the -u option.
Fix /home/jenkins-build/build/workspace/ceph-container-build-ceph-base-push-imgs/ceph-container/contrib/ceph-build-config.sh: line 464: DRY_RUN: unbound variable
=> contrib: declare DRY_RUN empty

src/daemon/config.static.sh
Nautilus removed the flag --set-uid=0
Resolves #
Checklist:
=> mon: remove unexisting option for nautilus

src/daemon/start_mon.sh
Please consider for merging.
`get_ip` incorrently returned string `[]` when IPv6 detection
failed, leading to skipped IPv4 auto detection and unknown
address to continue.
Checklist:
=> start_mon: fix NETWORK_AUTO_DETECT=1 IPv4 lookup

contrib/make-ceph-base-manifests.sh
Some versions of bash seem to treat printing an array with no elements
as an unbound variable error. Add a default empty to the variable
reference to fix this.
Checklist:
=> [skip ci] contrib: fix unbound var error in manifest script

contrib/ceph-build-config.sh
Tag quotes were incorrectly output as
`tags: ["v12 v12.2"]
This correctly quotes tags as
`tags: ["v12", "v12.2"]
=> [skip ci] contrib: fix manifest script tag quotes

.travis.yml
This is an attempt to overcome the error 'No output has been received in
the last 10m0s,', see https://github.com/travis-ci/travis-ci/issues/6590
Also trying to force Xenial.
=> travis: add sudo: required

src/daemon/start_rbd_mirror.sh
Don't use the rbd profile but the rbd-mirror one
=> rbd-mirror: apply the right profile to the key

src/daemon/start_rbd_mirror.sh
The flag is required since the rbd-mirror accesses the OSDs.
Resolves #
Checklist:
=> rbd-mirror: add missing rbd profile for osd

ceph-releases/luminous/daemon/config.static.sh, ceph-releases/luminous/daemon/start_rbd_mirror.sh, ceph-releases/luminous/daemon/variables_entrypoint.sh, ceph-releases/mimic/daemon/config.static.sh, ceph-releases/mimic/daemon/start_rbd_mirror.sh, ceph-releases/mimic/daemon/variables_entrypoint.sh, src/daemon/config.static.sh
Commits f0cc4c743073aaf83b186a6e4363f580d1fac35c, f5c404f62f6e5ec7f0ad80a3d96f134614cf00f9, 91b76d868fd14e41cfdc7d167f7332fc2b38f352 introduced some changes that are effective starting nautilus.
They put those changes inside src/ meaning all versions are affected breaking luminous & mimic builds.
This PR is about restoring the files priori this commits inside the luminous & mimic directories.
This way, src/ remains all versions and support the "future" code while ceph-releases/{luminous,mimic} keep the exceptions that will vanish once they will be EOL.
Resolves #
Checklist:
=> ceph-releases: Restoring rbd behavior for luminous/mimic

src/daemon/README.md, src/daemon/start_mon.sh
Please consider merging this or something similar.
Usefull when running CI against temporary ceph cluster created
with demo mode.
Description of your changes: adds NEW_USER_KEYRING variable when starting in demo mode. Enables injecting existing keyring to keyrings.
Resolves #
Checklist:
=> mon: add ability to inject existing keyring

ceph-releases/luminous/daemon-base/__GANESHA_PACKAGES__, ceph-releases/mimic/daemon-base/__GANESHA_PACKAGES__, src/daemon-base/__GANESHA_PACKAGES__
In order to deploy ganesha in a clustered configuration, we need the ganesha-rados-grace command. That's packaged separately in the nfs-ganesha-rados-grace package.
I'm not sure whether this is the correct fix however, as older versions of ganesha (before v2.7) didn't have this package, and so the installation attempt might fail.
=> Pull in nfs-ganesha-rados-grace package

src/daemon/demo.sh
The current code was waiting for 5 secs before trying to create the bucket.
The whole container usually starts in 25 secs meaning that a 1/5th is spent here.
This patch is poking the s3 service to see if it's available.
The loop is waiting up to 5 seconds.
Once the radosgw is ready, the bucket is created.
Tests on a private server showed that a single loop is enough, saving 5 seconds on the start process.
Resolves #
Checklist:
=> src/daemon/demo.sh: Dynamic sleep instead of harcoded value

src/daemon/common_functions.sh
To fix a mutation of the race condition where you create partitions and
udev takes time to inform the kernnel to create the node. We basically
wait for the device to appear and eventually fail if not showing up.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1648010
=> ceph-disk: bluestore wait for all partition

src/daemon/entrypoint.sh.in, src/daemon/variables_entrypoint.sh
Exit early if trying to run the daemon container on untested
architectures.  This has been written such that it's clear what's
supported but also so it can be tested trivially without requiring a
rebuild.
Checklist:
=> Make it explicit which architectures are supported

src/daemon/entrypoint.sh.in, src/daemon/variables_entrypoint.sh
Exit early if trying to run the daemon container on untested
architectures.  This has been written such that it's clear what's
supported but also so it can be tested trivially without requiring a
rebuild.
cherry-pick #1227
Checklist:
- [ n/a ] Documentation has been updated, if necessary.
- [ n/a ] Pending release notes updated with breaking and/or notable changes, if necessary.
CC: @tbreeds, @ktdreyer
=> [stable-3.2] Make it explicit which architectures are supported

src/daemon/osd_scenarios/osd_volume_activate.sh
Instead of requiring OSD_OBJECTSTORE to be set for activation we now
discover the objectstore on the fly.
=> ceph_volume_active: auto discover of osd type

src/daemon/osd_scenarios/osd_directory.sh, src/daemon/osd_scenarios/osd_disk_activate.sh, src/daemon/osd_scenarios/osd_disks.sh
Commit 207373b introduce a move of script files in /opt/ceph-container.
Some files were not updated correctly. This patch is about adding the right path when sourcing those files.
Original commit from Carlos Almeida (https://github.com/cmsalmeida)
This is a takeover of #1267 to ensure a quick merge while keeping a good commit quality
=> src/daemon: Define path for when sourcing osd scripts

src/daemon-base/__CEPH_BASE_PACKAGES__
Rook expects sgdisk to be in images alongside Ceph. Add this to the base
packages list.
**Note:** The ideal fix for the situation is to allow Rook to use its own sgdisk, but this is the quickest option to get it fixed in Rook v0.9
=> daemon-base: add gdisk to ceph base packages

src/daemon/README.md
These 2 options are not used anymore, you need to update your ceph.conf
directly and the rgw process will take that up.
Resolves #
Checklist:
=> [skip ci] rgw: remove old doc

contrib/ceph-versioned-image-descriptions.md
Add an .md file containing description text for the `ceph` images now
published on DockerHub.
@leseb, could you update the Docker Hub description of the `ceph/ceph-{,amd64,arm64}` images based on the text here once the text is approved? This file needn't make it into the ceph-container source, as the description on Docker Hub is the more important item; however, I think it might be a good idea to have this versioned.
=> [skip ci] Ceph image dockerhub descriptions

contrib/build-push-ceph-container-imgs.sh
For each ceph stable release we need the bis equivalent for
ceph-ansible.
=> contrib: build more latest-bis images

README.md
* openSUSE
* CentOS
* better marking of lack of support of Ubuntu Image
Signed-off-by: Christian Berendt <berendt@betacloud-solutions.de>
=> README: fix some nits

ceph-releases/luminous/daemon-base/__GANESHA_PACKAGES__, ceph-releases/mimic/daemon-base/__GANESHA_PACKAGES__
Because of the override specificity (copied from docs below)
`__GANESHA_PACKAGES__` for centos-arm64 were getting pulled from
`ceph-releases/{luminous,mimic}/daemon-base` and not from
`ceph-releases/ALL/centos-arm64/daemon-base`. Since
`__GANESHA_PACKAGES__` exists in `src/daemon-base` and since the
contents of the file for luminous and mimic were both exactly the same,
there should be no more need to have these files. And this fixes the
centos-arm64 staging.
```
ceph-releases/<ceph release>/<base os repository>/<base os release>/{daemon-base,daemon}/FILE
ceph-releases/<ceph release>/<base os repository>/<base os release>/FILE
ceph-releases/<ceph release>/<base os repository>/{daemon-base,daemon}/FILE
ceph-releases/<ceph release>/<base os repository>/FILE
ceph-releases/<ceph …
```
=> Remove ganesha packages from luminous/mimic

ceph-releases/ALL/opensuse/__CEPH_BASE_PACKAGES__
The current repos do not provide the 'gdisk' package, so removing it
temporarily until this is fixed. This is breaking the image build CI.
=> suse: remove gdisk package

src/daemon/start_mon.sh, src/daemon/variables_entrypoint.sh
You can now set '-e MON_PORT' to anything and the monitor will listen on
that port if possible.
=> mon: ability to change mon listening port

src/daemon/start_osd.sh
The TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES variable is defined in the
/etc/sysconfig/ceph file and sourced during the start_osd.sh script
execution.
If this variable has been set using ceph-ansible (via the variable
called ceph_tcmalloc_max_total_thread_cache), the container will have
this variable defined as an environment variable.
Unfortunately the source of the /etc/sysconfig/ceph file will
override the value defined by the environment variable.
This commit aims to set the right tcmalloc value when the environment
variable is present.
=> daemon/osd: Allow to override tcmalloc value

src/daemon/start_mon.sh
Don't use the detected interface if CEPH_ETH is defined.  Detected based
on the amount of traffic over the interface is not always the
wanted behaviour.
=> Allow the monitor interface to be provided

src/daemon/config.static.sh, src/daemon/demo.sh, src/daemon/start_mon.sh, travis-builds/validate_demo_cluster.sh
The values applied are causing the ceph-osd to crash on earlier versions
thus we perform the memory tuning on Nautilus and above only.
Closes: https://github.com/ceph/ceph-container/issues/1293
=> osd: apply memory tuning on nautilus only

contrib/build-push-ceph-container-imgs-arm64.sh, contrib/build-push-ceph-container-imgs.sh
Description of your changes: sets the `noninteractive` value when calling out to `apt-get` so that the system doesn't need to prompt for anything, preventing potential hangs
Which issue is resolved by this Pull Request: https://github.com/ceph/ceph-container/issues/1306
Resolves #
=> set `noninteractive` when installing with apt-get

ceph-releases/luminous/daemon-base/__CEPH_MGR_PACKAGE__, ceph-releases/mimic/daemon-base/__CEPH_MGR_PACKAGE__, src/daemon-base/__CEPH_MGR_PACKAGE__
We want ceph-mgr-rook to be installed on nautilus and later images, but
earlier releases didn't have that package. Add it to the base
`__CEPH_MGR_PACKAGE__` file and add override files for luminous and mimic.
Signed-off-by: Jeff Layton <jlayton@redhat.com>
=> Add ceph-mgr-rook to nautilus images

src/daemon-base/__CEPH_MGR_PACKAGE__
rook expects the dashboard to be available.
Signed-off-by: Jeff Layton <jlayton@redhat.com>
=> Add dashboard mgr module by default

Makefile, contrib/ceph-build-config.sh
contrib: add nautilus to ceph/ceph build scripts
Checklist:
=> contrib: add nautilus to ceph/ceph build scripts

Makefile, contrib/ceph-build-config.sh
Reverts ceph/ceph-container#1316
We are reverting for multiple reasons:
* no package for ganesha on Nautilus yet
* no packages at all of arm64
* no ceph-release file, so no repo file can be fetched
Revert while requisite Nautilus packages are not available.
=> Revert "contrib: add nautilus to ceph/ceph build scripts"

Makefile, contrib/ceph-build-config.sh
=> contrib: enable nautilus builds for x86_64 only

contrib/build-push-ceph-container-imgs.sh
The first RCs are out and Nautilus is around the corner, so we can start
building images from the RC.
=> contrib: add nautilus image to docker hub

contrib/ceph-build-config.sh
We now have packages for arm64 for Nautilus here:
http://download.ceph.com/rpm-nautilus/el7/aarch64/ so we can build that
new image.
=> contrib: add arm64 image build for nautilus

src/daemon/demo.sh, src/daemon/osd_scenarios/osd_directory_single.sh, src/daemon/osd_scenarios/osd_volume_activate.sh, src/daemon/variables_entrypoint.sh, src/daemon/watch_mgr_health.sh
Currently some entrypoint scripts were using python command. This
will in most of case refers to python 2 and not python 3.
Instead of hardcoding the python binary in the shell scripts we can
test if the binary exist and set the PYTHON variable.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1690093
=> daemon: Add support for python3

ceph-releases/luminous/daemon/variables_entrypoint.sh, ceph-releases/mimic/daemon/variables_entrypoint.sh, src/daemon/variables_entrypoint.sh
778c7f9 introduces the python binary detection based on the
is_available function. Unfortunately this function is source after
variables_entrypoint.sh in the entrypoint so it's not possible to
use it.
Also Luminous and Mimic release have a different variables entrypoint
script they're modified to reflect the python change.
=> daemon/variables_entrypoint Fix python detection

ceph-releases/luminous/daemon/osd_scenarios/osd_disk_activate.sh, ceph-releases/mimic/daemon/osd_scenarios/osd_disk_activate.sh, src/daemon/osd_scenarios/osd_disk_activate.sh
In Nautilus release, the ceph-disk command isn't supported anymore.
Instead we should migrate to ceph-volume.
To keep the backward compatibility with old container images using
the osd_ceph_disk_activate entrypoint, we need to replace the
osd_activate function with ceph-volume simple scan/activate commands
otherwise the container won't be able to start after upgrading from
Luminous or Mimic container image.
The new version of osd_disk_activate.sh is only available for Nautilus
and above releases. Older releases (Luminous and Mimic) keep the
previous one.
http://docs.ceph.com/docs/master/ceph-volume/#migrating
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1656506
=> daemon/osd: Migrate ceph-disk to ceph-volume

README.md, ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__, maint-lib/ceph_version.sh
You can now build an image out of a branch like so:
`make FLAVORS="wip-dev,centos,7" build`
The branch name MUST start with 'wip'.
=> build: ability to build an image on a branch

src/daemon/osd_scenarios/osd_disk_activate.sh
07abbbe has been merged without being rebase with 778c7f9 changes.
This mades 07abbbe non python 3 compatible.
=> osd_disk_activate: Use python binary variable

ceph-releases/luminous/daemon/config.static.sh, ceph-releases/mimic/daemon/config.static.sh, src/daemon/config.kv.etcd.sh, src/daemon/config.static.sh
The administrator keyring needs full capabilities on mds like mon,
osd and mgr.
Whithout this, the client.admin key won't be able to run commands
against mds (like ceph tell mds.0 session ls)
Resolves: #1333
=> daemon: Fix mds permissions to client.admin

ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_POSTINSTALL_CLEANUP__, ceph-releases/ALL/rhel7/daemon-base/__DOCKERFILE_POSTINSTALL_CLEANUP__, ceph-releases/ALL/rhel8/daemon-base/__DOCKERFILE_POSTINSTALL_CLEANUP__
When entering the container we always get this annoying warning:
bash: warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_MESSAGES: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_NUMERIC: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_TIME: cannot change locale (en_US.UTF-8): No such file or directory
Because the locale is not available, to fix this issue let's remove the
lang file which contains the local to set.
=> base: remove lang.sh

contrib/build-push-ceph-container-imgs.sh
When the latest tag is the same than the HEAD ref we have two refs to
that tag causing the script to not build the avaiblable tag.
```console
$ git ls-remote --tags
(...)
4101899ab55e916ad7da625daf330d6ea5a11d09	refs/tags/v4.0.0rc1
15d8573c1d9dfedbda9ca012f3609497704e34af	refs/tags/v4.0.0rc1^{}
```
This build script will then throw an error like:
```console
+ echo 'ERROR: it looks like more than one tag are not built, see
v4.0.0rc1 v4.0.0rc1.'
ERROR: it looks like more than one tag are not built, see v4.0.0rc1
v4.0.0rc1.
+ git checkout 'refs/tags/v4.0.0rc1 v4.0.0rc1'
error: pathspec 'refs/tags/v4.0.0rc1 v4.0.0rc1' did not match any
file(s) known to git.
++ git branch -r --contains 'tags/v4.0.0rc1 v4.0.0rc1'
++ grep -Eo 'stable-[0-9].[0-9]'
error: malformed object name tags/v4.0.0rc1 …
```
=> [skip ci] contrib: Do not show HEAD ref in git ls-remote

ceph-releases/ALL/rhel7/daemon-base/__DOCKERFILE_POSTINSTALL_CLEANUP__, ceph-releases/ALL/rhel8/daemon-base/__DOCKERFILE_POSTINSTALL_CLEANUP__
Commit 15d8573c1d9dfedbda9ca012f3609497704e34af introduced a syntax error because we omitted the `&&`, so `sed` was trying to interpret the `rm`, `-f` etc. as additional arguments.
Add the `&&` so the shell interprets the `sed` and `rm` as two separate commands.
=> base: fix lang.sh removal on RHEL

.travis.yml
We don't really need to push every travais image build for PR on
docker hub.
There's also an issue because we're using docker login with
credentials that can't be used for everybody.
=> travis: Remove image push to docker hub

src/daemon-base/__CEPH_BASE_PACKAGES__, src/daemon-base/__CSI_PACKAGES__
We want to use our base image for ceph-csi. ceph-csi needs extra
packages so we are adding them.
=> base: add packages for ceph-csi

src/daemon/osd_scenarios/osd_disk_activate.sh
When try to determine osd id with dmcrypt enabled expect that
/dev/mapper/device will be visible in /proc/mounts table.
Closes: #1343
Resolves #1343
Checklist:
=> With dmcrypt expect /dev/mapper/device to be used

contrib/build-push-ceph-container-imgs.sh
We currently only filter image tags that are like:
- vX.X.X
- vX.X.XrcX
Unfortunately we have a v4.0.0beta tag present on docker hub. Due
to the regex this tag is considered as v4.0.0 so we can build this
tag.
This commit update the tags regex and add alpha and beta suffix like
for rc.
=> contrib: Add alpha/beta tag filtering

src/daemon-base/__CSI_PACKAGES__
Whithout the ceph point release environment variable the CSI packages
create a dependency issue during container image build.
When trying to build an old release, all ceph packages are pinned to
that version except ceph-fuse and rbd-nbd that are using the latest
one.
=> daemon-base: Add ceph point release to csi pkgs

contrib/ceph-build-config.sh
Version sort doesn't work for list as a string. You need a new line
between each element.
```console
$ echo "12.2.0 12.1.9 12.2.3" | sort --version-sort
12.2.0 12.1.9 12.2.3
$ echo -e "12.2.0\n12.1.9\n12.2.3" | sort --version-sort
12.1.9
12.2.0
12.2.3
```
Due to this issue the package version are not listed correctly on the
z release (double z digit aren't take in count).
Before:
12.2.1-0 12.2.10-0 12.2.11-0 12.2.2-0 12.2.3-0
After:
12.2.1-0 12.2.2-0 12.2.3-0 12.2.10-0 12.2.11-0
=> contrib/ceph-build-config.sh: Fix version sort

src/daemon-base/__CEPH_MGR_PACKAGE__
Add diskprediction_local mgr module in order to have the same default
modules present in ceph-ansible and ceph-container.
=> daemon-base: Add ceph-mgr-diskprediction-local pkg

.travis.yml, src/daemon/demo.sh
We now are using beast as radosgw frontend so it doesn't make sense
to keep the civetweb environment variables.
=> travis: Remove civetweb references for demo

ceph-releases/ALL/rhel8/daemon-base/__DOCKERFILE_PREINSTALL__
The RHEL 8's UBI (universal base image) has a `ubi.repo` file that points at repositories that are only available with subscription-manager.
If these repositories are not available, dnf will exit with an error ([rhbz#1701290](https://bugzilla.redhat.com/show_bug.cgi?id=1701290)). We currently build the Ceph RHEL images in an environment that does not use subscription-manager, so dnf cannot access the UBI content, and it bails out at this point.
We already get RHEL 8 build content dynamically from OSBS's Yum repository injection feature, so we do not need anything in this ubi.repo file.
Delete the ubi.repo file entirely to avoid the errors associated with the repositories here.
UBI is a new initiative, so maybe we will find a better workaround in the future.
=> rhel8: rm ubi.repo

src/daemon/osd_scenarios/osd_disk_prepare.sh
We only need to create the block.db and block.wal partitions when
there's a dedicated devices for them.
This is only for bluestore objectstore.
* Collocated scenario now:
```console
/dev/sdb :
/dev/sdb1 ceph data, active, cluster ceph, osd.0, block /dev/sdb2, block.db /dev/sdb3, block.wal /dev/sdb4
/dev/sdb2 ceph block, for /dev/sdb1
/dev/sdb3 ceph block.db, for /dev/sdb1
/dev/sdb4 ceph block.wal, for /dev/sdb1
```
* Collocated scenario should be (the same than non containerized):
```console
/dev/sdb :
/dev/sdb1 ceph data, active, cluster ceph, osd.0, block /dev/sdb2
/dev/sdb2 ceph block, for /dev/sdb1
```
* Non-collocated scenario now:
```console
/dev/sdb :
/dev/sdb1 ceph data, active, cluster ceph, osd.0, block /dev/sdb2, block.db /dev/sde1, block.wal /dev/sdb4
/dev/sdb2 ceph block, for …
```
=> osd_disk_prepare: Don't always create db and wal

src/daemon/demo.sh
If rgw is not used at all (eg when running a minimal demo container with
only osd/mds) it still needs RGW_FRONTEND to be set when using Luminous.
This patch only tests/warns if rgw will be used.
Closes ceph/ceph-container#1358
Signed-off-by: Christian Schwede <cschwede@redhat.com>
Resolves #
Checklist:
=> Only check RGW_FRONTEND if rgw is used

ceph-releases/ALL/rhel8/daemon-base/__DOCKERFILE_PREINSTALL__
For the latest RH Ceph Storage on RHEL 8, we're going to simplify the component name to avoid the "rhel" string and just go with "rhceph". This matches what other products are doing for el8.
=> rhel8: drop "-rhel8" from component label
